### PR TITLE
prov/gni: fix a problem with not truncating recvs

### LINKED ISSUE #5002: prov/gni: messages larger than fi_recv buffer size corrupt adjacent memory
There is no logic in __smsg_eager_msg_w_data() to deal with arriving messages that are larger than the matching posted receive buffer, FI_ETRUNC is not implemented.   An incoming message is matched, then __gnix_msg_copy_data_to_recv_addr() is called to memcpy the incoming message into the matched buffer using the size of the incoming message.  If that size is larger than the size of the receive buffer, or larger than the amount of remaining space in a MULTI-RECV buffer, then the memory following the buffer is overwritten.   Next, __gnix_msg_recv_completion() is called, which uses the minimum of the incoming message size and the receive buffer size to set the 'len' field in the receive completion event.  The application receives an unexpectede successful CQE with the short length, when it should have received a FI_ETRUNC error.

I modified the gnitest cm_basic_send() to issue a fi_send of 8 bytes, and a fi_recv of 4 bytes.

<pre><code>
        uint64_t source = 0xa4321234a4321234,
                 target = 0xb5678901b5678901;

        dbg_printf("before source 0x%lx target 0x%lx\n", source, target);

        sz = fi_send(cli_ep, &source, 8, 0, 0, &target);
        cr_assert_eq(sz, 0);

        sz = fi_recv(srv_ep, &target, 4, 0, 0, &source);
        cr_assert_eq(sz, 0);
...
                ret = fi_cq_read(srv_cq, &cqe, 1);
                if (ret == 1) {
                        dbg_printf("recv cqe.len is %ld\n", cqe.len);
...
        dbg_printf("after source 0x%lx target 0x%lx\n", source, target);
</code></pre>

When the test is run, an unexpected successful 4-byte receive CQE is received, and 4 bytes beyond the receive buffer are destroyed.

<pre><code>
before source 0xa4321234a4321234 target 0xb5678901b5678901
recv cqe.len is 4
after source 0xa4321234a4321234 target 0xa4321234a4321234
</code></pre>

### PR DESCRIPTION
**Pull request by hppritcha**
Have no idea how things were working, but the GNI provider
was incorrectly using the length of the incoming message
for transfer to recv buffers/iovecs rather than the
length of receive buffers.

Fixes #5002

Signed-off-by: Howard Pritchard <howardp@lanl.gov>

### CODE REVIEW

**Comment by hppritcha** [comment]
@krehm could you test this branch with your application?

**Comment by krehm** [comment]
Did you try enabling the multi-recv tests in gnitest, and do they pass?

**Comment by hppritcha** [comment]
Nope I didn't do that.    I'll add code for posting error CQE.

File: prov/gni/test/rdm_multi_recv.c [hunk 1]
```diff
@@ -890,7 +890,7 @@ void do_multirecv_trunc_last(int len)
  * message size of 1 below might change depending on whether 0 is a
  * valid value for FI_OPT_MIN_MULTI_RECV (Github issue #1120)
  */
-Test(rdm_multi_r, multirecv_trunc_last, .disabled = true)
+Test(rdm_multi_r, multirecv_trunc_last, .disabled = false)
 {
```
Comment (krehm) [inline prov/gni/test/rdm_multi_recv.c]: Could you enable tests multirecv, multirecv_retrans, and multirecv_trunc_last_retrans in this file as well?

**Comment by hppritcha** [comment]
@krehm please try this out.  I'd like to get this into 1.7.2 release if its working for you.

**Comment by hppritcha** [comment]
@soumagne could your team try this with HG just in case it fixes the rdma Get problem you're hitting?

**Comment by hppritcha** [comment]
bot:lanl:retest

**Comment by hppritcha** [comment]
cori seems to be having a hard time
bot:lanl:retest
