### PR TITLE
Pr/sockets

### LINKED ISSUE #662: sockets provider: sock_pe_send_response references nonexistent address vector
For connected endpoints, the socket is not (to my knowledge) expected to be bound to an address vector.  The function `sock_pe_send_response` (which gets called when an endpoint receives an RMA or atomic operations) assumes that it is and passes a NULL pointer to `sock_av_lookup_ep_id` and this results in a crash:
```
==8393== Process terminating with default action of signal 11 (SIGSEGV)
==8393==  Access not within mapped region at address 0x60
==8393==    at 0x4C19C26: sock_av_lookup_ep_id (sock_av.c:140)
==8393==    by 0x4C2A6A8: sock_pe_send_response (sock_progress.c:413)
==8393==    by 0x4C2B66A: sock_pe_process_rx_write (sock_progress.c:682)
==8393==    by 0x4C2FEAD: sock_pe_process_recv (sock_progress.c:1349)
==8393==    by 0x4C3161F: sock_pe_progress_rx_pe_entry (sock_progress.c:1793)
==8393==    by 0x4C31901: sock_pe_new_rx_entry (sock_progress.c:1845)
==8393==    by 0x4C327FB: sock_pe_progress_rx_ep (sock_progress.c:2099)
==8393==    by 0x4C32911: sock_pe_progress_rx_ctx (sock_progress.c:2134)
==8393==    by 0x4C32CC4: sock_pe_progress_thread (sock_progress.c:2241)
==8393==    by 0x3AC3C07529: start_thread (in /usr/lib64/libpthread-2.20.so)
```

This can be trivially reproduced with the `simple/fi_msg_rma` example in fabtests.

### PR DESCRIPTION
**Pull request by jithinjosepkl**
- Coverity Fixes
- Fixes #662, #663, #667
- Fix and issue related to op-context reporting

### CODE REVIEW

File: prov/sockets/src/sock_ep_msg.c [hunk 1]
```diff
@@ -641,11 +756,24 @@ static int sock_ep_cm_connect(struct fid_ep *ep, const void *addr,
...
 
+	if (!_ep->cm.listener_thread) {
+		if (pthread_create(&_ep->cm.listener_thread, NULL, 
+				   sock_msg_ep_listener_thread, (void *)_ep)) {
+			SOCK_LOG_ERROR("Couldn't create listener thread\n");
+			return -FI_EINVAL;
+		}
+		
+		while (!(volatile int)_ep->cm.do_listen)
+			pthread_yield();
```
Comment (shefty) [inline prov/sockets/src/sock_ep_msg.c]: Why is the yield necessary?

File: prov/sockets/src/sock_ep_msg.c [hunk 2]
```diff
@@ -702,13 +823,27 @@ static int sock_ep_cm_accept(struct fid_ep *ep, const void *param, size_t paraml
...
+
+	if (!_ep->cm.listener_thread) {
+		if (pthread_create(&_ep->cm.listener_thread, NULL, 
+				   sock_msg_ep_listener_thread, (void *)_ep)) {
+			SOCK_LOG_ERROR("Couldn't create listener thread\n");
+			return -FI_EINVAL;
+		}
+		
+		while (!(volatile int)_ep->cm.do_listen)
+			pthread_yield();
```
Comment (shefty) [inline prov/sockets/src/sock_ep_msg.c]: Same here.  We really don't want to be allocating a new thread every time the user calls connect or accept.

File: prov/sockets/src/sock_progress.c [hunk 3]
```diff
@@ -2111,7 +2120,8 @@ int sock_pe_progress_rx_ctx(struct sock_pe *pe, struct sock_rx_ctx *rx_ctx)
 	struct dlist_entry *entry;
 	struct sock_pe_entry *pe_entry;
 
-	fastlock_acquire(&pe->lock);
+	if (fastlock_tryacquire(&pe->lock))
+		return 0;
```
Comment (shefty) [inline prov/sockets/src/sock_progress.c]: Can you explain the change to use tryacquire?

Comment (jithinjosepkl) [inline prov/sockets/src/sock_progress.c]: Yes, this is to avoid a 'possible' deadlock in manual progress mode.
This is a corner case.

In manual progress mode, cntr_read results in calling progress engine for each tx/rx context, which are maintained as a list in cntr. Calling progress engine results in acquiring pe-lock.
Now, another thread might have already been in progress engine and wants to acquire the cntr_lock. So, to avoid the "hold and wait", i added the try-lock for progress engine.

But, now I see another possible case like the following:
cntr_lock -> progress_engine_lock -> cntr_lock, (for the same cntr, and by same thread) because of cntr_read() -> progress() -> cntr_update(). 

Another solution is to release the cntr_lock before entering the progress engine.
(Same for CQ). But in this case, I need to make sure the tx/rx context list updates by another thread are not causing issues to the current thread's list traversal. The more I think, this seems to be a better solution, and avoids both the cases.

Comment (jithinjosepkl) [inline prov/sockets/src/sock_progress.c]: Another approach: We can add another lock for counter update/read operation.
So, we will never hit the hold-and-wait issue in manual-progress mode. 
Same for CQs.

Any thoughts?

Comment (shefty) [inline prov/sockets/src/sock_progress.c]: I would need to study the code in detail to suggest anything.

**Comment by shefty** [comment]
Can you update the patch set over the tip of the tree?

**Comment by jithinjosepkl** [comment]
@shefty, I have updated the patch set over the tip.
