### PR TITLE
prov/psm2: Fix format mismatch warnings

### LINKED ISSUE #3388: psm/psm2 build warnings on Linux
Used GCC version is 4.8.5

The psm's warnings:
```
prov/psm/src/psmx_init.c: In function ‘psmx_getinfo’:
prov/psm/src/psmx_init.c:251: warning: format ‘%llx’ expects type ‘long long unsigned int’, but argument 9 has type ‘psm_epid_t’
prov/psm/src/psmx_init.c:302: warning: format ‘%d’ expects type ‘int’, but argument 7 has type ‘size_t’
prov/psm/src/psmx_init.c:309: warning: format ‘%d’ expects type ‘int’, but argument 7 has type ‘size_t’
prov/psm/src/psmx_init.c:318: warning: format ‘%llx’ expects type ‘long long unsigned int’, but argument 7 has type ‘uint64_t’
prov/psm/src/psmx_init.c:327: warning: format ‘%llx’ expects type ‘long long unsigned int’, but argument 7 has type ‘uint64_t’
prov/psm/src/psmx_init.c:335: warning: format ‘%ld’ expects type ‘long int’, but argument 8 has type ‘int’
prov/psm/src/psmx_init.c:347: warning: format ‘%llx’ expects type ‘long long unsigned int’, but argument 7 has type ‘uint64_t’
prov/psm/src/psmx_init.c:356: warning: format ‘%llx’ expects type ‘long long unsigned int’, but argument 7 has type ‘uint64_t’
prov/psm/src/psmx_ep.c: In function ‘psmx_ep_open’:
prov/psm/src/psmx_ep.c:423: warning: format ‘%d’ expects type ‘int’, but argument 7 has type ‘size_t’
prov/psm/src/psmx_ep.c:423: warning: format ‘%d’ expects type ‘int’, but argument 8 has type ‘long unsigned int’
prov/psm/src/psmx_init.c:457: warning: format ‘%ld’ expects type ‘long int’, but argument 8 has type ‘long long unsigned int’
prov/psm/src/psmx_init.c:470: warning: format ‘%lx’ expects type ‘long unsigned int’, but argument 8 has type ‘int’
prov/psm/src/psmx_init.c:479: warning: format ‘%lx’ expects type ‘long unsigned int’, but argument 8 has type ‘int’
prov/psm/src/psmx_domain.c: In function ‘psmx_domain_check_features’:
prov/psm/src/psmx_domain.c:425: warning: format ‘%llx’ expects type ‘long long unsigned int’, but argument 7 has type ‘uint64_t’
prov/psm/src/psmx_domain.c:425: warning: format ‘%llx’ expects type ‘long long unsigned int’, but argument 8 has type ‘int’
prov/psm/src/psmx_init.c:513: warning: format ‘%lx’ expects type ‘long unsigned int’, but argument 8 has type ‘int’
prov/psm/src/psmx_init.c:522: warning: format ‘%lx’ expects type ‘long unsigned int’, but argument 8 has type ‘int’prov/psm/src/psmx_domain.c: In function ‘psmx_domain_enable_ep’:

prov/psm/src/psmx_domain.c:458: warning: format ‘%llx’ expects type ‘long long unsigned int’, but argument 7 has type ‘uint64_t’
prov/psm/src/psmx_domain.c:458: warning: format ‘%llx’ expects type ‘long long unsigned int’, but argument 8 has type ‘uint64_t’
prov/psm/src/psmx_av.c: In function ‘psmx_av_open’:
prov/psm/src/psmx_av.c:414: warning: format ‘%x’ expects type ‘unsigned int’, but argument 7 has type ‘uint64_t’
prov/psm/src/psmx_av.c:414: warning: format ‘%x’ expects type ‘unsigned int’, but argument 8 has type ‘long long unsigned int’
```

The psm2's warnings:
```
prov/psm2/src/psmx2_util.c: In function ‘psmx2_string_to_ep_name’:
prov/psm2/src/psmx2_ep.c: In function ‘psmx2_ep_open_internal’:
prov/psm2/src/psmx2_util.c:124:3: warning: format ‘%s’ expects argument of type ‘char *’, but argument 7 has type ‘const void *’ [-Wformat=]
   FI_INFO(&psmx2_prov, FI_LOG_CORE,
   ^
prov/psm2/src/psmx2_av.c: In function ‘psmx2_av_open’:
prov/psm2/src/psmx2_domain.c: In function ‘psmx2_domain_check_features’:
prov/psm2/src/psmx2_ep.c:520:4: warning: format ‘%d’ expects argument of type ‘int’, but argument 7 has type ‘size_t’ [-Wformat=]
    FI_WARN(&psmx2_prov, FI_LOG_EP_CTRL,
    ^
prov/psm2/src/psmx2_ep.c:520:4: warning: format ‘%d’ expects argument of type ‘int’, but argument 8 has type ‘long unsigned int’ [-Wformat=]
prov/psm2/src/psmx2_am.c: In function ‘psmx2_am_init’:
prov/psm2/src/psmx2_ep.c: In function ‘psmx2_sep_open’:
prov/psm2/src/psmx2_util.c:130:3: warning: format ‘%s’ expects argument of type ‘char *’, but argument 7 has type ‘const void *’ [-Wformat=]
   FI_INFO(&psmx2_prov, FI_LOG_CORE,
   ^
prov/psm2/src/psmx2_domain.c:536:3: warning: format ‘%llx’ expects argument of type ‘long long unsigned int’, but argument 7 has type ‘uint64_t’ [-Wformat=]
   FI_INFO(&psmx2_prov, FI_LOG_CORE,
   ^
prov/psm2/src/psmx2_domain.c:536:3: warning: format ‘%llx’ expects argument of type ‘long long unsigned int’, but argument 8 has type ‘int’ [-Wformat=]
prov/psm2/src/psmx2_av.c:758:4: warning: format ‘%x’ expects argument of type ‘unsigned int’, but argument 7 has type ‘uint64_t’ [-Wformat=]
    FI_INFO(&psmx2_prov, FI_LOG_AV,
    ^
prov/psm2/src/psmx2_av.c:758:4: warning: format ‘%x’ expects argument of type ‘unsigned int’, but argument 8 has type ‘long long unsigned int’ [-Wformat=]
prov/psm2/src/psmx2_am.c:292:4: warning: format ‘%d’ expects a matching ‘int’ argument [-Wformat=]
    FI_WARN(&psmx2_prov, FI_LOG_CORE,
    ^
prov/psm2/src/psmx2_am.c:292:4: warning: format ‘%d’ expects a matching ‘int’ argument [-Wformat=]
prov/psm2/src/psmx2_ep.c:923:4: warning: format ‘%d’ expects argument of type ‘int’, but argument 7 has type ‘size_t’ [-Wformat=]
    FI_WARN(&psmx2_prov, FI_LOG_EP_CTRL,
    ^
prov/psm2/src/psmx2_domain.c: In function ‘psmx2_domain_enable_ep’:
prov/psm2/src/psmx2_ep.c:930:4: warning: format ‘%d’ expects argument of type ‘int’, but argument 7 has type ‘size_t’ [-Wformat=]
    FI_WARN(&psmx2_prov, FI_LOG_EP_CTRL,
    ^
prov/psm2/src/psmx2_domain.c:556:3: warning: format ‘%llx’ expects argument of type ‘long long unsigned int’, but argument 7 has type ‘uint64_t’ [-Wformat=]
   FI_INFO(&psmx2_prov, FI_LOG_CORE,
   ^
prov/psm2/src/psmx2_domain.c:556:3: warning: format ‘%llx’ expects argument of type ‘long long unsigned int’, but argument 8 has type ‘uint64_t’ [-Wformat=]
prov/psm2/src/psmx2_init.c: In function ‘psmx2_getinfo’:
prov/psm2/src/psmx2_init.c:256:4: warning: format ‘%llx’ expects argument of type ‘long long unsigned int’, but argument 8 has type ‘psm2_epid_t’ [-Wformat=]
    FI_INFO(&psmx2_prov, FI_LOG_CORE,
    ^
prov/psm2/src/psmx2_init.c:313:4: warning: format ‘%llx’ expects argument of type ‘long long unsigned int’, but argument 9 has type ‘psm2_epid_t’ [-Wformat=]
    FI_INFO(&psmx2_prov, FI_LOG_CORE,
    ^
prov/psm2/src/psmx2_init.c:368:5: warning: format ‘%d’ expects argument of type ‘int’, but argument 7 has type ‘size_t’ [-Wformat=]
     FI_INFO(&psmx2_prov, FI_LOG_CORE,
     ^
prov/psm2/src/psmx2_init.c:377:5: warning: format ‘%d’ expects argument of type ‘int’, but argument 7 has type ‘size_t’ [-Wformat=]
     FI_INFO(&psmx2_prov, FI_LOG_CORE,
     ^
prov/psm2/src/psmx2_init.c:387:4: warning: format ‘%llx’ expects argument of type ‘long long unsigned int’, but argument 7 has type ‘uint64_t’ [-Wformat=]
    FI_INFO(&psmx2_prov, FI_LOG_CORE,
    ^
prov/psm2/src/psmx2_init.c:396:5: warning: format ‘%llx’ expects argument of type ‘long long unsigned int’, but argument 7 has type ‘uint64_t’ [-Wformat=]
     FI_INFO(&psmx2_prov, FI_LOG_CORE,
     ^
prov/psm2/src/psmx2_init.c:404:5: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 8 has type ‘int’ [-Wformat=]
     FI_INFO(&psmx2_prov, FI_LOG_CORE,
     ^
prov/psm2/src/psmx2_init.c:416:4: warning: format ‘%llx’ expects argument of type ‘long long unsigned int’, but argument 7 has type ‘uint64_t’ [-Wformat=]
    FI_INFO(&psmx2_prov, FI_LOG_CORE,
    ^
prov/psm2/src/psmx2_init.c:424:5: warning: format ‘%llx’ expects argument of type ‘long long unsigned int’, but argument 7 has type ‘uint64_t’ [-Wformat=]
     FI_INFO(&psmx2_prov, FI_LOG_CORE,
     ^
prov/psm2/src/psmx2_init.c:530:5: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 8 has type ‘long long unsigned int’ [-Wformat=]
     FI_INFO(&psmx2_prov, FI_LOG_CORE,
     ^
prov/psm2/src/psmx2_init.c:543:5: warning: format ‘%lx’ expects argument of type ‘long unsigned int’, but argument 8 has type ‘int’ [-Wformat=]
     FI_INFO(&psmx2_prov, FI_LOG_CORE,
     ^
prov/psm2/src/psmx2_init.c:552:5: warning: format ‘%lx’ expects argument of type ‘long unsigned int’, but argument 8 has type ‘int’ [-Wformat=]
     FI_INFO(&psmx2_prov, FI_LOG_CORE,
     ^
prov/psm2/src/psmx2_init.c:568:5: warning: format ‘%d’ expects argument of type ‘int’, but argument 8 has type ‘long unsigned int’ [-Wformat=]
     FI_INFO(&psmx2_prov, FI_LOG_CORE,
     ^
prov/psm2/src/psmx2_init.c:587:5: warning: format ‘%lx’ expects argument of type ‘long unsigned int’, but argument 8 has type ‘int’ [-Wformat=]
     FI_INFO(&psmx2_prov, FI_LOG_CORE,
     ^
prov/psm2/src/psmx2_init.c:596:5: warning: format ‘%lx’ expects argument of type ‘long unsigned int’, but argument 8 has type ‘int’ [-Wformat=]
     FI_INFO(&psmx2_prov, FI_LOG_CORE,

```

### PR DESCRIPTION
**Pull request by gladkovdmitry17**
The mismatch between types was fixed as follows:
- Change to use `fi_tostr` for the caps, modes, [msg|comp]_orders fields
- Replace the incorrect format specifiers to the proper ones (e.x. `%d` -> `%PRIu64` when type of the variable is `uint64_t`)

Fixes #3388 

Signed-off-by: Dmitry Gladkov <dmitry.gladkov@intel.com>

### CODE REVIEW

**Comment by gladkovdmitry17** [comment]
@j-xiong Could you take a look, please?

File: prov/psm2/src/psmx2_am.c [hunk 1]
```diff
@@ -291,7 +291,8 @@ int psmx2_am_init(struct psmx2_trx_ctxt *trx_ctxt)
 			psmx2_unlock(&psmx2_am_global.lock, 1);
 			FI_WARN(&psmx2_prov, FI_LOG_CORE,
 				"number of PSM2 endpoints exceed limit %d.\n"
-				"at indecies %d, %d\n", PSMX2_AM_MAX_TRX_CTXT);
+				"at indecies %d\n", PSMX2_AM_MAX_TRX_CTXT,
+				psmx2_am_global.cnt);
```
Comment (j-xiong) [inline prov/psm2/src/psmx2_am.c]: We should just remove "at indecies %d, %d\n" here.

Comment (gladkovdmitry17) [reply prov/psm2/src/psmx2_am.c]: Thanks!
Fixed
