### PR TITLE
prov/shm: fix shm mapping/addressing issues

### LINKED ISSUE #6015: Segmentation Fault issue when running fabtests using shm protocol with FI_DELIVERY_COMPLETE enabled
Hi,

I am hitting Segmentation Fault issue using shm protocol with FI_DELIVERY_COMPLETE enabled.

I changed the recv_cancel.c in fabtests to set FI_DELIVERY_COMPLETE:
```
--- a/fabtests/functional/recv_cancel.c
+++ b/fabtests/functional/recv_cancel.c
@@ -216,7 +216,7 @@ int main(int argc, char **argv)
        hints->caps = FI_TAGGED;
        hints->mode = FI_CONTEXT;
        hints->domain_attr->mr_mode = opts.mr_mode;
-
+       hints->tx_attr->op_flags = FI_DELIVERY_COMPLETE;
        ret = run_test();
 
        ft_free_res();
```
Then when I run the following command, I got seg fault on the server side:

Server Command:
```
/home/ec2-user/libfabric/fabtests/install/bin/fi_recv_cancel -e rdm -V -p "shm"  -s 127.0.0.1
```

Client Command:
```
/home/ec2-user/libfabric/fabtests/install/bin/fi_recv_cancel -e rdm -V -p "shm"  -s 127.0.0.1 127.0.0.1
```

This test has been run on Amazon Linux 2, with rdma-core v27.0 and libfabric master.

The stack trace on the server side is as follows:
```
#0  0x00007ffff7b4e11f in smr_progress_iov (cmd=0x7fffb527d098, iov=0x7ffff7fc2058, iov_count=1, 
    total_len=0x7fffffffdbd0, ep=0x61f7b0, err=0) at prov/shm/src/smr_progress.c:264
#1  0x00007ffff7b4f31e in smr_progress_msg_common (ep=0x61f7b0, cmd=0x7fffb527d098, entry=0x7ffff7fc2028)
    at prov/shm/src/smr_progress.c:555
#2  0x00007ffff7b4f7fa in smr_progress_cmd_msg (ep=0x61f7b0, cmd=0x7fffb527d098)
    at prov/shm/src/smr_progress.c:639
#3  0x00007ffff7b50521 in smr_progress_cmd (ep=0x61f7b0) at prov/shm/src/smr_progress.c:816
#4  0x00007ffff7b50a08 in smr_ep_progress (util_ep=0x61f7b0) at prov/shm/src/smr_progress.c:905
#5  0x00007ffff7a8cd74 in ofi_cq_progress (cq=0x61f5a0) at prov/util/src/util_cq.c:599
#6  0x00007ffff7a8bfeb in ofi_cq_readfrom (cq_fid=0x61f5a0, buf=0x7fffffffde30, count=1, src_addr=0x0)
    at prov/util/src/util_cq.c:247
#7  0x00007ffff7a8c2db in ofi_cq_read (cq_fid=0x61f5a0, buf=0x7fffffffde30, count=1)
    at prov/util/src/util_cq.c:314
#8  0x0000000000402280 in fi_cq_read (cq=0x61f5a0, buf=0x7fffffffde30, count=1)
    at /home/ec2-user/libfabric/install/include/rdma/fi_eq.h:394
#9  0x000000000040a238 in ft_spin_for_comp (cq=0x61f5a0, cur=0x613860 <rx_cq_cntr>, total=1, timeout=-1)
    at common/shared.c:2083
#10 0x000000000040a64e in ft_get_cq_comp (cq=0x61f5a0, cur=0x613860 <rx_cq_cntr>, total=1, timeout=-1)
    at common/shared.c:2175
#11 0x000000000040a91a in ft_get_rx_comp (total=1) at common/shared.c:2255
#12 0x000000000040a030 in ft_rx (ep=0x61f7b0, size=256) at common/shared.c:2024
#13 0x000000000040628e in ft_init_av_dst_addr (av_ptr=0x61f660, ep_ptr=0x61f7b0, 
    remote_addr=0x613200 <remote_fi_addr>) at common/shared.c:1212
#14 0x0000000000405f49 in ft_init_av () at common/shared.c:1145
#15 0x0000000000405571 in ft_init_fabric () at common/shared.c:984
#16 0x0000000000401e3f in run_test () at functional/recv_cancel.c:175
#17 0x0000000000402062 in main (argc=8, argv=0x7fffffffe108) at functional/recv_cancel.c:220
```

### PR DESCRIPTION
**Pull request by aingerson**
Fixes #6015

### CODE REVIEW

**Comment by aingerson** [comment]
Still checking/cleaning various things, but opening up for comment/feedback

**Comment by aingerson** [comment]
@aolia-0303 Could you take a look and see if this fixes the issue you were seeing in #6015 ?

File: prov/util/src/util_shm.c [hunk 1]
```diff
@@ -402,6 +420,9 @@ void smr_map_del(struct smr_map *map, int id)
 	if (!entry)
 		munmap(map->peers[id].region, map->peers[id].region->total_size);
 
+	(void) ofi_rbmap_find_delete(&map->rbmap,
+				     (void *) map->peers[id].peer.name);
```
Comment (shefty) [inline prov/util/src/util_shm.c:457]: Do you need map->lock here?

File: prov/shm/src/smr_ep.c [hunk 2]
```diff
@@ -179,16 +179,63 @@ static struct fi_ops_ep smr_ep_ops = {
...
+		goto out;
+
+	cmd = ofi_cirque_tail(smr_cmd_queue(peer_smr));
+	smr_generic_ctrl_format(cmd, id, ofi_ctrl_connreq);
+
+	tx_buf = smr_freestack_pop(smr_inject_pool(peer_smr));
+	cmd->msg.hdr.src_data = smr_get_offset(peer_smr, tx_buf);
+
+	cmd->msg.hdr.size = strlen(smr_name(ep->region)) + 1;
+	memcpy(tx_buf->data, smr_name(ep->region), cmd->msg.hdr.size);
```
Comment (shefty) [inline prov/shm/src/smr_ep.c:209]: Is the name not stored in the shared memory region?

File: prov/shm/src/smr_progress.c [hunk 3]
```diff
@@ -842,32 +877,37 @@ static void smr_progress_cmd(struct smr_ep *ep)
...
-			ret = smr_progress_cmd_atomic(ep, cmd);
-			break;
-		default:
-			FI_WARN(&smr_prov, FI_LOG_EP_CTRL,
-				"unidentified operation type\n");
-			ret = -FI_EINVAL;
+		if (cmd->msg.hdr.op_flags & SMR_CTRL_MSG) {
+			assert(cmd->msg.hdr.op == ofi_ctrl_connreq);
+			smr_progress_connreq(ep, cmd);
+		} else {
```
Comment (shefty) [inline prov/shm/src/smr_progress.c:883]: Why can't the op be added to the switch statement, versus checking a flag?  The op_flags should depend on the opcode, not the opcode dependent on a flag.

File: prov/util/src/util_shm.c (hunk 1 above)
Comment (aingerson) [reply prov/util/src/util_shm.c:457]: smr_map_del and smr_map_add assume that the map->lock is acquired already. There's one place it's not so I'll fix that an add a comment to say it should be held.

File: prov/shm/src/smr_ep.c (hunk 2 above)
Comment (aingerson) [reply prov/shm/src/smr_ep.c:209]: It is, but this is to send the name of the sender if the target doesn't have it mapped yet so it needs the remote name in order to map it.

File: prov/shm/src/smr_progress.c (hunk 3 above)
Comment (aingerson) [reply prov/shm/src/smr_progress.c:883]: Because there are 2 different sets of ops - ofi_ctrl_*
https://github.com/ofiwg/libfabric/blob/master/include/ofi_proto.h#L52
and ofi_op_*
https://github.com/ofiwg/libfabric/blob/master/include/ofi_proto.h#L121
The op_flags are kind of a misnomer - they really should be just flags or cmd_flags, not op_flags

Comment (shefty) [reply prov/shm/src/smr_progress.c:883]: hdr.op *should* be the field that decides how to interpret all other fields.  Having the 5th bit of a flag field be the determining factor is confusing.

I think the best option is to add a base_ctrl_op = ofi_op_max, and have all ctrl ops start there.

**Comment by aolia-0303** [comment]
@aingerson I would not hit the segfault issue in  https://github.com/ofiwg/libfabric/issues/6015.

However, the client side will hang. The backtrace is as follows:

```
#0  0x00007fe57e811543 in pthread_spin_lock () from /lib64/libpthread.so.0
#1  0x00007fe57f580f76 in smr_ep_progress () from /fsx/libfabric/install/lib/libfabric.so.1
#2  0x00007fe57f50265d in ofi_cq_progress () from /fsx/libfabric/install/lib/libfabric.so.1
#3  0x00007fe57f50196e in ofi_cq_readfrom () from /fsx/libfabric/install/lib/libfabric.so.1
#4  0x00000000004022e0 in fi_cq_read (cq=0x1516170, buf=0x7ffd38c322e0, count=1)
    at /fsx/libfabric/install/include/rdma/fi_eq.h:394
#5  0x000000000040a5dd in ft_spin_for_comp (cq=0x1516170, cur=0x613d00 <tx_cq_cntr>, total=3, 
    timeout=-1) at common/shared.c:2152
#6  0x000000000040a9f3 in ft_get_cq_comp (cq=0x1516170, cur=0x613d00 <tx_cq_cntr>, total=3, 
    timeout=-1) at common/shared.c:2244
#7  0x000000000040ad77 in ft_get_tx_comp (total=3) at common/shared.c:2339
#8  0x0000000000401922 in recv_cancel_client () at functional/recv_cancel.c:65
#9  0x0000000000401ebe in run_test () at functional/recv_cancel.c:180
#10 0x00000000004020c2 in main (argc=9, argv=0x7ffd38c32508) at functional/recv_cancel.c:220
```

File: prov/shm/src/smr_progress.c (hunk 3 above)
Comment (aingerson) [reply prov/shm/src/smr_progress.c:883]: You mean in ofi_proto.h? Wouldn't that change all the ofi_ctrl_* values and create versioning issues?

**Comment by aingerson** [comment]
> @aingerson I would not hit the segfault issue in #6015.
> 
> However, the client side will hang. The backtrace is as follows:
> 
> ```
> #0  0x00007fe57e811543 in pthread_spin_lock () from /lib64/libpthread.so.0
> #1  0x00007fe57f580f76 in smr_ep_progress () from /fsx/libfabric/install/lib/libfabric.so.1
> #2  0x00007fe57f50265d in ofi_cq_progress () from /fsx/libfabric/install/lib/libfabric.so.1
> #3  0x00007fe57f50196e in ofi_cq_readfrom () from /fsx/libfabric/install/lib/libfabric.so.1
> #4  0x00000000004022e0 in fi_cq_read (cq=0x1516170, buf=0x7ffd38c322e0, count=1)
>     at /fsx/libfabric/install/include/rdma/fi_eq.h:394
> #5  0x000000000040a5dd in ft_spin_for_comp (cq=0x1516170, cur=0x613d00 <tx_cq_cntr>, total=3, 
>     timeout=-1) at common/shared.c:2152
> #6  0x000000000040a9f3 in ft_get_cq_comp (cq=0x1516170, cur=0x613d00 <tx_cq_cntr>, total=3, 
>     timeout=-1) at common/shared.c:2244
> #7  0x000000000040ad77 in ft_get_tx_comp (total=3) at common/shared.c:2339
> #8  0x0000000000401922 in recv_cancel_client () at functional/recv_cancel.c:65
> #9  0x0000000000401ebe in run_test () at functional/recv_cancel.c:180
> #10 0x00000000004020c2 in main (argc=9, argv=0x7ffd38c32508) at functional/recv_cancel.c:220
> ```

I'll look into it. Thanks for checking!

File: prov/shm/src/smr_progress.c (hunk 3 above)
Comment (shefty) [reply prov/shm/src/smr_progress.c:883]: I'm suggesting that the shm provider define a single op space.  And to limit the changes, that the new ctrl ops use an offset of + ofi_op_max.  IOW, the code here would be:
```
switch (cmd->msg.hdr.op) {
case ofi_op_msg:
case ofi_op_tagged:
    ...
case ofi_op_atomic_compare:
    ...
case ofi_op_max + ofi_ctrl_connreq:
    smr_progress_connreq(ep, cmd)
default:
    FI_WARN(...)
}
```
You can use ofi_op_max directly, or define a new value (base_ctrl_op) for where the ctrl ops should start.  The latter would avoid problems if ofi_op_max is ever changed and could reserve some values for new non-ctrl ops.

Comment (shefty) [reply prov/shm/src/smr_progress.c:883]: Btw, if you look at the comment in fi_proto.h
```
 * Intent is that RX can use opcode + control as indices into a function
 * pointer array for message processing (after validating values).
```
This is describing having the basic command opcodes be offset by some number of values reserved for control opcodes.  But since shm didn't have control opcodes before, I would simply reverse the order and place the control opcodes after the basic command opcodes.

The shm protocol version doesn't need to change in this case.  If there's a mismatch, the receiver will simply get a unknown opcode and discard it.

Comment (aingerson) [reply prov/shm/src/smr_progress.c:883]: Brilliant - thank you

**Comment by aingerson** [comment]
Updated with fixes to comments.
Looking into the recv_cancel hang I'm not sure if this is a shm bug but rather a misuse of DELIVERY_COMPLETE in the recv_cancel test. But it could be that I'm misunderstanding either fi_cancel or the completion semantics. It seems to me that delivery complete can't be used when posting a message for a canceled receive buffer since it might never be matched/received. 
@shefty Can you clarify what the behavior should be in this case?

**Comment by shefty** [comment]
I read over the recv_cancel test.  The results are not deterministic.  It looks like the idea is that the message with the CANCEL tag should not be matched.  However, there's no way to know what that means to the message.  For example, a small message may be received by the peer and queued in an expected list.  In this case, a completion will be generated.  While a large message may never complete prior to the test ending.

The STANDARD tag message should always match.

I think the fix here is, after the STANDARD tag message is received, the CANCEL tag message should be re-posted.  Both the sender and receiver should wait until they get a valid completion related to the CANCEL message.  The client/server sync at that point then exit.

**Comment by aingerson** [comment]
> I read over the recv_cancel test. The results are not deterministic. It looks like the idea is that the message with the CANCEL tag should not be matched. However, there's no way to know what that means to the message. For example, a small message may be received by the peer and queued in an expected list. In this case, a completion will be generated. While a large message may never complete prior to the test ending.
> 
> The STANDARD tag message should always match.
> 
> I think the fix here is, after the STANDARD tag message is received, the CANCEL tag message should be re-posted. Both the sender and receiver should wait until they get a valid completion related to the CANCEL message. The client/server sync at that point then exit.

That makes more sense to me. I've updated this in PR #6230 - this new shm addressing works with the changes in that PR with delivery complete. (It also fixes long lines - you're welcome @shefty )

**Comment by aingerson** [comment]
Updated with rebase and fix for CI failure

**Comment by shefty** [comment]
bot:aws:retest

**Review by shefty — APPROVED** [review]
