### PR TITLE
prov/sockets: Fixed fi_getinfo to user provided capabilities from hints

### LINKED ISSUE #1202: sockets provider reports extra capabilities
Seen when running fi_rdm_cntr_pingpong:

(gdb) print /x hints->caps
$5 = 0x2

(gdb) print /x fi->caps
$4 = 0xf00000000353f1e

The application only requests FI_MSG capability, but additional primary caps are defined.  This is restricted by the API definition as it opens the app's security.  For instance, FI_RMA cannot be enabled unless the app explicitly requests it.  See fi_getinfo.3 for details on which caps are listed as primary, versus secondary.

### PR DESCRIPTION
**Pull request by shantonu**
- Fixed code to use capabilities from hints->caps, hints->tx_attr->caps and hints->rx_attr->caps when specified by the user. 
- Factored the definition of SOCK_EP_XXXX_CAP into SOCK_EP_XXXX_PRI_CAP and SOCK_EP_XXXX_SEC_CAP
- Removed unused FI_MORE cap from the definition

Resolves #1202

@shefty, @jithinjosepkl can you please review? Tested with runfabtests.

Signed-off-by: Shantonu Hossain <shantonu.hossain@intel.com>

### CODE REVIEW

File: prov/sockets/src/sock_ep_dgram.c [hunk 1]
```diff
@@ -215,14 +215,21 @@ int sock_dgram_fi_info(void *src_addr, void *dest_addr, struct fi_info *hints,
 
 	if (hints && hints->rx_attr) {
 		(*info)->rx_attr->op_flags |= hints->rx_attr->op_flags;
+		if(hints->rx_attr->caps)
+			(*info)->rx_attr->caps = hints->rx_attr->caps;
```
Comment (shefty) [inline prov/sockets/src/sock_ep_dgram.c]: Please leave a space between the if and the open paren: if (...)

Only the primary caps cannot be added.  It is okay to add secondary caps.  I think the defines for SOCK_EP_XX_CAP may need to be broken into PRI_CAP and SEC_CAP

**Comment by jithinjosepkl** [comment]
Looks good to me.

Minor nit: We could define something like SOCK_EP_RDM_CAP as  (SOCK_EP_RDM_PRI_CAP | SOCK_EP_RDM_SEC_CAP) and use this in all the capability checks.

Also, I think we should check for the allowed capabilities while issuing operations (only in debug mode). That could go as a separate commit/PR.

**Comment by shantonu** [comment]
Should be good to merge now. I'll create a separate PR with the check.
