### PR TITLE
prov/verbs: Serialize an access to the EP/SRQ's Work Requests pool and list

### LINKED ISSUE #3389: fi_ibv_poll_cq: Assertion `wre && (wre->ep || wre->srq)' failed.
While running:

    MPIR_CVAR_OFI_USE_PROVIDER="verbs;ofi_rxm" srun -N 32 -n 256 mpi/collective/osu_alltoall -m 8

I got the assertion

  osu_alltoall: prov/verbs/src/verbs_cq.c:398: fi_ibv_poll_cq: Assertion `wre && (wre->ep || wre->srq)' failed.

gdb info:

    (gdb) bt
    #0  0x00007ffff709b5f7 in raise () from /lib64/libc.so.6
    #1  0x00007ffff709cce8 in abort () from /lib64/libc.so.6
    #2  0x00007ffff7094566 in __assert_fail_base () from /lib64/libc.so.6
    #3  0x00007ffff7094612 in __assert_fail () from /lib64/libc.so.6
    #4  0x00007ffff6de30d2 in fi_ibv_poll_cq (cq=0x6f12e0, wc=0x7fffffffd030) at prov/verbs/src/verbs_cq.c:398
    #5  0x00007ffff6de32b5 in fi_ibv_cq_read (cq_fid=0x6f12e0, buf=0x7fffffffd1b0, count=1) at prov/verbs/src/verbs_cq.c:455
    #6  0x00007ffff6e1cce6 in fi_cq_read (cq=0x6f12e0, buf=0x7fffffffd1b0, count=1) at ./include/rdma/fi_eq.h:385
    #7  0x00007ffff6e1ef52 in rxm_cq_read (msg_cq=0x6f12e0, comp=0x7fffffffd1b0) at prov/rxm/src/rxm_cq.c:536
    #8  0x00007ffff6e1f2cc in rxm_cq_progress (rxm_ep=0x6f0ec0) at prov/rxm/src/rxm_cq.c:585
    #9  0x00007ffff6e1c8e9 in rxm_ep_progress (util_ep=0x6f0ec0) at prov/rxm/src/rxm_ep.c:1331
    #10 0x00007ffff6da98d3 in ofi_cq_progress (cq=0x70c1f0) at prov/util/src/util_cq.c:479
    #11 0x00007ffff6da8cf5 in ofi_cq_read (cq_fid=0x70c1f0, buf=0x7fffffffd320, count=1) at prov/util/src/util_cq.c:186
    #12 0x00007ffff75d6057 in MPID_nem_ofi_poll () from /home/users/fzago/install/lib/libmpi.so.0
    #13 0x00007ffff75be1fa in MPIDI_CH3I_Progress () from /home/users/fzago/install/lib/libmpi.so.0
    #14 0x00007ffff755fe8d in MPIDI_CH3U_VC_WaitForClose () from /home/users/fzago/install/lib/libmpi.so.0
    #15 0x00007ffff75a6e45 in MPID_Finalize () from /home/users/fzago/install/lib/libmpi.so.0
    #16 0x00007ffff74dee7c in PMPI_Finalize () from /home/users/fzago/install/lib/libmpi.so.0
    #17 0x000000000040126d in main (argc=3, argv=0x7fffffffd678) at osu_alltoall.c:125
    (gdb) 
    #4  0x00007ffff6de30d2 in fi_ibv_poll_cq (cq=0x6f12e0, wc=0x7fffffffd030) at prov/verbs/src/verbs_cq.c:398
    398			assert(wre && (wre->ep || wre->srq));
    (gdb) p *wre
    $4 = {entry = {next = 0x72c6d0, prev = 0x6f0308}, context = 0x7ffff2239740, ep = 0x0, srq = 0x0, wr = {type = IBV_RECV_WR, {swr = {wr_id = 7518832, 
        next = 0x0, sg_list = 0x7fffffffcdd0, num_sge = 1, opcode = IBV_WR_RDMA_WRITE, send_flags = 0, imm_data = 0, wr = {rdma = {remote_addr = 0, 
            rkey = 0}, atomic = {remote_addr = 0, compare_add = 0, swap = 0, rkey = 0}, ud = {ah = 0x0, remote_qpn = 0, remote_qkey = 0}}, {qp_type = {
            xrc = {remote_srqn = 0}}, xrc_remote_srq_num = 0}}, rwr = {wr_id = 7518832, next = 0x0, sg_list = 0x7fffffffcdd0, num_sge = 1}}}}

### PR DESCRIPTION
**Pull request by gladkovdmitry17**
The intent of the PR is to fix a not serialized access to the EP/SRQ's Work Request pool and list.

Fixes #3389 (Multi-threaded usage)

Signed-off-by: Dmitry Gladkov <dmitry.gladkov@intel.com>

### CODE REVIEW

**Comment by gladkovdmitry17** [comment]
@plebioda Could you test this solution, please? It is straightforward changes and should be merged anyway to protect the WR pool and list, but we need to be sure that this fixes the discovered problem in the Multi-threaded case. Thanks in advance!

File: prov/verbs/src/fi_verbs.c [hunk 1]
```diff
@@ -319,10 +319,16 @@ fi_ibv_send(struct fi_ibv_msg_ep *ep, struct ibv_send_wr *wr, void *context)
 
 	if (ep->scq) {
 		if (wr->send_flags & IBV_SEND_SIGNALED) {
+			fastlock_init(&ep->wre_lock);
```
Comment (plebioda) [inline prov/verbs/src/fi_verbs.c]: fastlock_acquire

Comment (gladkovdmitry17) [reply prov/verbs/src/fi_verbs.c]: @plebioda Thanks. Looks strange why it doesn't fail. My tests is ok

**Comment by gladkovdmitry17** [comment]
@a-ilango Could you take a look, please?

File: prov/verbs/src/fi_verbs.c [hunk 2]
```diff
@@ -319,10 +319,16 @@ fi_ibv_send(struct fi_ibv_msg_ep *ep, struct ibv_send_wr *wr, void *context)
...
+			fastlock_acquire(&ep->wre_lock);
 			wre = util_buf_alloc(ep->wre_pool);
-			if (OFI_UNLIKELY(!wre))
+			if (OFI_UNLIKELY(!wre)) {
+				fastlock_release(&ep->wre_lock);
 				return -FI_EAGAIN;
+			}
 			memset(wre, 0, sizeof(*wre));
+			dlist_insert_tail(&wre->entry, &ep->wre_list);
+			fastlock_release(&ep->wre_lock);
```
Comment (a-ilango) [inline prov/verbs/src/fi_verbs.c]: It seems on send error FI_IBV_RELEASE_WRE doesn't lock when releasing the entry.

Comment (gladkovdmitry17) [reply prov/verbs/src/fi_verbs.c]: Good catch. Has been updated according your comment

File: prov/verbs/src/fi_verbs.h [hunk 3]
```diff
@@ -141,11 +141,13 @@
...
 
-#define FI_IBV_RELEASE_WRE(wre_pool, wre)		\
+#define FI_IBV_RELEASE_WRE(ep, wre)			\
 ({							\
 	if (wre) {					\
+		fastlock_acquire(&ep->wre_lock);	\
 		dlist_remove(&wre->entry);		\
-		util_buf_release(wre_pool, wre);	\
+		util_buf_release(ep->wre_pool, wre);	\
+		fastlock_acquire(&ep->wre_lock);	\
```
Comment (a-ilango) [inline prov/verbs/src/fi_verbs.h]: typo: this should be fastlock_release

**Comment by gladkovdmitry17** [comment]
The fabtests report with latest changes:

```
$ ./runfabtests.sh -g 192.168.65.1 -s 192.168.65.1 -c 192.168.65.1 verbs
# Test                                                                    Result
# ------------------------------------------------------------------------------
fi_getinfo_test -p "verbs":                                                 Pass
fi_av_test -g 192.168.65.1 -n 1 -s 192.168.65.1 -p "verbs":                 Pass
fi_dom_test -n 2 -p "verbs":                                                Pass
fi_eq_test -p "verbs":                                                      Pass
fi_cq_test -p "verbs":                                                      Pass
fi_mr_test -p "verbs":                                                      Pass
fi_cntr_test -p "verbs":                                                    Pass
fi_dgram g00n13s -p "verbs":                                                Pass
fi_rdm g00n13s -p "verbs":                                                  Pass
fi_msg g00n13s -p "verbs":                                                  Pass
fi_cm_data -p "verbs":                                                      Pass
fi_cq_data -p "verbs":                                                      Pass
fi_dgram -p "verbs":                                                        Pass
fi_dgram_waitset -p "verbs":                                                Fail
fi_msg -p "verbs":                                                          Pass
fi_msg_epoll -p "verbs":                                                    Pass
fi_msg_sockets -p "verbs":                                                  Pass
fi_poll -t queue -p "verbs":                                              Notrun
fi_poll -t counter -p "verbs":                                            Notrun
fi_rdm -p "verbs":                                                          Pass
fi_rdm_rma_simple -p "verbs":                                             Notrun
fi_rdm_rma_trigger -p "verbs":                                            Notrun
fi_shared_ctx -p "verbs":                                                 Notrun
fi_shared_ctx --no-tx-shared-ctx -p "verbs":                              Notrun
fi_shared_ctx --no-rx-shared-ctx -p "verbs":                              Notrun
fi_shared_ctx -e msg -p "verbs":                                          Notrun
fi_shared_ctx -e msg --no-tx-shared-ctx -p "verbs":                         Pass
fi_shared_ctx -e msg --no-rx-shared-ctx -p "verbs":                       Notrun
fi_shared_ctx -e dgram -p "verbs":                                        Notrun
fi_shared_ctx -e dgram --no-tx-shared-ctx -p "verbs":                       Fail
fi_shared_ctx -e dgram --no-rx-shared-ctx -p "verbs":                     Notrun
fi_rdm_tagged_peek -p "verbs":                                              Pass
fi_scalable_ep -p "verbs":                                                Notrun
fi_cmatose -p "verbs":                                                      Pass
fi_rdm_shared_av -p "verbs":                                              Notrun
fi_multi_mr -e msg -V -p "verbs":                                         Notrun
fi_multi_mr -e rdm -V -p "verbs":                                         Notrun
fi_recv_cancel -e rdm -V -p "verbs":                                        Pass
fi_unexpected_msg -e msg -i 10 -p "verbs":                                Notrun
fi_unexpected_msg -e rdm -i 10 -p "verbs":                                  Pass
fi_unexpected_msg -e dgram -i 10 -p "verbs":                              Notrun
fi_unexpected_msg -e msg -S -i 10 -p "verbs":                             Notrun
fi_unexpected_msg -e rdm -S -i 10 -p "verbs":                               Pass
fi_unexpected_msg -e dgram -S -i 10 -p "verbs":                           Notrun
fi_inj_complete -e msg -p "verbs":                                        Notrun
fi_inj_complete -e rdm -p "verbs":                                          Pass
fi_inj_complete -e dgram -p "verbs":                                      Notrun
fi_inj_complete -e msg -SR -p "verbs":                                    Notrun
fi_inj_complete -e rdm -SR -p "verbs":                                      Pass
fi_inj_complete -e dgram -SR -p "verbs":                                  Notrun
fi_msg_pingpong -I 5 -p "verbs":                                            Pass
fi_msg_pingpong -I 5 -v -p "verbs":                                         Pass
fi_msg_bw -I 5 -p "verbs":                                                  Pass
fi_msg_bw -I 5 -v -p "verbs":                                               Pass
fi_rma_bw -e msg -o write -I 5 -p "verbs":                                  Pass
fi_rma_bw -e msg -o read -I 5 -p "verbs":                                   Pass
fi_rma_bw -e msg -o writedata -I 5 -p "verbs":                              Pass
fi_rma_bw -e rdm -o write -I 5 -p "verbs":                                  Pass
fi_rma_bw -e rdm -o read -I 5 -p "verbs":                                   Pass
fi_rma_bw -e rdm -o writedata -I 5 -p "verbs":                              Fail
fi_msg_rma -o write -I 5 -p "verbs":                                        Pass
fi_msg_rma -o read -I 5 -p "verbs":                                         Pass
fi_msg_rma -o writedata -I 5 -p "verbs":                                    Pass
fi_msg_stream -I 5 -p "verbs":                                              Pass
fi_rdm_atomic -I 5 -o all -p "verbs":                                     Notrun
fi_rdm_cntr_pingpong -I 5 -p "verbs":                                     Notrun
fi_rdm_multi_recv -I 5 -p "verbs":                                          Pass
fi_rdm_pingpong -I 5 -p "verbs":                                            Pass
fi_rdm_pingpong -I 5 -v -p "verbs":                                         Pass
fi_rdm_rma -o write -I 5 -p "verbs":                                        Pass
fi_rdm_rma -o read -I 5 -p "verbs":                                         Pass
fi_rdm_rma -o writedata -I 5 -p "verbs":                                  Notrun
fi_rdm_tagged_pingpong -I 5 -p "verbs":                                     Pass
fi_rdm_tagged_pingpong -I 5 -v -p "verbs":                                  Pass
fi_rdm_tagged_bw -I 5 -p "verbs":                                           Pass
fi_rdm_tagged_bw -I 5 -v -p "verbs":                                        Pass
fi_dgram_pingpong -I 5 -p "verbs":                                          Pass
fi_rc_pingpong -n 5 -p "verbs":                                             Pass
fi_rc_pingpong -n 5 -e -p "verbs":                                          Pass
# ------------------------------------------------------------------------------
# Total Pass                                                50
# Total Notrun/Excluded                                     26
# Total Fail                                                 3
# Percentage of Pass                                        94
# ------------------------------------------------------------------------------
```

File: prov/verbs/src/fi_verbs.h (hunk 3 above)
Comment (gladkovdmitry17) [reply prov/verbs/src/fi_verbs.h]: @a-ilango thanks, has been updated
