### PR TITLE
core: Increase the size of the indexer to 1M

### LINKED ISSUE #5429: core: Indexer limit of 16 bits causes applications to fail above 64K ranks.
```
# export FI_VERBS_PREFER_XRC=1
--
# srun -N 837 --ntasks-per-node=128 --cpu_bind=rank ./osu_barrier
...
# OSU MPI Barrier Latency Test v5.4.1
# Avg Latency(us)
MPICH ERROR [Rank 92032] [job id 19.3] [Thu Nov  7 08:55:17 2019] [unknown] [nid000866] - Abort(245990799) (rank 92032 in comm 0): Fatal error in PMPI_Barrier: Other MPI error, error stack:
...
MPIDI_OFI_handle_cq_error(902).......: OFI poll failed (ofi_events.h:904:MPIDI_OFI_handle_cq_error:Unspecified error
```

The error reported through warning indicates that the handle->key does not match the key, when performing a lookup, followed directly by a CQ error generated by the provider.

### PR DESCRIPTION
**Pull request by jswaro**
When running more than 64K application ranks, the indexer
hits a hard limit as defined in the header file. This commit
increases the number of bits in the indexer from 16 to 22,
increasing the size from (64K - 1) entries, to (1M - 1) entries.

Signed-off-by: James Swaro <jswaro@cray.com>

Fixes #5429

### CODE REVIEW

File: include/ofi_indexer.h [hunk 1]
```diff
@@ -60,7 +60,7 @@ struct ofi_idx_entry {
 	int   next;
 };
 
-#define OFI_IDX_INDEX_BITS 16
+#define OFI_IDX_INDEX_BITS 20
```
Comment (shefty) [inline include/ofi_indexer.h]: This will increase the default size of the indexer from an array of 64 pointers to an array of 1024 pointers.  Are we okay with that increase?  Looking at the indexer use in the code, this should be okay.

**Comment by shefty** [comment]
AppVeyor error was timeout reaching github.  I restarted, but the failure wasn't related.

File: include/ofi_indexer.h (hunk 1 above)
Comment (jswaro) [reply include/ofi_indexer.h]: I'm ok with it. The indexer seems to add memory as necessary, so in the worst case scenario (unused space), it adds an additional 7680 bytes per process as overhead, regardless of usage. It also allows the indexer to grow (maximum usage) from 530K per process to 8.2MB per process

Comment (jswaro) [reply include/ofi_indexer.h]: With 128 processes per node:

10% filled (before): 6.8 MB total, ~0.05MB per process
10% filled (after): 108MB, ~0.8MB per process
100% filled (before): 67 MB, ~.5MB per process. 
100% filled (after): 1.07GB, ~8.2 MB per process

Comment (shefty) [reply include/ofi_indexer.h]: Whoa - something doesn't look right here.  This increase should only add a few KB per node.

Comment (shefty) [reply include/ofi_indexer.h]: err, per process

Comment (jswaro) [reply include/ofi_indexer.h]: Right... to the base memory cost. If the indexer were filled to the maximum, then it would consume more because there is more space that could be allocated. 

To the base memory cost (the cost of the 64 or 1024 array locations), it would only be a few KB per process.

Comment (shefty) [reply include/ofi_indexer.h]: Okay, I think the issue is that the comparisons above are misleading.  10% filled after the change is significantly more entries added to the index than 10% before the change.  It would be better to show the consumption for X entries total, which I would expect to be the same for any reasonable value of X.

Comment (jswaro) [reply include/ofi_indexer.h]: I was actually trying to show it a little better... apples to apples. 

working on it

Comment (jswaro) [reply include/ofi_indexer.h]: With 128 processes per node:
6.4K entries (10% of indexer) [before]: 6.8 MB total, 52KB per process
6.4K entries (0.625 % of indexer) [after]: 7.8MB, 60KB per process

64K entries (100% of original) filled (before): 67 MB, 524K per process. 
64K entries (6.25% of indexer) filled (after): 68.1MB, 532K per process

max entries (before): 67 MB, ~.5MB per process. 
max entries (after): 1.07GB, 8MB per process

Comment (jswaro) [reply include/ofi_indexer.h]: Agreed though. Initial numbers were a misleading :) Sorry about that.

Comment (shefty) [reply include/ofi_indexer.h]: Hmm... an extra MB per process with this change is a lot.  What a I missing?  Why isn't this change adding about 8-16KB per process?

Comment (shefty) [reply include/ofi_indexer.h]: I didn't read your data correctly.  This is only about 8KB per process increase.  Thanks

**Comment by shefty** [comment]
Do not worry about the Jenkins bot for now.  That is still undergoing testing to get some kinks out.  Until we switch over, the bot labeled Intel CI (buildbot) is handling the testing.
