### PR TITLE
prov/psm2: Fix a segfault when the provider is loaded dynamically

### LINKED ISSUE #3282: Shared context test crashes on psm2 when it's built as a DL provider
Test: fi_shared_ctx -p "psm2"

I see the following crash on psm2 provider when it's built as a separate dynamic library:

```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff6a9d0ed in getenv () from /lib64/libc.so.6
(gdb) bt
#0  0x00007ffff6a9d0ed in getenv () from /lib64/libc.so.6
#1  0x00007ffff63cb470 in fini_ipath_backtrace () from /lib64/libinfinipath.so.4
#2  0x00007ffff7deab7a in _dl_fini () from /lib64/ld-linux-x86-64.so.2
#3  0x00007ffff6a9da69 in __run_exit_handlers () from /lib64/libc.so.6
#4  0x00007ffff6a9dab5 in exit () from /lib64/libc.so.6
#5  0x00007ffff6a86c0c in __libc_start_main () from /lib64/libc.so.6
#6  0x0000000000401759 in _start ()
```

The issue is present in v1.5.0 as well.

### PR DESCRIPTION
**Pull request by j-xiong**
Under certain condition, putenv() is called to add an environment
variable to automatically turn on the PSM2 multi EP support. This
works fine fine as a built-in provider. However, if the provider
is dynamically loaded, the environment becomes corrupted after the
provider is unloaded. This can cause the PSM2 library destructor
to segfault within a getenv() call upon exit() being called.

This is fixed by replacing putenv() with setenv(), which makes a
copy of the string arguments.

Fixes #3282 

Signed-off-by: Jianxin Xiong <jianxin.xiong@intel.com>

### CODE REVIEW

File: prov/psm2/src/psmx2_init.c [hunk 1]
```diff
@@ -97,7 +97,7 @@ static int psmx2_init_lib(int default_multi_ep)
 		goto out;
 
 	if (default_multi_ep && !getenv("PSM2_MULTI_EP"))
-		putenv("PSM2_MULTI_EP=1");
+		putenv(strdup("PSM2_MULTI_EP=1"));
```
Comment (gladkovdmitry17) [inline prov/psm2/src/psmx2_init.c]: What do you think about using the another POSIX-compliant variant [`setenv`](https://sourceware.org/git/?p=glibc.git;a=blob;f=stdlib/setenv.c) that makes a copy of the provided string and doesn't use the parameter directly in contrast to [`putenv`](https://sourceware.org/git/?p=glibc.git;a=blob;f=stdlib/putenv.c)? The remaining part of the psm/psm2 providers uses `setenv`

Comment (j-xiong) [reply prov/psm2/src/psmx2_init.c]: Good catch. Thanks.
