### PR TITLE
usnic: fix compilation issue with new libibverbs

### LINKED ISSUE #2682: usnic provider fails to compile with new libibverbs
Apparently libibverbs changed its `kern-abi.h` recently, and that is causing libfabric's usnic provider to fail to compile.

Bug initially filed upstream: http://bugs.openfabrics.org/show_bug.cgi?id=2614

### PR DESCRIPTION
**Pull request by jsquyres**
libibverbs recently modified the internals of struct ibv_modify_qp in
kern-abi.h.  This commit adds the relevant configury to the usnic
provider to handle both old and new <infiniband/kern-abi.h>.

Signed-off-by: Jeff Squyres <jsquyres@cisco.com>

Fixes #2682

### CODE REVIEW

**Comment by shefty** [comment]
Is the usnic provider dependent on libibverbs as a library, or only on the installed header files?

**Comment by shefty** [comment]
Grepping the usnic code, I see it uses 2 verbs calls.  One is ibv_read_sysfs_file().  I think that can be replaced with fi_read_file() helper function.  The other is ibv_register_driver().  I wonder if that call is needed.  It looks like usnic issues write() calls directly to the kernel.  If so, maybe you could include the kern-abi.h file that you need and remove any links between usnic and libibverbs?

**Comment by shefty** [comment]
Btw, libibverbs will no longer support out of tree 'providers', so usnic's use of libibverbs will no longer be supported.  So it's in our interest to avoid using it.  (They are no longer guaranteeing API compatibility with providers.)  It looks like ibv_register_driver just allocates a data structure and sticks it on a list.  Maybe this is an easy change?

**Comment by goodell** [comment]
Jeff/Ben will know for sure, but IIRC the `ibv_register_driver` call is just there so that we can insert a dummy provider to avoid a warning `printf` in older versions of `libibverbs`.

**Comment by jsquyres** [comment]
@shefty I think this comes down to two issues:

# Use of ibv_foo calls

Yes, @goodell is correct: the call to `ibv_register_driver` is so that we can insert a "fake" usNIC verbs provider to quash older versions of libfabric from unconditionally emitting a warning to stderr.  It's ugly, but it's better than answering a zillion customer questions ("why am I getting a warning about no provider being found for usnic devices?").

That being said, that call to `ibv_register_driver` is already protected by configury -- it won't compile if `verbs.h` isn't present.  The call to `ibv_read_sysfs_file` is also in this protected-by-configury fake usNIC driver (i.e., meaning it's safe to use because that whole .c file isn't compiled if verbs.h isn't present).

I'm not too worried about this code being no longer supported.  Hypothetically, this "no usNIC verbs provider present" problem will resolve itself over time due to https://github.com/cisco/libusnic_verbs (which has been accepted upstream by various distros).  Hence, if this code in libfabric becomes too burdensome to maintain, we can likely remove it.  We'd like to keep it for a while, however, because people are still using older Linux distros that do not have the libusnic_verbs fake verbs provider.

# Writing / reading to the kernel

Down below in the usnic_direct subdirectory, we do `write()` directly to the usNIC kernel driver.  That's what we use the kern-abi.h file for (to know the structs to read / write).

Your idea of caching an older version of kern-abi.h is interesting.  Let me take this issue back and discuss it internally.

**Comment by shefty** [comment]
Just looking at the code, I didn't see where the usnic provider needs libibverbs.  It needs a copy of the kernel header file and a call to read sysfs, which libfabric already provides.  Why is it being linked?

**Comment by jsquyres** [comment]
We only link against libibverbs when its present, and it's solely for that fake usnic verbs provider.

The stuff in `prov/usnic/src/usnic_direct` only uses `kern-abi.h`, and doesn't use any ibv_foo calls.

**Comment by shefty** [comment]
But why do you _need_ a fake usnic verbs provider?  What does that have to do with libfabric?

**Comment by jsquyres** [comment]
The fake usnic provider is there to solve the problem of libibverbs spuriously printing a scary warning message that implies that usnic is not working.

This warning message will be emitted if the verbs provider is present *at all* (even if there are no other verbs devices).  Hence, even if you're on a system with only usnic devices, if the verbs provider is present, it will emit this scary warning.  So we put this fake provider in to squelch the warning message.

**Comment by goodell** [comment]
> So we put this fake provider in to squelch the warning message.

To elaborate on this: [Jeff eliminated the libibverbs warning message upstream a little while back](https://github.com/linux-rdma/rdma-core/commit/54883e413d4c40508e25f447daf5430d2f00cb82), but that doesn't help for systems with older libibverbs installations.  This is a workaround *for a libibverbs bug* until older installs are sufficiently rare that it can be dropped from the libfabric usnic provider.

**Comment by jsquyres** [comment]
PR updated to use a cached version of `kern-abi.h`.

Note that @jgunthorpe's changes from #2685 are also necessary (specifically, the change from `driver.h` to `verbs.h` in one file) to make the usnic libfabric provider compile with new versions of libibverbs.  I didn't include his changes in this PR so as not to cause conflicts on his PR.

It would likely be easiest to merge #2685 first, and then this one.

**Comment by jgunthorpe** [comment]
@jsquyres @goodell rdma-core 13 might no longer allow compiling against ibv_register_driver, so you will need to update your autoconf to not compile that one usnic file.

I recommend the following logic:
 - If verbs_register_driver exists in infiniband/driver.h do not compile (verbs has the patch goodell pointed out)
 - If infiniband/driver.h does not exist do not compile (verbs is new and has the patch)
 - If infiniband/driver.h exists then compile (verbs is old)

Or remove it entirely.

Note that the current proposal is that *dynamic linking* of this usnic stuff would fail with rdma-core 13 due to this call. I'm unclear how big a problem that is for libfabric?

**Comment by jsquyres** [comment]
@jgunthorpe Sounds good.  But I think the configure check could be simpler: if we can't compile against libibverbs and resolve `ibv_register_driver`, don't compile the usnic fake driver.  I.e., just use `AC_CHECK_FUNCS([ibv_register_driver])` in the usnic configury.

Am I missing something?

**Comment by goodell** [comment]
> Am I missing something?

@jsquyres I think Jason is recommending that we eliminate linking against libibverbs in a case that we don't need to (his first bullet point above), which is reasonable.

**Comment by jgunthorpe** [comment]
@jsquyres  

AC_CHECK_FUNC should never be used. eg this is what the the shm_open test expands to in libfabric:

```
 char shm_open ();
 int
 main ()
 {
 return shm_open ();
   ;
   return 0;
 }
```

Which succeeds even if there is no function prototype, which is never what you want these days.

If you attempt this with the proposed libibverbs it will succeed and link to the 'PRIVATE' symbol, even though there is no header file export for it.

@goodell is right, the desire is to limit linking to ibverbs to only those cases that absolutely need it since we'd like to eliminate the symbol version you are using entirely from the library ..

**Comment by jsquyres** [comment]
Agreed -- limiting linking against verbs is a Good Thing.  I didn't say anything about it because I silently agreed.  😄 

And yes, you're right -- AC_CHECK_FUNC was not the right thing.  I should have said AC_CHECK_LIB.  Specifically:

```
AC_CHECK_LIB([ibverbs], [ibv_register_driver], ...)
```

**Comment by jgunthorpe** [comment]
AC_CHECK_LIB is no better... The ac test must include the right header file.

**Comment by jsquyres** [comment]
I see my confusion now: the intent of linux-rdma/rdma-core#65 is not to make `ibv_register_driver` private in the linker sense.  I.e., trying to link to the symbol `ibv_register_driver` from an application *will still work* -- the symbol will still exist in `libibverbs.so`; the RDMA maintainers are just saying "don't use it."

I'll poke around with AC_CHECK_HEADER and AC_CHECK_DECL to see if I can make those work.

File: prov/usnic/src/usnic_direct/usnic_verbs_kern-abi.h [hunk 1]
```diff
@@ -0,0 +1,882 @@
...
+	__u32 max_send_sge;
+	__u32 max_recv_sge;
+	__u32 max_inline_data;
+};
+
+struct ibv_create_srq_resp_v5 {
+	__u32 srq_handle;
+};
+
+#endif /* KERN_ABI_H */
```
Comment (shefty) [inline prov/usnic/src/usnic_direct/usnic_verbs_kern-abi.h]: Do you want to keep all definitions, or limit to only those structures that you need?

Comment (jgunthorpe) [inline prov/usnic/src/usnic_direct/usnic_verbs_kern-abi.h]: Remember these declarations are copies of the declarations in /usr/include/rdma/ib_user_verbs.h (ie the kernel headers), ideally you'd use the actual kernel headers unchanged for this sort of stuff...

**Comment by jsquyres** [comment]
New commits pushed:

1. original commit: use a cached `kern-abi.h`
1. new commit: do a reduction of @jgunthorpe's test -- Jason and I talked about using AC_COMPILE_IFELSE, but I couldn't get it to work out nicely/simply.  I used AC_CHECK_HEADER and AC_CHECK_DECL.
1. new commit: limit the use of -libverbs

File: prov/usnic/src/usnic_direct/usnic_verbs_kern-abi.h (hunk 1 above)
Comment (jsquyres) [inline prov/usnic/src/usnic_direct/usnic_verbs_kern-abi.h]: What's the standard practice -- copy the whole thing, or just the ones you need?

I'm happy to go either way; I just did the copy-the-whole-thing for simplicity / ease of maintenance.

Comment (goodell) [inline prov/usnic/src/usnic_direct/usnic_verbs_kern-abi.h]: I think the *best* practice would be direct use of the installed kernel headers, no cached copy at all.  But that might not be quite as quick of a change for us, depending on the exact contents of the kernel headers.  How about we stick with what you have for the moment and take a TODO for ourselves to switch usnic_direct over to use the kernel headers instead at some point?

Comment (jsquyres) [inline prov/usnic/src/usnic_direct/usnic_verbs_kern-abi.h]: @jgunthorpe Dave and I iterated on this internally; we like your "just use the Kernel header" approach better.  I have a version that does that, and will update this PR shortly.

**Comment by jsquyres** [comment]
New commit pushed that switches from libibverbs `kern-abi.h` to the kernel's `rdma/ib_user_verbs.h`
