### PR TITLE
verbs,ofi_rxm: check hugepages when fork enabled

### LINKED ISSUE #4969: verbs;ofi_rxm: Registration of hugepages fails without RDMAV_HUGEPAGES_SAFE=1
@shefty @a-ilango @swelch 

The common core code for memory allocation of buffer pools utilizes hugepages if they are available. When those hugepages are used with buffer pools, then the NIC fails to register them with the NIC. 

Specifically, this occurs with verbs and rxm when rxm attempts to register a buffer for transfer using space from the local buffer pool. See https://github.com/ofiwg/libfabric/blob/master/prov/util/src/util_buf.c#L115 for the exact point of failure. (with rxm_buf_reg as the function being used in that pointer)

```
(gdb) where
#0 0x00007fc8e4b16f81 in free () from /lib64/libc.so.6
#1 0x00007fc8e508b851 in ofi_freealign (memptr=<optimized out>) at ./include/unix/osd.h:99
#2 ofi_bufpool_grow (pool=pool@entry=0x66ecd0) at prov/util/src/util_buf.c:182
#3 0x00007fc8e50d0e78 in ofi_buf_alloc (pool=0x66ecd0) at ./include/ofi_mem.h:431
#4 rxm_rx_buf_alloc (rxm_ep=0x6701b0) at prov/rxm/src/rxm.h:1028
#5 rxm_ep_prepost_buf (rxm_ep=rxm_ep@entry=0x6701b0, msg_ep=0x66fcf0) at prov/rxm/src/rxm_cq.c:1267
#6 0x00007fc8e50c5fa8 in rxm_msg_ep_open (rxm_ep=rxm_ep@entry=0x6701b0, msg_info=<optimized out>,
context=context@entry=0x66f460, rxm_conn=<optimized out>) at prov/rxm/src/rxm_conn.c:841
#7 0x00007fc8e50c7de4 in rxm_conn_connect (addr=0x9fae80, handle=0x66f460, util_ep=0x6701b0)
at prov/rxm/src/rxm_conn.c:1440
#8 rxm_cmap_connect (rxm_ep=0x6701b0, fi_addr=<optimized out>, handle=handle@entry=0x66f460)
at prov/rxm/src/rxm_conn.c:617
#9 0x00007fc8e50cb378 in rxm_ep_prepare_tx (rxm_conn=<synthetic pointer>, dest_addr=<optimized out>, rxm_ep=0x6701b0)
at prov/rxm/src/rxm.h:986
#10 rxm_ep_tinject_fast (ep_fid=0x6701b0, buf=0x0, len=0, dest_addr=<optimized out>, tag=17592187092993)
at prov/rxm/src/rxm_ep.c:1833
```

Libibverbs has some issues with hugepages, and as part of some older work, they introduced an environment variable that handles this problem: See https://lists.openfabrics.org/pipermail/ewg/2010-July/015609.html

If I export RDMAV_HUGEPAGES_SAFE=1, everything works just fine. This environment variable tells the libibverbs library to check the page size every time memory is registered. This allows the library to properly detect range and length of regions for memory registration as required by the Infiniband specification.

I would suggest the following:

- Short term: Add a check into the fi_fabric call for the verbs provider. Attempt to allocate a hugepage, and if it succeeds, set the RDMAV_HUGEPAGES_SAFE variable under the assumption that the application and common core core in libfabric MAY use hugepages without us being aware. This has to be done before ibv_fork_init is called.
- Medium term: Add a provider-specific opt that we can set from the fabric to enable or disable hugepage usage, then pass that through to the common-core code so that we have the option to run with or without hugepages. Generally, we want to run with hugepages, but there is a cost to running with hugepages that cannot be ignored. When running with hugepages, and FI_LOCAL_MR, we see a 10x increase in latency due to the increased checking done during registration. This increase in latency seems to only affect messages after the rendezvous threshold. Using the memory registration cache significantly helps, but the current implementation (glibc memory handlers) is insufficient for detecting when memory is released by the process and causes silent corruption in MPI. We could choose to add the option, or find a complete solution for the memory cache. 
- Long term: I've started a discussion on the OFIWG mailing list regarding how does libfabric want to handle hugepage support. Is it something that gets handled transparently by providers and applications accept the costs of additional checking? Or do we provide applications with a way to indicate intent or request support for hugepages?

### PR DESCRIPTION
**Pull request by jswaro**
Memory registration can fail with libibverbs when hugepages are
available and application fork support is enabled. In multi-model
applications, libfabric cannot guarantee the correct ordering of
calls to ibv_fork_init with the correct environment settings. To
address both of these problems, the verbs provider does not set any
environment variables related to fork and hugepage safety.

Signed-off-by: James Swaro <jswaro@cray.com>

closes #4969

### CODE REVIEW

File: prov/verbs/src/verbs_info.c [hunk 1]
```diff
@@ -1207,6 +1209,23 @@ int fi_ibv_init_info(const struct fi_info **all_infos)
...
+			ret = munmap(buffer, VERBS_MMAP_TEST_BUFFER_LEN_SIZE);
+			assert(ret == 0);
+
+			/* assume hugepages will be used and set
+			   environment for correctness */
+                        setenv("RDMAV_HUGEPAGES_SAFE", "1", 1);
+
+                        VERBS_INFO(FI_LOG_CORE, "Huge pages may be in-use, "
+				"enabling huge page support\n");
+                }
```
Comment (a-ilango) [inline prov/verbs/src/verbs_info.c]: As enabling this by default increases the memory registration latency, I wonder if this should be left to the user to set this env variable if they see a memory registration failure.

Comment (jswaro) [reply prov/verbs/src/verbs_info.c]: If they don't enable it, the application with crash with a segmentation fault in the common core code. @swelch was working on a patch for that actually, but at minimum -- we would need some sort of diagnostic/debugging message to the user so that they would be aware that such a variable needed to be set.

File: prov/verbs/src/verbs_info.c [hunk 2]
```diff
@@ -1186,13 +1186,15 @@ static int fi_ibv_fill_addr(struct rdma_addrinfo *rai, struct fi_info **info,
 }
 
 #define VERBS_NUM_DOMAIN_TYPES		3
+#define VERBS_MMAP_TEST_BUFFER_LEN_SIZE (1llu << 21)
```
Comment (shefty) [inline prov/verbs/src/verbs_info.c]: This is arbitrary.  There is an existing call, ofi_get_hugepage_size() that will return the correct size

Comment (jswaro) [reply prov/verbs/src/verbs_info.c]: Resolved.

File: prov/verbs/src/verbs_info.c (hunk 1 above)
Comment (a-ilango) [reply prov/verbs/src/verbs_info.c]: I see. I thought the memory registration call failed by returning an error.

To me it seems that we need this patch if we're to maintain current behavior. In case we turn off fork safety as the default behavior then we can skip this patch. @shefty thoughts?

If we add this patch, can you please update the log message to say that memory registration latency would be high if fork safety is not disabled? And it should probably be a warning instead of info level log.

Comment (jswaro) [reply prov/verbs/src/verbs_info.c]: Sounds fine to me. If we disable the libfabric verbs fork support by default, and provide guidance to application writers to use the libibverbs environment variables -- then I feel that we can discard this patch. That would resolve #4969  and #4974 in one go.

File: prov/verbs/src/verbs_info.c [hunk 3]
```diff
@@ -1207,6 +1209,32 @@ int fi_ibv_init_info(const struct fi_info **all_infos)
...
 
 	if (!fi_ibv_gl_data.fork_unsafe) {
+		/* check to see if hugepages can be used */
+		buffer_size = ofi_get_hugepage_size();
+		if (buffer_size > 0) {
+			/* attempt to map hugepage if valid size found */
+			buffer = mmap(NULL, buffer_size,
+				PROT_READ | PROT_WRITE,
+				MAP_PRIVATE | MAP_ANONYMOUS | MAP_HUGETLB,
+				-1, 0);
```
Comment (shefty) [inline prov/verbs/src/verbs_info.c]: Use ofi_alloc_hugepage_buf() and ofi_free_hugepage_buf().  We should probably create a new abstraction for this.  E.g:
```
int ofi_hugepage_enabled()
{
    size = ofi_get_hugepage_size();
    if (!size)
        return 0;
    ret = ofi_alloc_hugepage_buf(&ptr, size);
    if (ret)
        return 0;
    ofi_free_hugepage_buf(ptr, size);
    return 1;
}
The ofi_xxx_hugepage_xxx calls are scattered in the various osd.h files.  We should also define the function prototypes in maybe ofi_mem.h, so they are easier to find.

The hugepage support is also needed by the userfaultfd work (#4946).

File: prov/verbs/src/verbs_info.c (hunk 1 above)
Comment (shefty) [reply prov/verbs/src/verbs_info.c]: If the measurable performance impact is significant or if our fork support doesn't really exist because of other issues, I think we can disable it.  But until we can verify one of those, I think we proceed with this patch to maintain the current behavior as Arun mentioned.

Comment (jswaro) [reply prov/verbs/src/verbs_info.c]: In an alltoall between 64 ranks (1 rank per node), I observed a 10x increase in collective latency with 256KB messages and higher. As I mentioned in the original issue, when using the provider as-is today, there is a 30-60% increase in latency for messages above the rendezvous threshold. The increased latency for message sizes above the rendezvous threshold becomes more pronounced as the number of ranks increases. Additionally, if the rendezvous threshold is decreased, all messages above the rendezvous threshold experience additionally latency. 

When running with hugepages, and RDMAV_HUGEPAGES_SAFE=1 for hugepage safety, and default fork safety today -- there is a performance impact to applications between .3 to 10x or more. 

It doesn't affect the provider as much if the memory registration cache is in use, but we do not use it today due to silent data corruption issues. #4946 is relevant to that discussion.

Comment (shefty) [reply prov/verbs/src/verbs_info.c]: Is the performance impact related to huge pages or fork?

Comment (shefty) [reply prov/verbs/src/verbs_info.c]: I think this is the answer I'm looking for
```
default fork safety today - there is a performance impact to applications between .3 to 10x or more.
```
That delta is based on disabling for support, correct?

Comment (jswaro) [reply prov/verbs/src/verbs_info.c]: To be completely accurate, 

```
If 
    the provider requests fork safety, (FI_FORK_UNSAFE=0, [default]) and 
    hugepages safety IS NOT requested (RDMAV_HUGEPAGES_SAFE=0), 
        latency is normal. [ NOTE: this condition requires that hugepages are not enabled, or registration errors occur ]

If 
    the provider requests fork safety, (FI_FORK_UNSAFE=0, [default]) and 
    hugepages safety IS requested (RDMAV_HUGEPAGES_SAFE=1), 
        latency increases by a factor of .3 to 10x or more

If 
    the provider does not request fork safety (FI_FORK_UNSAFE=1) , 
    latency is normal. [RMDAV_HUGEPAGES_SAFE is ignored in this case] 
```

The delta in performance is really associated with enabling hugepage safety if libibverbs fork support is requested. If libibverbs fork support isn't requested, hugepage checking isn't necessary in libibverbs.

File: prov/verbs/src/verbs_info.c (hunk 3 above)
Comment (jswaro) [reply prov/verbs/src/verbs_info.c]: I've added a separate commit for the function. It looks like we won't need it, but we could cherry pick it out and keep it for later. 

@shefty thoughts?

Comment (shefty) [reply prov/verbs/src/verbs_info.c]: Yes - regardless of what we decide, I think we should pull in that change.  Thanks!

File: prov/verbs/src/verbs_info.c (hunk 1 above)
Comment (shefty) [reply prov/verbs/src/verbs_info.c]: This helps.  So the change from our original decision is that hugepages are more of a factor now and can have a significant impact.  Thanks!

@a-ilango @jsquyres @hppritcha -The short question here is whether we should disable fork support by default now, to greatly improve performance when huge pages are in use.

Comment (jswaro) [reply prov/verbs/src/verbs_info.c]: I would be in favor of removing the FI_FORK_SAFE variable and disabling fork support by default. The other issue, #4974, indicates a problem in multi-model applications where different libraries calling into libibverbs can complicate matters, or cause errors. 

As much as I dislike the idea of applications using the IBV/RDMAV environment variables directly, it doesn't seem like we can prevent a bad order of operations to the libibverbs layer without extracting ourselves from environment variable management. The IBV/RDMAV environment variables are "global" in the sense that it doesn't matter who makes it to libibverbs first. FI_* variables will influence the underlying libraries at the point in time where the provider is initialized, which could be after the application probes ibverbs by itself. 

Applications using the verbs provider, or intending to use the verbs provider can set IBV_FORK_SAFE, and/or RDMAV_HUGEPAGES_SAFE with the correct context. Libfabric has no idea whether an application will attempt to call ibv_* functions directly, but the application does.

Comment (shefty) [reply prov/verbs/src/verbs_info.c]: @jswaro  I agree.  I don't see a way for libfabric to use ibv_fork_init() safely.  I think we need to remove the fork support from libfabric and rely on it being set directly when verbs is used.

Comment (jsquyres) [reply prov/verbs/src/verbs_info.c]: This kinda sucks, but I don't see a better answer, either.

This needs to be clearly documented somewhere.

Comment (jswaro) [reply prov/verbs/src/verbs_info.c]: @jsquyres Agreed. I was thinking we should potentially add another sections 'notes' or similar, for the purpose of discussing additional environment variable that influence the provider, but fall outside of the domain of libfabric such as IBV_FORK_SAFE, or RDMAV_HUGEPAGES_SAFE. It could also be a section for discussing information relevant to a provider, but not directly influenced by the provider. 

That same section could be used for MR cache change, #4946 & #4956, to describe the limitations of the implementation with respect to the OS. In that specific case, something like this could go into a 'notes' section:

> The support for hugetlbfs and shared memory areas and non-page-fault
>        events was added in Linux 4.11

**Comment by shefty** [comment]
@jswaro - Can you update this PR to remove the call to ibv_fork_init, but keep the hugepage patch?  I would document the fork details as part of the verbs man page.

**Comment by jswaro** [comment]
Sure. I'm going to be out for a few weeks so if we don't commit this today, I'll need someone else to merge it.

**Comment by jswaro** [comment]
> @jswaro - Can you update this PR to remove the call to ibv_fork_init, but keep the hugepage patch?

Specifically, which part of the hugepage patch? The new utility function call, RDMAV environment export, or both?

**Comment by shefty** [comment]
@jswaro - the first commit in this PR.  IIUC, the second commit won't be needed if we remove the call to ibv_fork_init

**Comment by jswaro** [comment]
Let me know if there is anything else. I've repushed the commits with modifications
