### PR TITLE
usnic: Handle data in failed connection requests

### LINKED ISSUE #2134: usnic: Failed connection requests do not handle data correctly.
The `usdf_cm_msg_connreq_failed` function can be called when `creq->datalen` is in host order or network order. This causes a seg fault in [`memcpy`](https://github.com/ofiwg/libfabric/blob/master/prov/usnic/src/usdf_cm.c#L254) in some situations due to the incorrect size being specified.

This probably needs a flag, or to be split into separate functions depending on if the failed request has happened after/before converting to network order. In the future, this should be refactored to avoid the possibility of having data in both states in the same variable.

### PR DESCRIPTION
**Pull request by bturrubiates**
This fixes #2134. This change makes it so that data is only reported when the failure is caused by the remote end rejecting something.

### CODE REVIEW

File: prov/usnic/src/usdf_pep.c [hunk 1]
```diff
@@ -186,37 +186,39 @@ usdf_pep_read_connreq(void *v)
...
 
 		entry->fid = &pep->pep_fid.fid;
 		entry->info = usdf_pep_conn_info(crp);
-		if (entry->info == NULL) {
-			free(entry);
-			usdf_cm_msg_connreq_failed(crp, -FI_ENOMEM);
-			return 0;
-		}
+		if (entry->info == NULL)
+			goto free_entry_and_report_failure;
```
Comment (jsquyres) [inline prov/usnic/src/usdf_pep.c]: What's the value of `ret` here?

File: prov/usnic/src/usdf_cm.c [hunk 2]
```diff
@@ -209,25 +209,82 @@ usdf_cm_msg_accept(struct fid_ep *fep, const void *param, size_t paramlen)
...
+/* Report a connection management related failure. Sometimes the data should be
+ * skipped, in this case the skip data argument can be set to something with a
+ * truthy value.
+ *
+ * If data is to be generated for the error entry, then the connection request
+ * is assumed to have the data size in host order. If something fails during
+ * processing of the error data, then the EQ entry will still be generated
+ * without the error data.
+ */
+void usdf_cm_report_failure(struct usdf_connreq *crp, int error, bool skip_data)
```
Comment (jsquyres) [inline prov/usnic/src/usdf_cm.c]: Minor nit: I'm not a big fan of parameters that exhibit negative logic (e.g., "if `skip_data` is `true`, then you *don't* do something").  If you care, it would be nice to switch to a parameter that exhibits positive logic.

File: prov/usnic/src/usdf_pep.c (hunk 1 above)
Comment (bturrubiates) [inline prov/usnic/src/usdf_pep.c]: > What's the value of ret here?

Hmm, missed that. Thanks. `usdf_pep_conn_info` seems to be only be able to fail in the event of a failure in `calloc`, so I'll modify that to `-FI_ENOMEM`.

**Comment by bturrubiates** [comment]
Not sure why Travis failed, it seems that the sockets provider failed the `ubertest`. I kicked off a new build...
