### PR TITLE
prov/verbs: Serialize an access to connection hash for AV entry

### LINKED ISSUE #3302: verbs/rdm: possible races in connection code
I'm running some OSU benchmarks on top of MPICH on top of libfabric with the verbs provider. I see some crashes in libfabric. They happen in the connection code, in fi_ibv_rdm_av_map_addr_to_conn_add_new_conn(), in the calls to HASH_FIND or HASH_ADD.

Here's a trace:

    (gdb) bt
    #0  0x00007ffff5ef632a in fi_ibv_rdm_av_map_addr_to_conn_add_new_conn (ep=0x6783e0, addr=6956928) at prov/verbs/src/ep_rdm/verbs_av_ep_rdm.c:563
    #1  0x00007ffff5f1658f in fi_ibv_rdm_tagged_recvmsg (ep_fid=0x6783e0, msg=0x7fffffffced0, flags=0) at prov/verbs/src/ep_rdm/verbs_tagged_ep_rdm.c:126
    #2  0x00007ffff5f16a6b in fi_ibv_rdm_tagged_recvv (ep_fid=0x6783e0, iov=0x7fffffffcf60, desc=0x7fffffffcf40, count=1, src_addr=6956928, tag=17592221696001, 
    ignore=17293822569102704640, context=0x7ffff78a3ea0 <MPIR_Request_direct+320>) at prov/verbs/src/ep_rdm/verbs_tagged_ep_rdm.c:200
    #3  0x00007ffff5f16ad5 in fi_ibv_rdm_tagged_recvfrom (ep_fid=0x6783e0, buf=0x0, len=0, desc=0x0, src_addr=6956928, tag=17592221696001, 
    ignore=17293822569102704640, context=0x7ffff78a3ea0 <MPIR_Request_direct+320>) at prov/verbs/src/ep_rdm/verbs_tagged_ep_rdm.c:213
    #4  0x00007ffff7416222 in fi_trecv (desc=0x0, context=0x7ffff78a3ea0 <MPIR_Request_direct+320>, ignore=17293822569102704640, tag=17592221696001, 
    src_addr=<optimized out>, len=0, buf=0x0, ep=<optimized out>) at /home/users/fzago/install/include/rdma/fi_tagged.h:93
    #5  MPIDI_OFI_do_irecv (flags=<optimized out>, mode=0, request=0x7fffffffd060, addr=<optimized out>, context_offset=1, 
    comm=0x7ffff7881f80 <MPIR_Comm_builtin>, tag=<optimized out>, rank=<optimized out>, datatype=1275068685, count=0, buf=0x0)
    at ./src/mpid/ch4/netmod/include/../ofi/ofi_recv.h:215
    #6  MPIDI_NM_mpi_irecv (request=0x7fffffffd060, addr=<optimized out>, context_offset=1, comm=0x7ffff7881f80 <MPIR_Comm_builtin>, tag=<optimized out>, 
    rank=<optimized out>, datatype=1275068685, count=0, buf=0x0) at ./src/mpid/ch4/netmod/include/../ofi/ofi_recv.h:387
    #7  MPID_Irecv (request=0x7fffffffd060, context_offset=1, comm=0x7ffff7881f80 <MPIR_Comm_builtin>, tag=<optimized out>, rank=<optimized out>, 
    datatype=1275068685, count=0, buf=0x0) at ./src/mpid/ch4/src/ch4_recv.h:322
    #8  MPIC_Sendrecv (sendbuf=sendbuf@entry=0x0, sendcount=sendcount@entry=0, sendtype=sendtype@entry=1275068685, dest=dest@entry=22, sendtag=sendtag@entry=1, 
    recvbuf=recvbuf@entry=0x0, recvcount=recvcount@entry=0, recvtype=recvtype@entry=1275068685, source=source@entry=34, recvtag=recvtag@entry=1, 
    comm_ptr=comm_ptr@entry=0x7ffff7881f80 <MPIR_Comm_builtin>, status=0x7fffffffd070, status@entry=0x1, errflag=errflag@entry=0x7fffffffd618)
    at src/mpi/coll/helper_fns.c:478
    #9  0x00007ffff66266b3 in MPIR_Barrier_recursive_doubling (comm_ptr=comm_ptr@entry=0x7ffff7881f80 <MPIR_Comm_builtin>, errflag=errflag@entry=0x7fffffffd618)
    at src/mpi/coll/barrier.c:275
    #10 0x00007ffff6628818 in MPIDI_OFI_Barrier_recursive_doubling (params_container=<optimized out>, errflag=0x7fffffffd618, 
    comm_ptr=0x7ffff7881f80 <MPIR_Comm_builtin>) at ./src/mpid/ch4/netmod/include/../ofi/ofi_coll_impl.h:27
    #11 MPIDI_OFI_Barrier_call (ch4_algo_parameters_container=<optimized out>, errflag=0x7fffffffd618, comm_ptr=0x7ffff7881f80 <MPIR_Comm_builtin>)
    at ./src/mpid/ch4/netmod/include/../ofi/ofi_coll_select.h:25
    #12 MPIDI_NM_mpi_barrier (ch4_algo_parameters_container_in=<optimized out>, errflag=0x7fffffffd618, comm_ptr=0x7ffff7881f80 <MPIR_Comm_builtin>)
    at ./src/mpid/ch4/netmod/include/../ofi/ofi_coll.h:35
    #13 MPIDI_Barrier_composition_beta (ch4_algo_parameters_container=<optimized out>, errflag=0x7fffffffd618, comm=0x7ffff7881f80 <MPIR_Comm_builtin>)
    at ./src/mpid/ch4/src/ch4_coll_impl.h:95
    #14 MPIDI_CH4_Barrier_call (ch4_algo_parameters_container=<optimized out>, errflag=0x7fffffffd618, comm=0x7ffff7881f80 <MPIR_Comm_builtin>)
    at ./src/mpid/ch4/src/ch4_coll_select.h:51
    #15 MPID_Barrier (errflag=0x7fffffffd618, comm=0x7ffff7881f80 <MPIR_Comm_builtin>) at ./src/mpid/ch4/src/ch4_coll.h:28
    #16 PMPI_Barrier (comm=comm@entry=1140850688) at src/mpi/coll/barrier.c:428
    #17 0x0000000000401002 in main (argc=1, argv=0x7fffffffd7b8) at osu_reduce.c:94

Looking at the code, it appears that both the application calling fi_trecv and the CM thread can trigger the createion of a new connection. There is no locking around the hash usage. If a new connection request arrives at the same time an application tries to post receives, there could be a race, as both threads would create the connection and try to insert it. There is also no warranty that the new connection couldn't be inserted by the other thread after checking that the connection is not in the hash.

The problem is reproducible.

### PR DESCRIPTION
**Pull request by gladkovdmitry17**
- Serialize an access to connection hash that can be accessed from CM thread and main thread.
- Replace `free()` by `ofi_freealign()`. This is minor changes, because `ofi_freealign()` is mapped to `free()`. Just to keep code style and be compliant with another place where `ofi_frealign(av_entry)` is used instead.

Fixes #3302 

Signed-off-by: Dmitry Gladkov <dmitry.gladkov@intel.com>

### CODE REVIEW

File: prov/verbs/src/ep_rdm/verbs_rdm_cm.c [hunk 1]
```diff
@@ -442,6 +445,7 @@ fi_ibv_rdm_process_connect_request(struct rdma_cm_event *event,
 		HASH_ADD(hh, ep->domain->rdm_cm->av_hash, addr,
 			 FI_IBV_RDM_DFLT_ADDRLEN, av_entry);
 	} else {
+		pthread_mutex_lock(&av_entry->conn_lock);
 		HASH_FIND(hh, av_entry->conn_hash, &ep,
 			  sizeof(struct fi_ibv_rdm_ep *), conn);
 		if (!conn) {
```
Comment (fzago-cray) [inline prov/verbs/src/ep_rdm/verbs_rdm_cm.c]: mutex must be released in error path below.

File: prov/verbs/src/ep_rdm/verbs_av_ep_rdm.c [hunk 2]
```diff
@@ -560,6 +562,7 @@ fi_ibv_rdm_av_map_addr_to_conn_add_new_conn(struct fi_ibv_rdm_ep *ep,
 	struct fi_ibv_rdm_av_entry *av_entry =
 		fi_ibv_rdm_av_map_addr_to_av_entry(ep, addr);
 	if (av_entry) {
+		pthread_mutex_lock(&av_entry->conn_lock);
 		HASH_FIND(hh, av_entry->conn_hash,
 			  &ep, sizeof(struct fi_ibv_rdm_ep *), conn);
 		if (!conn) {
```
Comment (fzago-cray) [inline prov/verbs/src/ep_rdm/verbs_av_ep_rdm.c]: mutex must be released in error path below

File: prov/verbs/src/ep_rdm/verbs_av_ep_rdm.c [hunk 3]
```diff
@@ -590,6 +594,7 @@ fi_ibv_rdm_av_tbl_idx_to_conn_add_new_conn(struct fi_ibv_rdm_ep *ep,
 	struct fi_ibv_rdm_av_entry *av_entry =
 		fi_ibv_rdm_av_tbl_idx_to_av_entry(ep, addr);
 	if (av_entry) {
+		pthread_mutex_lock(&av_entry->conn_lock);
```
Comment (fzago-cray) [inline prov/verbs/src/ep_rdm/verbs_av_ep_rdm.c]: mutex must be released in error path below

File: prov/verbs/src/ep_rdm/verbs_rdm_cm.c (hunk 1 above)
Comment (gladkovdmitry17) [reply prov/verbs/src/ep_rdm/verbs_rdm_cm.c]: Ops, no need to be so quickly :) Done
Thanks!

File: prov/verbs/src/ep_rdm/verbs_av_ep_rdm.c (hunk 2 above)
Comment (gladkovdmitry17) [reply prov/verbs/src/ep_rdm/verbs_av_ep_rdm.c]: Done

File: prov/verbs/src/ep_rdm/verbs_av_ep_rdm.c (hunk 3 above)
Comment (gladkovdmitry17) [reply prov/verbs/src/ep_rdm/verbs_av_ep_rdm.c]: Done

File: prov/verbs/src/ep_rdm/verbs_ep_rdm.c [hunk 4]
```diff
@@ -416,16 +419,19 @@ static int fi_ibv_rdm_ep_close(fid_t fid)
...
 	}
 
         /* now destroy all connections that wasn't removed from HASH */
 	HASH_ITER(hh, ep->domain->rdm_cm->av_hash, av_entry, tmp) {
+		pthread_mutex_lock(&av_entry->conn_lock);
 		HASH_FIND(hh, av_entry->conn_hash, &ep,
 			  sizeof(struct fi_ibv_rdm_ep *), conn);
 		if (conn) {
 			HASH_DEL(av_entry->conn_hash, conn);
 			fi_ibv_rdm_conn_cleanup(conn);
```
Comment (fzago-cray) [inline prov/verbs/src/ep_rdm/verbs_ep_rdm.c]: Could this connection cleanup be done outside the lock?

File: prov/verbs/src/ep_rdm/verbs_ep_rdm.c [hunk 5]
```diff
@@ -435,6 +441,7 @@ static int fi_ibv_rdm_ep_close(fid_t fid)
 		av_entry = container_of(item,
 					struct fi_ibv_rdm_av_entry,
 					removed_next);
+		pthread_mutex_lock(&av_entry->conn_lock);
 		HASH_FIND(hh, av_entry->conn_hash, &ep,
 			  sizeof(struct fi_ibv_rdm_ep *), conn);
 		if (conn) {
```
Comment (fzago-cray) [inline prov/verbs/src/ep_rdm/verbs_ep_rdm.c]: Same here regarding connection cleanup.

File: prov/verbs/src/ep_rdm/verbs_av_ep_rdm.c [hunk 6]
```diff
@@ -607,6 +616,7 @@ fi_ibv_rdm_av_tbl_idx_to_conn_add_new_conn(struct fi_ibv_rdm_ep *ep,
 			HASH_ADD(hh, av_entry->conn_hash, ep,
 				 sizeof(struct fi_ibv_rdm_ep *), conn);
 		}
+		pthread_mutex_unlock(&av_entry->conn_lock);
 	}
```
Comment (shefty) [inline prov/verbs/src/ep_rdm/verbs_av_ep_rdm.c]: Can we restructure the error handling to jump (i.e. goto) a common exit routine, so that we don't miss calling unlock anywhere, including possible future updates to the code?

**Comment by shefty** [comment]
Can you add labels if this should be picked up for the v1.4.x and/or v1.5.x branches?

File: prov/verbs/src/ep_rdm/verbs_ep_rdm.c (hunk 4 above)
Comment (gladkovdmitry17) [reply prov/verbs/src/ep_rdm/verbs_ep_rdm.c]: Yes, that would be great.

File: prov/verbs/src/ep_rdm/verbs_ep_rdm.c (hunk 5 above)
Comment (gladkovdmitry17) [reply prov/verbs/src/ep_rdm/verbs_ep_rdm.c]: Sure, we can do this by adding ugly if-else statement. But it should be okay

**Comment by gladkovdmitry17** [comment]
> Can you add labels if this should be picked up for the v1.4.x and/or v1.5.x branches?

Seems I have no rights to do this. But seems, it should be picked up to v1.5.x branch.
v1.4.x doesn't contain `conn_hash`. There is only `av_hash`

File: prov/verbs/src/ep_rdm/verbs_av_ep_rdm.c (hunk 6 above)
Comment (gladkovdmitry17) [reply prov/verbs/src/ep_rdm/verbs_av_ep_rdm.c]: Yes, we can do this.
I've updated the places where it's possible

File: prov/verbs/src/ep_rdm/verbs_av_ep_rdm.c [hunk 7]
```diff
@@ -577,9 +580,12 @@ fi_ibv_rdm_av_map_addr_to_conn_add_new_conn(struct fi_ibv_rdm_ep *ep,
 			HASH_ADD(hh, av_entry->conn_hash, ep,
 				 sizeof(struct fi_ibv_rdm_ep *), conn);
 		}
+err:
```
Comment (fzago-cray) [inline prov/verbs/src/ep_rdm/verbs_av_ep_rdm.c]: This is misnamed. It's almost never going to be an error.

File: prov/verbs/src/ep_rdm/verbs_rdm.h [hunk 8]
```diff
@@ -334,6 +334,7 @@ enum fi_rdm_cm_role {
 
 struct fi_ibv_rdm_av_entry {
 	/* association of conn and EPs */
+	pthread_mutex_t			conn_lock;
```
Comment (shefty) [inline prov/verbs/src/ep_rdm/verbs_rdm.h]: Is this structure per each entry in the AV, as the name suggests?  If so, how can it be used to protect the hash table?

Comment (gladkovdmitry17) [reply prov/verbs/src/ep_rdm/verbs_rdm.h]: Yes, this structure (`struct fi_ibv_rdm_av_entry`) per each entry in the AV. But there is a hash in the AV entry that contains connection structures instances (`struct fi_ibv_rdm_conn`) per each Endpoint (i.e. key - EP, value - conn structure).
The `fi_ibv_domain::fi_ibv_rdm_cm::cm_lock` protects av_table and av_hash storages.

This solution is going to protect fi_ibv_rdm_av_entry::conn_hash storage.

File: prov/verbs/src/ep_rdm/verbs_av_ep_rdm.c (hunk 7 above)
Comment (gladkovdmitry17) [reply prov/verbs/src/ep_rdm/verbs_av_ep_rdm.c]: `done` label should be ok

**Comment by gladkovdmitry17** [comment]
@fzago-cray Please, confirm when we can merge the content of this PR to master branch. Thanks.

**Comment by fzago-cray** [comment]
I've already approved the change. Is there anything else I need to do?

**Comment by gladkovdmitry17** [comment]
> I've already approved the change. Is there anything else I need to do?

@fzago-cray Sorry, I missed this. Thanks!

**Comment by gladkovdmitry17** [comment]
@shefty Can we merge this PR into the `master` and `v1.5.x` branches and clsoe the #3302 ? Thanks.

**Comment by gladkovdmitry17** [comment]
@shefty This PR can't be picked up for the v1.5.x branch since there are no changes from master branch that fixes multiple AV per EP issue. Shall we picked up the whole set of changes (some commits from the #2975 and this PR)? Thanks!

**Comment by shefty** [comment]
I'll merge this, but I didn't understand your last comment wrt v1.5.x branch.  Are you saying that we need all 7 commits from #2975 plus this commit cherry-picked?
