### PR TITLE
src/common: fix segfault on print if address is NULL

### LINKED ISSUE #6204: prov/verbs, shm: libfabric v1.11.0 intel MPI 2020.2 fatal error/segfault
When using Intel Parallel 2020.2 and libfabric v1.11.0 the following leads to a fatal error (or segfault sometimes): 
```bash
$ mpirun -np 2 IMB-MPI1
```
Other tested versions include v1.10.0 and Intel-provided 1.10.1-impi and tested fine. Verbose logs w/ `debug` build were enabled for v1.11.0.

Successful on `dn` node, v1.10 and `shm`: [libf1_10_Intel2020p2_dn_shm.txt](https://github.com/ofiwg/libfabric/files/5117717/libf1_10_Intel2020p2_dn_shm.txt)
Successful on `sdv` node, v1.10 and `shm`: [libf1_10_Intel2020p2_sdv_shm.txt](https://github.com/ofiwg/libfabric/files/5117718/libf1_10_Intel2020p2_sdv_shm.txt)
Successful on `sdv` node, v1.10 and `verbs`: [libf1_10_Intel2020p2_sdv_verbs.txt](https://github.com/ofiwg/libfabric/files/5117719/libf1_10_Intel2020p2_sdv_verbs.txt)

Failure (fatal error) on `dn` node, v1.11 and `shm,verbs`: [libf1_11_Intel2020p2_dn.txt](https://github.com/ofiwg/libfabric/files/5117720/libf1_11_Intel2020p2_dn.txt)
Failure (segfault) on `dn` node, v1.11 and `shm,verbs`: [libf1_11_Intel2020p2_dn2.txt](https://github.com/ofiwg/libfabric/files/5117721/libf1_11_Intel2020p2_dn2.txt)
Failure (fatal error) on `sdv` node, v1.11 and `shm,verbs`: [libf1_11_Intel2020p2_sdv.txt](https://github.com/ofiwg/libfabric/files/5117722/libf1_11_Intel2020p2_sdv.txt)

Environment used:
```bash
export FI_PROVIDER="shm,verbs"
export FI_VERBS_IFACE=ib0
export I_MPI_HYDRA_TOPOLIB=ipl
export FI_LOG_LEVEL=debug
export I_MPI_DEBUG=6
```

### PR DESCRIPTION
**Pull request by aingerson**
Along with #6257 fixes #6204

### CODE REVIEW

File: prov/verbs/src/fi_verbs.c [hunk 1]
```diff
@@ -295,10 +295,12 @@ int vrb_get_rai_id(const char *node, const char *service, uint64_t flags,
...
-		ofi_straddr_log(&vrb_prov, FI_LOG_INFO, FI_LOG_FABRIC,
-				"src addr", (*rai)->ai_src_addr);
-		ofi_straddr_log(&vrb_prov, FI_LOG_INFO, FI_LOG_FABRIC,
-				"dst addr", (*rai)->ai_dst_addr);
+		if ((*rai)->ai_src_addr)
+			ofi_straddr_log(&vrb_prov, FI_LOG_INFO, FI_LOG_FABRIC,
+					"src addr", (*rai)->ai_src_addr);
+		if ((*rai)->ai_dst_addr)
+			ofi_straddr_log(&vrb_prov, FI_LOG_INFO, FI_LOG_FABRIC,
+					"dst addr", (*rai)->ai_dst_addr);
```
Comment (shefty) [inline prov/verbs/src/fi_verbs.c:303]: It may be better to modify ofi_straddr_log_internal() to display "(null)" when passed a null address.  That way, we avoid adding these checks, plus the logging is consistent, rather than it not being there at all.

Comment (aingerson) [reply prov/verbs/src/fi_verbs.c:303]: Good call

Comment (aingerson) [reply prov/verbs/src/fi_verbs.c]: Updated

**Review by shefty — APPROVED** [review]

**Comment by shefty** [comment]
bot:aws:retest
