### PR TITLE
verbs: Add defines and macros to support RHEL build

### LINKED ISSUE #4658: Compile errors on systems without XRC verbs support
libfabric master fails to build on systems that do not have XRC support (e.g., RHEL 6).  The compile errors are fairly obvious; just take any older version of `libibverbs` (before `rdma-core`) and try to compile -- you'll see the failures immediately.

The XRC code is quite pervasive in the verbs provider; I didn't want to make an attempt to make it safe to compile on XRC-less machines.  

I think there are two possibilities here:

1. Make the verbs provider safe to compile without XRC support.
    * If this is the route chosen, I suggest adding something like this to `prov/verbs/configure.m4`, and then using `#if VERBS_HAVE_XRC` in C code:
```patch
index 326688dfe..0ae0d9c3e 100644
--- a/prov/verbs/configure.m4
+++ b/prov/verbs/configure.m4
@@ -65,6 +65,16 @@ AC_DEFUN([FI_VERBS_CONFIGURE],[
                           [Experimental verbs features support])],
                [])
 
+       # See if we have XRC support
+       VERBS_HAVE_XRC=0
+       AS_IF([test $verbs_ibverbs_happy -eq 1],[
+               AC_CHECK_DECL([IBV_QPT_XRC_SEND],
+                       [VERBS_HAVE_XRC=1],[],
+                       [#include <infiniband/verbs.h>])
+               ])
+       AC_DEFINE_UNQUOTED([VERBS_HAVE_XRC],[$VERBS_HAVE_XRC],
+               [Whether infiniband/verbs.h has XRC support or not])
+
        # Technically, verbs_ibverbs_CPPFLAGS and
        # verbs_rdmacm_CPPFLAGS could be different, but it is highly
        # unlikely that they ever will be.  So only list
```
2. Require XRC support for the verbs provider to compile.
    * If this is the case, it would be straightforward to modify the above-suggested patch to disable the verbs provider if XRC support is not found.

### PR DESCRIPTION
**Pull request by jswaro**
RHEL runs an old version of libibverbs that isn't supported
with the current version of the verbs provider. This commit
introduces several defines and macros to simulate the existence
of an updated libibverbs and header files and relies on the
underlying libraries to provide the appropriate errors when
necessary.

Signed-off-by: James Swaro <jswaro@cray.com>

closes #4658

### CODE REVIEW

**Comment by jswaro** [comment]
Tested with Ubuntu Trusty using stock libibverbs. Stock libibverbs is old enough that it was failing the compilation before I made the changes to Travis. The verbs provider can now build on trusty. 

This PR adds any necessary defines, stubs out some functions and allows the verbs provider to build on older systems. We can expect that the verbs provider on a RHEL system will not display the XRC provider because of the check made in the getinfo call against the FI_PROTO and VERBS_HAVE_XRC.

**Comment by jsquyres** [comment]
FWIW, this compiles fine on RHEL 6 / old libibverbs.

**Comment by jswaro** [comment]
@jsquyres Thanks for verifying that. I appreciate it.

**Comment by jswaro** [comment]
@swelch I've updated a few files to have a /* VERBS_HAVE_XRC */ with the #else and #endifs. Just a heads up since the PR was updated. 

Those should be the last of my modifications unless someone has something they'd like me to change.

File: prov/verbs/src/verbs_rma.c [hunk 1]
```diff
@@ -444,7 +444,9 @@ fi_ibv_xrc_rma_write_fast(struct fid_ep *ep_fid, const void *buf,
 
 	ep->base_ep.wrs->rma_wr.wr.rdma.remote_addr = addr;
 	ep->base_ep.wrs->rma_wr.wr.rdma.rkey = (uint32_t) key;
+#if VERBS_HAVE_XRC
 	ep->base_ep.wrs->rma_wr.qp_type.xrc.remote_srqn = ep->peer_srqn;
+#endif /* VERBS_HAVE_XRC */
```
Comment (shefty) [inline prov/verbs/src/verbs_rma.c]: Maybe FI_IBV_SET_REMOTE_SRQN should be more generic to handle this case as well.

File: prov/verbs/src/verbs_rma.c [hunk 2]
```diff
@@ -483,7 +485,9 @@ fi_ibv_msg_xrc_ep_rma_inject_writedata_fast(struct fid_ep *ep_fid,
 						base_ep.util_ep.ep_fid);
 	ep->base_ep.wrs->rma_wr.wr.rdma.remote_addr = addr;
 	ep->base_ep.wrs->rma_wr.wr.rdma.rkey = (uint32_t) key;
+#if VERBS_HAVE_XRC
 	ep->base_ep.wrs->rma_wr.qp_type.xrc.remote_srqn = ep->peer_srqn;
+#endif /* VERBS_HAVE_XRC */
```
Comment (shefty) [inline prov/verbs/src/verbs_rma.c]: and here

File: prov/verbs/src/verbs_rma.c (hunk 1 above)
Comment (jswaro) [reply prov/verbs/src/verbs_rma.c]: Modified the macro to take a variable as an argument. I've also moved the assignment outside of the creation/assignment of the work request so that the macro can be generalized.

File: prov/verbs/src/verbs_rma.c (hunk 2 above)
Comment (jswaro) [reply prov/verbs/src/verbs_rma.c]: See previous

**Comment by jswaro** [comment]
I've updated the PR to reflect the requested changes.

**Comment by jswaro** [comment]
@shefty Any clues from the Intel CI failure?

**Comment by aingerson** [comment]
@jswaro Intel CI seems to be failing the rpm build. It's complaining that it can't find the new header you added. I'm no expert on building/the outdated verbs issues but I'm guessing that you might have to add it to the Makefile?

**Comment by jswaro** [comment]
@aingerson I'm assuming it is using the RPM build script in contrib? I'll test locally.

**Comment by jswaro** [comment]
I've updated and rebuilt the RPMs locally. Seems to work fine.

**Comment by aingerson** [comment]
It's still running all the tests, but that fixed the rpm build. Thanks!
