### PR TITLE
prov/shm: enable multiple GPU iface/device support

### LINKED ISSUE #6639: prov/shm: Request to handle iov's with mixed FI_HMEM_SYSTEM and FI_HMEM_CUDA
We just noticed the multiple iov with mixed host memory and cuda memory will cause shm provider to crash.

Specifically, we want to send 2 iov. The first one is on host memory, the second one is on cuda memory. The memory type is specified correctly in the descriptors we passed to `fi_sendmsg`.

We found such a send will cause shm provider to crash.

From reading the shm source code, I can see the code was written under the assumption that multiple IOV will have the same memory type. For example in function `smr_get_mr_hmem_iface`, the memory type was obtained from the first descriptor. Also in `smr_tx_entry`, memory type is specified by an integer `iface`.

This feature is important for EFA because EFA provider uses shm provider to support communication on same host, and it will use mixed memory to support cuda memory. For small cuda messages (<4k), EFA will send 2 iov via shm, the first one is on host memory, which contains header. The second one would be application's buffer on gpu memory.

### PR DESCRIPTION
**Pull request by aingerson**
Fixes #6639

### CODE REVIEW

**Comment by wenduwan** [comment]
I am seeing `osu_latency -d cuda D H` segfault (`osu_latency -d cuda H D` looks ok so far)
Back trace:
```
#0  0x00007ff4bec24ca0 in raise () from /lib64/libc.so.6
#1  0x00007ff4bec26148 in abort () from /lib64/libc.so.6
#2  0x00007ff4bec1da4a in __assert_fail_base () from /lib64/libc.so.6
#3  0x00007ff4bec1dac2 in __assert_fail () from /lib64/libc.so.6
#4  0x00007ff4bd898285 in smr_progress_ipc (cmd=0x7ff4739fcaa0, mr=0x7ffcc2e30580, iov=0x7ffcc2e305a0, iov_count=1, total_len=0x7ffcc2e30550, ep=0x2e55990, err=0) at prov/shm/src/smr_progress.c:507
#5  0x00007ff4bd899b4d in smr_progress_cmd_rma (ep=0x2e55990, cmd=0x7ff4739fcaa0) at prov/shm/src/smr_progress.c:913
#6  0x00007ff4bd89a539 in smr_progress_cmd (ep=0x2e55990) at prov/shm/src/smr_progress.c:1040
#7  0x00007ff4bd89ab95 in smr_ep_progress (util_ep=0x2e55990) at prov/shm/src/smr_progress.c:1143
#8  0x00007ff4bd7c9b4b in ofi_cq_progress (cq=0x2e55da0) at prov/util/src/util_cq.c:546
#9  0x00007ff4bd7c8e2f in ofi_cq_readfrom (cq_fid=0x2e55da0, buf=0x7ffcc2e307a0, count=1, src_addr=0x7ffcc2e30780) at prov/util/src/util_cq.c:260
#10 0x00007ff4bd82d2f8 in fi_cq_readfrom (cq=0x2e55da0, buf=0x7ffcc2e307a0, count=1, src_addr=0x7ffcc2e30780) at ./include/rdma/fi_eq.h:400
#11 0x00007ff4bd832871 in rdm_ep_poll_shm_cq (ep=0x2e547e0, cqe_to_process=50) at prov/efa/src/rdm/rxr_ep.c:1753
#12 0x00007ff4bd832c8e in rxr_ep_progress_internal (ep=0x2e547e0) at prov/efa/src/rdm/rxr_ep.c:1830
#13 0x00007ff4bd833737 in rxr_ep_progress (util_ep=0x2e547e0) at prov/efa/src/rdm/rxr_ep.c:2078
#14 0x00007ff4bd7c9b4b in ofi_cq_progress (cq=0x2e57550) at prov/util/src/util_cq.c:546
#15 0x00007ff4bd7c8e2f in ofi_cq_readfrom (cq_fid=0x2e57550, buf=0x7ff4c1d13d30, count=100, src_addr=0x0) at prov/util/src/util_cq.c:260
#16 0x00007ff4bd7c7985 in fi_cq_readfrom (cq=0x2e57550, buf=0x7ff4c1d13d30, count=100, src_addr=0x0) at ./include/rdma/fi_eq.h:400
#17 0x00007ff4bd7c91d1 in ofi_cq_read (cq_fid=0x2e57550, buf=0x7ff4c1d13d30, count=100) at prov/util/src/util_cq.c:313
#18 0x00007ff4bfc68481 in ompi_mtl_ofi_send_true () from /home/ec2-user/ompi/install/lib/libmpi.so.80
#19 0x00007ff4bfd14a07 in mca_pml_cm_send () from /home/ec2-user/ompi/install/lib/libmpi.so.80
#20 0x00007ff4bfb623fa in PMPI_Send () from /home/ec2-user/ompi/install/lib/libmpi.so.80
#21 0x0000000000402352 in main (argc=<optimized out>, argv=<optimized out>) at osu_latency.c:170
```
Rings any bell?

**Comment by wenduwan** [comment]
More dump if I do `-d cuda D D`
```
#0  0x00007f0be0a2ff4f in cuda_gdrcopy_impl (handle=7016996763797347249, devptr=0x7f0bb3400000, hostptr=0x7f0bb3c00000, len=8192, dir=GDRCOPY_FROM_DEVICE) at src/hmem_cuda_gdrcopy.c:265
#1  0x00007f0be0a30085 in cuda_gdrcopy_from_dev (handle=7016996763797347249, hostptr=0x7f0bb3c00000, devptr=0x7f0bb3400000, len=8192) at src/hmem_cuda_gdrcopy.c:291
#2  0x00007f0be0a2dbbf in cuda_copy_from_dev (device=7016996763797347249, dst=0x7f0bb3c00000, src=0x7f0bb3400000, size=8192) at src/hmem_cuda.c:262
#3  0x00007f0be0a2c6d0 in ofi_copy_from_hmem (iface=FI_HMEM_CUDA, device=7016996763797347249, dest=0x7f0bb3c00000, src=0x7f0bb3400000, size=8192) at ./include/ofi_hmem.h:376
#4  0x00007f0be0a2caca in ofi_copy_hmem_iov_buf (hmem_iface=FI_HMEM_CUDA, device=7016996763797347249, hmem_iov=0x7ffe2ee0a320, hmem_iov_count=1, hmem_iov_offset=0, buf=0x7f0bb3c00000, size=8192, dir=0) at src/hmem.c:281
#5  0x00007f0be0a2cc38 in ofi_copy_from_hmem_iov (dest=0x7f0bb3c00000, size=8192, hmem_iface=FI_HMEM_CUDA, device=7016996763797347249, hmem_iov=0x7ffe2ee0a320, hmem_iov_count=1, hmem_iov_offset=0) at src/hmem.c:329
#6  0x00007f0be0b3334a in smr_progress_ipc (cmd=0x7f0b9cc599a0, mr=0x7ffe2ee0a300, iov=0x7ffe2ee0a320, iov_count=1, total_len=0x7ffe2ee0a2d0, ep=0x146d990, err=0) at prov/shm/src/smr_progress.c:531
#7  0x00007f0be0b34ae2 in smr_progress_cmd_rma (ep=0x146d990, cmd=0x7f0b9cc599a0) at prov/shm/src/smr_progress.c:913
#8  0x00007f0be0b354ce in smr_progress_cmd (ep=0x146d990) at prov/shm/src/smr_progress.c:1040
#9  0x00007f0be0b35b2a in smr_ep_progress (util_ep=0x146d990) at prov/shm/src/smr_progress.c:1143
#10 0x00007f0be0a64b4b in ofi_cq_progress (cq=0x146dda0) at prov/util/src/util_cq.c:546
#11 0x00007f0be0a63e2f in ofi_cq_readfrom (cq_fid=0x146dda0, buf=0x7ffe2ee0a520, count=1, src_addr=0x7ffe2ee0a500) at prov/util/src/util_cq.c:260
#12 0x00007f0be0ac82f8 in fi_cq_readfrom (cq=0x146dda0, buf=0x7ffe2ee0a520, count=1, src_addr=0x7ffe2ee0a500) at ./include/rdma/fi_eq.h:400
#13 0x00007f0be0acd871 in rdm_ep_poll_shm_cq (ep=0x146c7e0, cqe_to_process=50) at prov/efa/src/rdm/rxr_ep.c:1753
#14 0x00007f0be0acdc8e in rxr_ep_progress_internal (ep=0x146c7e0) at prov/efa/src/rdm/rxr_ep.c:1830
#15 0x00007f0be0ace737 in rxr_ep_progress (util_ep=0x146c7e0) at prov/efa/src/rdm/rxr_ep.c:2078
#16 0x00007f0be0a64b4b in ofi_cq_progress (cq=0x146f550) at prov/util/src/util_cq.c:546
#17 0x00007f0be0a63e2f in ofi_cq_readfrom (cq_fid=0x146f550, buf=0x7f0be4faed30, count=100, src_addr=0x0) at prov/util/src/util_cq.c:260
#18 0x00007f0be0a62985 in fi_cq_readfrom (cq=0x146f550, buf=0x7f0be4faed30, count=100, src_addr=0x0) at ./include/rdma/fi_eq.h:400
#19 0x00007f0be0a641d1 in ofi_cq_read (cq_fid=0x146f550, buf=0x7f0be4faed30, count=100) at prov/util/src/util_cq.c:313
#20 0x00007f0be2f03481 in ompi_mtl_ofi_send_true () from /home/ec2-user/ompi/install/lib/libmpi.so.80
#21 0x00007f0be2fafa07 in mca_pml_cm_send () from /home/ec2-user/ompi/install/lib/libmpi.so.80
#22 0x00007f0be2dfd3fa in PMPI_Send () from /home/ec2-user/ompi/install/lib/libmpi.so.80
#23 0x000000000040226a in main (argc=<optimized out>, argv=<optimized out>) at osu_latency.c:147
```

**Comment by wenduwan** [comment]
Compiler warnings (if it helps)
```
In file included from ./include/ofi_mr.h:51:0,
                 from ./include/ofi_util.h:58,
                 from prov/util/src/util_mr_cache.c:39:
prov/util/src/util_mr_cache.c: In function 'ofi_copy_mr_iov':
./include/ofi_hmem.h:376:9: warning: 'hmem_device' may be used uninitialized in this function [-Wmaybe-uninitialized]
  return hmem_ops[iface].copy_from_hmem(device, dest, src, size);
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
prov/util/src/util_mr_cache.c:575:23: note: 'hmem_device' was declared here
  uint64_t hmem_iface, hmem_device;
                       ^~~~~~~~~~~
  CC       prov/mrail/src/src_libfabric_la-mrail_domain.lo
  CC       prov/mrail/src/src_libfabric_la-mrail_cq.lo
  CC       prov/mrail/src/src_libfabric_la-mrail_ep.lo
  CC       prov/mrail/src/src_libfabric_la-mrail_av.lo
  CC       prov/mrail/src/src_libfabric_la-mrail_rma.lo
  CC       prov/rxd/src/src_libfabric_la-rxd_attr.lo
  CC       prov/rxd/src/src_libfabric_la-rxd_init.lo
  CC       prov/rxd/src/src_libfabric_la-rxd_fabric.lo
  CC       prov/rxd/src/src_libfabric_la-rxd_domain.lo
  CC       prov/rxd/src/src_libfabric_la-rxd_av.lo
  CC       prov/rxd/src/src_libfabric_la-rxd_cq.lo
  CC       prov/rxd/src/src_libfabric_la-rxd_cntr.lo
  CC       prov/rxd/src/src_libfabric_la-rxd_ep.lo
  CC       prov/rxd/src/src_libfabric_la-rxd_msg.lo
  CC       prov/rxd/src/src_libfabric_la-rxd_tagged.lo
  CC       prov/rxd/src/src_libfabric_la-rxd_rma.lo
  CC       prov/rxd/src/src_libfabric_la-rxd_atomic.lo
  CC       prov/shm/src/src_libfabric_la-smr_attr.lo
  CC       prov/shm/src/src_libfabric_la-smr_cq.lo
  CC       prov/shm/src/src_libfabric_la-smr_domain.lo
  CC       prov/shm/src/src_libfabric_la-smr_comp.lo
  CC       prov/shm/src/src_libfabric_la-smr_progress.lo
  CC       prov/shm/src/src_libfabric_la-smr_cntr.lo
  CC       prov/shm/src/src_libfabric_la-smr_msg.lo
  CC       prov/shm/src/src_libfabric_la-smr_rma.lo
  CC       prov/shm/src/src_libfabric_la-smr_atomic.lo
  CC       prov/shm/src/src_libfabric_la-smr_ep.lo
  CC       prov/shm/src/src_libfabric_la-smr_fabric.lo
  CC       prov/shm/src/src_libfabric_la-smr_init.lo
  CC       prov/shm/src/src_libfabric_la-smr_av.lo
  CC       prov/shm/src/src_libfabric_la-smr_dsa.lo
  CC       prov/tcp/src/src_libfabric_la-tcpx_fabric.lo
  CC       prov/tcp/src/src_libfabric_la-tcpx_attr.lo
  CC       prov/tcp/src/src_libfabric_la-tcpx_conn_mgr.lo
  CC       prov/tcp/src/src_libfabric_la-tcpx_domain.lo
  CC       prov/tcp/src/src_libfabric_la-tcpx_rma.lo
  CC       prov/tcp/src/src_libfabric_la-tcpx_msg.lo
  CC       prov/tcp/src/src_libfabric_la-tcpx_ep.lo
  CC       prov/tcp/src/src_libfabric_la-tcpx_shared_ctx.lo
  CC       prov/tcp/src/src_libfabric_la-tcpx_cq.lo
  CC       prov/tcp/src/src_libfabric_la-tcpx_eq.lo
  CC       prov/tcp/src/src_libfabric_la-tcpx_init.lo
  CC       prov/tcp/src/src_libfabric_la-tcpx_progress.lo
  CC       prov/net/src/src_libfabric_la-xnet_fabric.lo
  CC       prov/net/src/src_libfabric_la-xnet_attr.lo
  CC       prov/net/src/src_libfabric_la-xnet_cm.lo
  CC       prov/net/src/src_libfabric_la-xnet_rdm_cm.lo
  CC       prov/net/src/src_libfabric_la-xnet_domain.lo
  CC       prov/net/src/src_libfabric_la-xnet_rma.lo
  CC       prov/net/src/src_libfabric_la-xnet_ep.lo
  CC       prov/net/src/src_libfabric_la-xnet_msg.lo
  CC       prov/net/src/src_libfabric_la-xnet_rdm.lo
  CC       prov/net/src/src_libfabric_la-xnet_pep.lo
  CC       prov/net/src/src_libfabric_la-xnet_srx.lo
  CC       prov/net/src/src_libfabric_la-xnet_cq.lo
  CC       prov/net/src/src_libfabric_la-xnet_eq.lo
  CC       prov/net/src/src_libfabric_la-xnet_init.lo
  CC       prov/net/src/src_libfabric_la-xnet_progress.lo
  CC       prov/hook/perf/src/src_libfabric_la-hook_perf.lo
  CC       prov/hook/trace/src/src_libfabric_la-hook_trace.lo
  CC       prov/hook/hook_debug/src/src_libfabric_la-hook_debug.lo
  CC       prov/hook/hook_hmem/src/src_libfabric_la-hook_hmem.lo
  CC       prov/hook/dmabuf_peer_mem/src/src_libfabric_la-hook_dmabuf_peer_mem.lo
  CC       util/info.o
prov/shm/src/smr_rma.c: In function 'smr_generic_rma':
prov/shm/src/smr_rma.c:110:7: warning: 'use_ipc' may be used uninitialized in this function [-Wmaybe-uninitialized]
  bool use_ipc;
```

File: prov/util/src/util_mr_cache.c [hunk 1]
```diff
@@ -566,3 +566,67 @@ int ofi_open_mr_cache(uint32_t version, void *attr, size_t attr_len,
 	*fid = cache_fid;
 	return 0;
 }
+
+static ssize_t ofi_copy_mr_iov(struct ofi_mr **mr, const struct iovec *iov,
+		size_t iov_count, uint64_t iov_offset, void *buf,
+		size_t size, int dir)
```
Comment (shefty) [inline prov/util/src/util_mr_cache.c:572]: This function looks like it belongs better in hmem.c than the mr_cache

File: prov/util/src/util_mr_cache.c [hunk 2]
```diff
@@ -566,3 +566,67 @@ int ofi_open_mr_cache(uint32_t version, void *attr, size_t attr_len,
...
+		else
+			ret = ofi_copy_from_hmem(hmem_iface, hmem_device,
+						(char *)buf + done, hmem_buf,
+						len);
+		if (ret)
+			return ret;
+
+		size -= len;
+		done += len;
+	}
```
Comment (shefty) [inline prov/util/src/util_mr_cache.c:614]: This duplicates most of ofi_copy_hmem_iov_buf().  Can we isolate the common code?

File: prov/util/src/util_mr_cache.c (hunk 1 above)
Comment (aingerson) [reply prov/util/src/util_mr_cache.c:572]: I went back and forth but put it in the MR cache because adding it the hmem would require including ofi_mr.h which requires ofi_hmem.h for the handle size so there's a circular dependency. Do you want me to try to move it?

Comment (shefty) [reply prov/util/src/util_mr_cache.c:572]: I think it makes more sense in hmem.c.  Looking at just the first commit, can you just include ofi_mr.h instead of ofi_hmem.h?  You just need struct ofi_mr, right?

**Comment by aingerson** [comment]
@wenduwan Thanks for the backtraces and compiler warnings. I know where all of these are coming from. I will push a fix shortly when I address Sean's comments as well.

File: prov/util/src/util_mr_cache.c (hunk 1 above)
Comment (aingerson) [reply prov/util/src/util_mr_cache.c:572]: I tried that but I get a lot of these
```
In file included from ./include/ofi_mr.h:51,                                                                           [130/1171]
                 from ./include/ofi_util.h:58,                                                                                   
                 from src/fabric.c:47:                          
./include/ofi_hmem.h:380:62: warning: 'struct ofi_mr' declared inside parameter list will not be visible outside of this definiti
on or declaration               
 ssize_t ofi_copy_from_mr_iov(void *dest, size_t size, struct ofi_mr **mr,                                                       
                                                              ^~~~~~                                                             
./include/ofi_hmem.h:383:35: warning: 'struct ofi_mr' declared inside parameter list will not be visible outside of this definiti
on or declaration               
 ssize_t ofi_copy_to_mr_iov(struct ofi_mr **mr, const struct iovec *iov,                                                         
```

Comment (shefty) [reply prov/util/src/util_mr_cache.c:572]: Sorry, my brain wasn't working.  I meant move struct ofi_mr into ofi_hmem.h.  ofi_mr.h already includes ofi_hmem.h

Comment (aingerson) [reply prov/util/src/util_mr_cache.c:572]: You'd rather move ofi_mr into ofi_hmem instead of have the mr copy function in the MR code? (That came out sarcastic but I'm just clarifying)

Comment (shefty) [reply prov/util/src/util_mr_cache.c:572]: Between those 2 options, yes.  But maybe we need to back up.  A better option would leave struct ofi_mr in ofi_mr.h, put the new calls in ofi_hmem.h, and have ofi_hmem.h include ofi_mr.h.  To do that we need to figure out why ofi_mr.h includes ofi_hmem.h.

At a quick glance, I think it's only to pick up the definition of MAX_IPC_HANDLE_SIZE.  Does moving that info ofi.h or another common file remove the current dependency from ofi_mr.h on ofi_hmem.h?  I think it does.

Comment (aingerson) [reply prov/util/src/util_mr_cache.c:572]: With some extra modifications, yes, I can make that work. I had to move this to make it work:
```
#define MAX_IPC_HANDLE_SIZE	64

/*
 * This structure is part of the
 * the shm communication protocol
 * defined in ofi_shm.h.
 * Please make sure the SMR_VERSION are
 * bumped and SMR_CMD_SIZE are large
 * enough, for any changes in this
 * structure.
 */
struct ipc_info {
	uint64_t	iface;
	uint64_t	base_addr;
	uint64_t	base_length;
	uint64_t	device;
	uint64_t	offset;
	uint8_t		ipc_handle[MAX_IPC_HANDLE_SIZE];
};
```

Do you think ofi.h is the best place for it or would you like it somewhere else?

Comment (shefty) [reply prov/util/src/util_mr_cache.c:572]: Why did you need to move ipc_info?  I don't know that ofi.h is the best place, but looks like it without introducing a new header file.

Comment (j-xiong) [reply prov/util/src/util_mr_cache.c:572]: I agree moving `#define MAX_IPC_HANDLE_SIZE	64` to ofi.h and adding `#include <ofi.h>` to ofi_hmem.h is the simplest solution.

**Comment by aingerson** [comment]
@shefty @wenduwan Updated

File: src/hmem.c [hunk 3]
```diff
@@ -212,18 +212,8 @@ ofi_async_copy_hmem_iov_buf(enum fi_hmem_iface hmem_iface, uint64_t device,
...
-		if (hmem_iov_offset > len) {
-			hmem_iov_offset -= len;
-			continue;
-		}
-
-		hmem_buf = (char *)hmem_iov[i].iov_base + hmem_iov_offset;
-		len -= hmem_iov_offset;
-		hmem_iov_offset = 0;
-
-		len = MIN(len, size);
```
Comment (shijin-aws) [inline src/hmem.c:226]: I understand this is a refactor. But why do we used to set `hmem_iov_offset` as 0 considering it is not used anymore in this function?

Comment (shijin-aws) [reply src/hmem.c:226]: never mind. I get it now. It is in a loop over the iov so it is still used.

**Review by shijin-aws — APPROVED** [review]

**Comment by wenduwan** [comment]
@aingerson Thanks for the update. The compiler warnings are gone. We need to make a few adjustments in prov/efa to test it out with mixed iovec types. I have an idea of the needed change which is mainly around the usage of 
```c
struct ofi_mr {
	struct fid_mr mr_fid;
	struct util_domain *domain;
	uint64_t key;
	uint64_t flags;
	enum fi_hmem_iface iface;
	uint64_t device;
};
```
in `prov/shm/src/smr_msg.c`, namely
```c
	/* Do not inline/inject if IPC is available so device to device
	 * transfer may occur if possible. */
	if (iov_count == 1 && desc && desc[0]) {
		smr_desc = (struct ofi_mr *) *desc;
		use_ipc = ofi_hmem_is_ipc_enabled(((struct ofi_mr *) *desc)->iface) &&
				smr_desc->flags & FI_HMEM_DEVICE_ONLY &&
				!(op_flags & FI_INJECT);
	}
	proto = smr_select_proto(use_ipc, smr_cma_enabled(ep, peer_smr), op,
				 total_len, op_flags);

	ret = smr_proto_ops[proto](ep, peer_smr, id, peer_id, op, tag, data, op_flags,
				   (struct ofi_mr **)desc, iov, iov_count, total_len,
				   context);
```
Inside prov/efa we do not use `struct ofi_mr` directly, but instead
```c
struct efa_mr_peer {
	enum fi_hmem_iface      iface;
	union {
		uint64_t        reserved;
		/* this field is gdrcopy handle when gdrcopy is enabled,
		 * otherwise it is cuda device id.
		 */
		uint64_t        cuda;
		int             neuron;
		int             synapseai;
	} device;
};

struct efa_mr {
	struct fid_mr		mr_fid;
	struct ibv_mr		*ibv_mr;
	struct efa_domain	*domain;
	/* Used only in MR cache */
	struct ofi_mr_entry	*entry;
	/* Used only in rdm */
	struct fid_mr		*shm_mr;
	struct efa_mr_peer	peer;
	bool			inserted_to_mr_map;
};
```
I will sync with the EFA team about the next steps to finish testing on our side.

**Comment by wenduwan** [comment]
Aside from that, cuda to host is still seeing segfault
```
#0  0x00007f6a0fee126f in cuda_gdrcopy_impl (handle=541996365, devptr=0x7f69ba1ff000, hostptr=0x7f69e3400000, len=32768, dir=GDRCOPY_FROM_DEVICE) at src/hmem_cuda_gdrcopy.c:265
#1  0x00007f6a0fee13a5 in cuda_gdrcopy_from_dev (handle=541996365, hostptr=0x7f69e3400000, devptr=0x7f69ba1ff000, len=32768) at src/hmem_cuda_gdrcopy.c:291
#2  0x00007f6a0fedeedf in cuda_copy_from_dev (device=541996365, dst=0x7f69e3400000, src=0x7f69ba1ff000, size=32768) at src/hmem_cuda.c:262
#3  0x00007f6a0fedd77a in ofi_copy_from_hmem (iface=FI_HMEM_CUDA, device=541996365, dest=0x7f69e3400000, src=0x7f69ba1ff000, size=32768) at ./include/ofi_hmem.h:358
#4  0x00007f6a0feddb99 in ofi_copy_hmem_iov_buf (hmem_iface=FI_HMEM_CUDA, device=541996365, hmem_iov=0x7ffee44ce820, hmem_iov_count=1, hmem_iov_offset=0, buf=0x7f69e3400000, size=0, dir=0) at src/hmem.c:260
#5  0x00007f6a0feddf58 in ofi_copy_from_hmem_iov (dest=0x7f69e3400000, size=32768, hmem_iface=FI_HMEM_CUDA, device=541996365, hmem_iov=0x7ffee44ce820, hmem_iov_count=1, hmem_iov_offset=0) at src/hmem.c:361
#6  0x00007f6a0ffe43cc in smr_progress_ipc (cmd=0x7f69cc29a8a0, mr=0x7ffee44ce800, iov=0x7ffee44ce820, iov_count=1, total_len=0x7ffee44ce7d0, ep=0x23b19d0, err=0) at prov/shm/src/smr_progress.c:529
#7  0x00007f6a0ffe5b64 in smr_progress_cmd_rma (ep=0x23b19d0, cmd=0x7f69cc29a8a0) at prov/shm/src/smr_progress.c:911
#8  0x00007f6a0ffe6550 in smr_progress_cmd (ep=0x23b19d0) at prov/shm/src/smr_progress.c:1038
#9  0x00007f6a0ffe6bac in smr_ep_progress (util_ep=0x23b19d0) at prov/shm/src/smr_progress.c:1141
#10 0x00007f6a0ff15f4b in ofi_cq_progress (cq=0x23b1de0) at prov/util/src/util_cq.c:546
#11 0x00007f6a0ff1522f in ofi_cq_readfrom (cq_fid=0x23b1de0, buf=0x7ffee44cea20, count=1, src_addr=0x7ffee44cea00) at prov/util/src/util_cq.c:260
#12 0x00007f6a0ff793e8 in fi_cq_readfrom (cq=0x23b1de0, buf=0x7ffee44cea20, count=1, src_addr=0x7ffee44cea00) at ./include/rdma/fi_eq.h:400
#13 0x00007f6a0ff7e961 in rdm_ep_poll_shm_cq (ep=0x23b0820, cqe_to_process=50) at prov/efa/src/rdm/rxr_ep.c:1753
#14 0x00007f6a0ff7ed7e in rxr_ep_progress_internal (ep=0x23b0820) at prov/efa/src/rdm/rxr_ep.c:1830
#15 0x00007f6a0ff7f827 in rxr_ep_progress (util_ep=0x23b0820) at prov/efa/src/rdm/rxr_ep.c:2078
#16 0x00007f6a0ff15f4b in ofi_cq_progress (cq=0x23b3590) at prov/util/src/util_cq.c:546
#17 0x00007f6a0ff1522f in ofi_cq_readfrom (cq_fid=0x23b3590, buf=0x7f6a1445fd30, count=100, src_addr=0x0) at prov/util/src/util_cq.c:260
#18 0x00007f6a0ff13d85 in fi_cq_readfrom (cq=0x23b3590, buf=0x7f6a1445fd30, count=100, src_addr=0x0) at ./include/rdma/fi_eq.h:400
#19 0x00007f6a0ff155d1 in ofi_cq_read (cq_fid=0x23b3590, buf=0x7f6a1445fd30, count=100) at prov/util/src/util_cq.c:313
#20 0x00007f6a123b4481 in ompi_mtl_ofi_send_true () from /home/ec2-user/ompi/install/lib/libmpi.so.80
#21 0x00007f6a12460a07 in mca_pml_cm_send () from /home/ec2-user/ompi/install/lib/libmpi.so.80
#22 0x00007f6a122ae3fa in PMPI_Send () from /home/ec2-user/ompi/install/lib/libmpi.so.80
#23 0x0000000000402352 in main (argc=<optimized out>, argv=<optimized out>) at osu_latency.c:170
```

**Comment by shijin-aws** [comment]
> Aside from that, cuda to host is still seeing segfault
> 
> ```
> #0  0x00007f6a0fee126f in cuda_gdrcopy_impl (handle=541996365, devptr=0x7f69ba1ff000, hostptr=0x7f69e3400000, len=32768, dir=GDRCOPY_FROM_DEVICE) at src/hmem_cuda_gdrcopy.c:265
> #1  0x00007f6a0fee13a5 in cuda_gdrcopy_from_dev (handle=541996365, hostptr=0x7f69e3400000, devptr=0x7f69ba1ff000, len=32768) at src/hmem_cuda_gdrcopy.c:291
> #2  0x00007f6a0fedeedf in cuda_copy_from_dev (device=541996365, dst=0x7f69e3400000, src=0x7f69ba1ff000, size=32768) at src/hmem_cuda.c:262
> #3  0x00007f6a0fedd77a in ofi_copy_from_hmem (iface=FI_HMEM_CUDA, device=541996365, dest=0x7f69e3400000, src=0x7f69ba1ff000, size=32768) at ./include/ofi_hmem.h:358
> #4  0x00007f6a0feddb99 in ofi_copy_hmem_iov_buf (hmem_iface=FI_HMEM_CUDA, device=541996365, hmem_iov=0x7ffee44ce820, hmem_iov_count=1, hmem_iov_offset=0, buf=0x7f69e3400000, size=0, dir=0) at src/hmem.c:260
> #5  0x00007f6a0feddf58 in ofi_copy_from_hmem_iov (dest=0x7f69e3400000, size=32768, hmem_iface=FI_HMEM_CUDA, device=541996365, hmem_iov=0x7ffee44ce820, hmem_iov_count=1, hmem_iov_offset=0) at src/hmem.c:361
> #6  0x00007f6a0ffe43cc in smr_progress_ipc (cmd=0x7f69cc29a8a0, mr=0x7ffee44ce800, iov=0x7ffee44ce820, iov_count=1, total_len=0x7ffee44ce7d0, ep=0x23b19d0, err=0) at prov/shm/src/smr_progress.c:529
> #7  0x00007f6a0ffe5b64 in smr_progress_cmd_rma (ep=0x23b19d0, cmd=0x7f69cc29a8a0) at prov/shm/src/smr_progress.c:911
> #8  0x00007f6a0ffe6550 in smr_progress_cmd (ep=0x23b19d0) at prov/shm/src/smr_progress.c:1038
> #9  0x00007f6a0ffe6bac in smr_ep_progress (util_ep=0x23b19d0) at prov/shm/src/smr_progress.c:1141
> #10 0x00007f6a0ff15f4b in ofi_cq_progress (cq=0x23b1de0) at prov/util/src/util_cq.c:546
> #11 0x00007f6a0ff1522f in ofi_cq_readfrom (cq_fid=0x23b1de0, buf=0x7ffee44cea20, count=1, src_addr=0x7ffee44cea00) at prov/util/src/util_cq.c:260
> #12 0x00007f6a0ff793e8 in fi_cq_readfrom (cq=0x23b1de0, buf=0x7ffee44cea20, count=1, src_addr=0x7ffee44cea00) at ./include/rdma/fi_eq.h:400
> #13 0x00007f6a0ff7e961 in rdm_ep_poll_shm_cq (ep=0x23b0820, cqe_to_process=50) at prov/efa/src/rdm/rxr_ep.c:1753
> #14 0x00007f6a0ff7ed7e in rxr_ep_progress_internal (ep=0x23b0820) at prov/efa/src/rdm/rxr_ep.c:1830
> #15 0x00007f6a0ff7f827 in rxr_ep_progress (util_ep=0x23b0820) at prov/efa/src/rdm/rxr_ep.c:2078
> #16 0x00007f6a0ff15f4b in ofi_cq_progress (cq=0x23b3590) at prov/util/src/util_cq.c:546
> #17 0x00007f6a0ff1522f in ofi_cq_readfrom (cq_fid=0x23b3590, buf=0x7f6a1445fd30, count=100, src_addr=0x0) at prov/util/src/util_cq.c:260
> #18 0x00007f6a0ff13d85 in fi_cq_readfrom (cq=0x23b3590, buf=0x7f6a1445fd30, count=100, src_addr=0x0) at ./include/rdma/fi_eq.h:400
> #19 0x00007f6a0ff155d1 in ofi_cq_read (cq_fid=0x23b3590, buf=0x7f6a1445fd30, count=100) at prov/util/src/util_cq.c:313
> #20 0x00007f6a123b4481 in ompi_mtl_ofi_send_true () from /home/ec2-user/ompi/install/lib/libmpi.so.80
> #21 0x00007f6a12460a07 in mca_pml_cm_send () from /home/ec2-user/ompi/install/lib/libmpi.so.80
> #22 0x00007f6a122ae3fa in PMPI_Send () from /home/ec2-user/ompi/install/lib/libmpi.so.80
> #23 0x0000000000402352 in main (argc=<optimized out>, argv=<optimized out>) at osu_latency.c:170
> ```

GDR copy should not be present in the ipc path. Something must be wrong

File: prov/shm/src/smr_msg.c [hunk 4]
```diff
@@ -312,22 +311,24 @@ static ssize_t smr_generic_sendmsg(struct smr_ep *ep, const struct iovec *iov,
...
 
 	/* Do not inline/inject if IPC is available so device to device
 	 * transfer may occur if possible. */
-	use_ipc = ofi_hmem_is_ipc_enabled(iface) && (iov_count == 1) &&
-		  desc && (smr_get_mr_flags(desc) & FI_HMEM_DEVICE_ONLY) &&
-		  !(op_flags & FI_INJECT);
-
-	proto = smr_select_proto(use_ipc, smr_cma_enabled(ep, peer_smr), iface,
-				 op, total_len, op_flags);
+	if (iov_count == 1 && desc && desc[0]) {
```
Comment (wenduwan) [inline prov/shm/src/smr_msg.c:320]: Could you explain what's magical about `desc[0]`?

In the current revision, if `iov_count  = 2` and `desc[1]` actually carries the cuda MR, cuda ipc won't be activated at all. Did I miss anything?

Comment (shijin-aws) [reply prov/shm/src/smr_msg.c:320]: That is the old implementation too. in order to use ipc you cannot send with multiple iovs. It is more complicated to use IPC for different ifaces.

Comment (aingerson) [reply prov/shm/src/smr_msg.c:320]: Right, multiple iovs have to take the SAR path. IPC currently does not support multiple iovs/ifaces. The biggest limitation is having to send multiple IPC handles in the command which previously could only hold one IPC handle. Recently, we doubled the command size to 256 bytes so we could theoretically hold more handles in the command. It will still get complicated though to have mixed iovs for IPC because the system memory would not have an IPC handle. We could figure out a way to send the virtual addresses to use CMA as the "IPC" method but that would still be complicated and also wouldn't cover the non-CMA cases so then we would have to take SAR. But that leads down a hole that would require a lot of modification to support... I'm not sure how worth it that is. Do you think that's something worth while to investigate from your point of view?

**Comment by aingerson** [comment]
@wenduwan In regards to the ofi_mr/efa_mr comment, it shouldn't matter that you're using different MRs. The ofi_mr desc is internal to shm. For any shm operations, you should be passing in the shm desc which will return the ofi_mr. Basically in terms of your efa_mr:
```
void *ofi_mr = fi_mr_desc(efa_mr->shm_mr);
fi_send(shm_ep, buf, len, ofi_mr, shm_addr, context);
```

File: prov/shm/src/smr_msg.c (hunk 4 above)
Comment (shijin-aws) [reply prov/shm/src/smr_msg.c:320]: @wenduwan @aingerson I do not think we really need that feature. Currently EFA provider only send msg with multiple (2) iovs to shm ep for host memory in EAGER protocol. The first iov stores additional packet headers for efa provider. The 2nd iov is the real msg iov for user buffer. This extra iov can be removed after we sending msg via shm directly in the future after onboarding peer API. 

And currently we have observed that for cuda-to-cuda latency, doing hmem copy inside efa, and use shm for pure host-to-host  has a better performance for small message sizes than making shm do IPC for cuda-to-cuda. I guess an improvement for shm in the future could be making such ipc/non-ipc switch point configurable in shm provider.

Comment (wenduwan) [reply prov/shm/src/smr_msg.c:320]: > Do you think that's something worth while to investigate from your point of view?

Thanks for both's explanation. I'm not familiar with IPC(especially inside prov/shm) and from what I'm reading, the IPC path is rather a corner case. I'm biased toward prioritizing the crash as mentioned in https://github.com/ofiwg/libfabric/issues/6639.

Comment (aingerson) [reply prov/shm/src/smr_msg.c:320]: @shijin-aws I have thought about configuring that threshold for IPC but haven't done any experimentation to determine where that would be. I'm totally open to changing it though. We can easily do that adjustment either with the use_ipc definition or inside of select_proto. Feel free to experiment with it and open a PR for the change

File: prov/shm/src/smr_progress.c [hunk 5]
```diff
@@ -536,12 +527,13 @@ static int smr_progress_ipc(struct smr_cmd *cmd, enum fi_hmem_iface iface,
...
-						       cmd->msg.data.ipc_info.iface,
-						       device, iov, iov_count, 0);
+					cmd->msg.data.ipc_info.iface,
+					cmd->msg.data.ipc_info.device, iov,
+					iov_count, 0);
 	} else {
 		hmem_copy_ret = ofi_copy_to_hmem_iov(cmd->msg.data.ipc_info.iface,
-						     device, iov, iov_count, 0,
-						     ptr, cmd->msg.hdr.size);
+					cmd->msg.data.ipc_info.device, iov,
```
Comment (wenduwan) [inline prov/shm/src/smr_progress.c:535]: As @shijin-aws correctly pointed out, `cmd->msg.data.ipc_info.device` is somehow messed up - inspected another core dump:
```
(gdb) f 6
#6  0x00007fdc40c873cc in smr_progress_ipc (cmd=0x7fdbfce0a8a0, mr=0x7ffebd0a0330, iov=0x7ffebd0a0350, iov_count=1, total_len=0x7ffebd0a0300, ep=0x2fb39d0, err=0) at prov/shm/src/smr_progress.c:529
529			hmem_copy_ret = ofi_copy_from_hmem_iov(ptr, cmd->msg.hdr.size,
(gdb) p **mr
$7 = {mr_fid = {fid = {fclass = 12, context = 0x0, ops = 0x7fdc40f50800 <ofi_mr_fi_ops>}, mem_desc = 0x3959c70, key = 9437194}, domain = 0x2fb1200, key = 9437194, flags = 70368744177664, iface = FI_HMEM_CUDA, device = 0}
(gdb) p cmd->data
There is no member named data.
(gdb) p cmd->msg
$8 = {hdr = {msg_id = 0, id = 1, op = 2, op_src = 5, op_flags = 6, size = 1, src_data = 262336, data = 0, {tag = 0, {datatype = 0 '\000', atomic_op = 0 '\000'}}}, data = {
    msg = "\001\000\000\000\000\000\000\000\000\000\200\061\311\177\000\000\000\000@\000\000\000\000\000\024\337v\034", '\000' <repeats 12 times>, "\300\267\371\001\000\000\000\000\224K\000\000\000\000\000\000\000\000@\000\000\000\000\000\000\004\000\000\000\000\000\000\035\020\000\000\000\000\000\000\070\000\000\000\000\000\000\000\262\017\320\301\341\000\000\\", '\000' <repeats 95 times>, {iov_count = 1, iov = {{iov_base = 0x7fc931800000, iov_len = 4194304}, {iov_base = 0x1c76df14, iov_len = 0}, {iov_base = 0x1f9b7c0, iov_len = 19348}, {iov_base = 0x400000, iov_len = 1024}, {iov_base = 0x101d, iov_len = 56}, {iov_base = 0x5c0000e1c1d00fb2, iov_len = 0}, {iov_base = 0x0, iov_len = 0},
        {iov_base = 0x0, iov_len = 0}, {iov_base = 0x0, iov_len = 0}, {iov_base = 0x0, iov_len = 0}, {iov_base = 0x0, iov_len = 0}}}, {buf_batch_size = 1, sar = {0, 0, 0, 12672, 32713, 0, 0, 64, 0, 0, -8428, 7286, 0, 0, 0, 0, 0, 0, -18496, 505, 0, 0, 19348, 0, 0, 0, 0, 64, 0, 0, 1024, 0, 0, 0, 4125, 0, 0, 0, 56, 0, 0, 0, 4018, -15920, 225,
        23552, 0 <repeats 18 times>}}, ipc_info = {iface = 1, base_addr = 140502095626240, base_length = 4194304, device = 477552404, offset = 0,
      ipc_handle = "\300\267\371\001\000\000\000\000\224K\000\000\000\000\000\000\000\000@\000\000\000\000\000\000\004\000\000\000\000\000\000\035\020\000\000\000\000\000\000\070\000\000\000\000\000\000\000\262\017\320\301\341\000\000\\\000\000\000\000\000\000\000"}}}
```

The unused `mr` variable contains the correct the device id in this case... The segfault disappears with this change:
```
diff --git a/prov/shm/src/smr_progress.c b/prov/shm/src/smr_progress.c
index 0cda4e53b..344e0fba5 100644
--- a/prov/shm/src/smr_progress.c
+++ b/prov/shm/src/smr_progress.c
@@ -527,9 +527,11 @@ static int smr_progress_ipc(struct smr_cmd *cmd, struct ofi_mr **mr,

        if (cmd->msg.hdr.op == ofi_op_read_req) {
                hmem_copy_ret = ofi_copy_from_hmem_iov(ptr, cmd->msg.hdr.size,
-                                       cmd->msg.data.ipc_info.iface,
-                                       cmd->msg.data.ipc_info.device, iov,
-                                       iov_count, 0);
+                                       (*mr)->iface,
+                                       (*mr)->device,
+                                       iov,
+                                       iov_count,
+                                       0);
        } else {
                hmem_copy_ret = ofi_copy_to_hmem_iov(cmd->msg.data.ipc_info.iface,
                                        cmd->msg.data.ipc_info.device, iov,
```

However I have not got to the root of the location where `cmd->msg.data.ipc_info.device` is set. Any thoughts?

Comment (wenduwan) [reply prov/shm/src/smr_progress.c:535]: ... my guess is [here](https://github.com/ofiwg/libfabric/blob/10cdccde6ceeac41eb70cb1dc4eed8f0f8704c02/prov/shm/src/smr_ep.c#L786-L787)

```c

static ssize_t smr_do_ipc(struct smr_ep *ep, struct smr_region *peer_smr, int64_t id,
			  int64_t peer_id, uint32_t op, uint64_t tag, uint64_t data,
			  uint64_t op_flags, enum fi_hmem_iface iface, uint64_t device,
		          const struct iovec *iov, size_t iov_count, size_t total_len,
		          void *context)
{
	struct smr_cmd *cmd;
	struct smr_resp *resp;
	struct smr_tx_entry *pend;
	int ret = -FI_EAGAIN;

	if (ofi_cirque_isfull(smr_resp_queue(ep->region)))
		return -FI_EAGAIN;

	cmd = ofi_cirque_next(smr_cmd_queue(peer_smr));
	resp = ofi_cirque_next(smr_resp_queue(ep->region));
	pend = ofi_freestack_pop(ep->pend_fs);

	smr_generic_format(cmd, peer_id, op, tag, data, op_flags);
	if (iface == FI_HMEM_ZE) {
		if (smr_ze_ipc_enabled(ep->region, peer_smr))
			ret = smr_format_ze_ipc(ep, id, cmd, iov, device,
					total_len, ep->region, resp, pend);
	} else {
		ret = smr_format_ipc(cmd, iov[0].iov_base, total_len, ep->region,
				     resp, iface); // Missing device
	}
...
```

Comment (shijin-aws) [reply prov/shm/src/smr_progress.c:535]: Good catch, it seems this PR removes the `device` argument from `smr_progress_*` and derive it from `cmd->msg.data.ipc_info.device`, which is actually not set in the `smr_do_ipc` procedure. Before this change, the `device` was derived from the matched rx_entry's desc so there aws no such issue.

Comment (shijin-aws) [reply prov/shm/src/smr_progress.c:535]: I think the quickest fix is to expand the `smr_format_ipc` to have `device` as an argument like `smr_format_ze_ipc` and assign it to `cmd->msg.data.ipc_info.device`. Ideally we should merge `smr_do/format/progress_ipc` with `smr_do/format/progress_ze_ipc` to remove duplication.

Comment (aingerson) [reply prov/shm/src/smr_progress.c:535]: Thanks for catching. I didn't realize the non-ZE path didn't set the device. We need it in the send IPC path for ZE. I've updated the code to set it in the normal send IPC path so hopefully this should be fixed. The ZE path is unique and needs a special send/recv path but we're working on moving that internally so we don't have to switch by interface in shm. That will let us merge the send and recv code and allow ZE to make use of the IPC caching. Let me know if the update works. Thanks for testing it!

Comment (wenduwan) [reply prov/shm/src/smr_progress.c:535]: Thanks for the quick update. I will test the change today. Once we move past the segfault I'm planning to run AWS CI (i.e. more tests) on a GPU instance. Will report back later.

Comment (aingerson) [reply prov/shm/src/smr_progress.c:535]: @wenduwan Thanks for the backtrace and additional data. I'm not sure I understand the issue here. I see that the device looks very wrong but I don't understand how it got here or the proposed fix above (I think the formatting might be off).
The problem seems to be on the RMA read path. The copy from is trying to copy the data from the target buffer into the initiator buffer through the IPC handle. The device comes directly from the cmd ipc info which should have been set by the sender. That device comes directly from the user's desc (ofi_mr). In other words, that the device came from the user/efa so I'm not sure how it got such an incorrect device. I think the only two ways this could happen are either with a corruption of the cmd IPC info data or an incorrect desc/MR registration from the app/efa. Can you add some output to see what device that memory region was registered with or what device is being picked up on the send side?
Like on smr_format_ipc what cmd->msg.data.ipc_info.device is at the end of the function and also what device is being passed into that function.
There could be some corruption in the data in the cmd ipc info like when we get the base address and stuff
```
struct ipc_info {
	uint64_t	iface;
	uint64_t	base_addr;
	uint64_t	base_length;
	uint64_t	device;
	uint64_t	offset;
	uint8_t		ipc_handle[MAX_IPC_HANDLE_SIZE];
};
```
Or maybe I'm completely off and your proposed fix is right! I just don't understand what you're suggesting :)

Comment (wenduwan) [reply prov/shm/src/smr_progress.c:535]: @aingerson Thanks for your explanation, in particular this
> The device comes directly from the cmd ipc info which should have been set by the sender. That device comes directly from the user's desc (ofi_mr).

This echoes back to my prior observation around `struct efa_mr` vs `struct ofi_mr`. I have a rough idea to test out via `fi_mr_desc`.

Will sync up later.

Comment (wenduwan) [reply prov/shm/src/smr_progress.c:535]: @aingerson Sorry I just realized that my local PR clone was not up-to-date. I missed git merge failure with your latest commit. I created a new repo and the segfault is gone! It became clear when I read the latest `prov/shm/src/smr_ep.c` 😅
Sorry for the confusion. I will proceed to run additional tests on this PR.

**Review by wenduwan — APPROVED** [review]
Ran more AWS CI tests on GPU instance. So far looking good. Thank you!

**Comment by shijin-aws** [comment]
Is this PR ready for merge?

**Comment by aingerson** [comment]
@shijin-aws It's good on my end. Not sure if @wenduwan had any extra tests to run.

**Comment by wenduwan** [comment]
I'm good with the existing tests. Thanks
