### PR TITLE
prov/shm: buffer unexpected inject and SAR data

### LINKED ISSUE #9143: prov/shm: SHM provider can't handle multiple unexpected messages in SAR protocol
**Describe the bug**
SHM provider can't handle multiple unexpected messages in SAR protocol

**To Reproduce**
Use CUDA<->host test as an example. Same result for host<->host test with CMA turned off

1k message size works fine

```
$ ./install/bin//fi_unexpected_msg -e rdm -p shm -s localhost -S 1000 -D cuda                                                                                                   
libfabric:63263:1689361915::core:core:ofi_cudaMemcpy():160<warn> Either dst or src buffer of cudaMemcpy is not allocated or registered by cuda device. cudaDeviceSynchronize() will be performed to ensure data consistency. The performance may be impacted.
PID 63263 GOOD iter 0/600 completed
PID 63263 GOOD iter 100/600 completed
PID 63263 GOOD iter 200/600 completed
PID 63263 GOOD iter 300/600 completed
PID 63263 GOOD iter 400/600 completed
PID 63263 GOOD iter 500/600 completed
PID 63263 GOOD all done
```
Anything above inject size hangs
```
$ ./install/bin//fi_unexpected_msg -e rdm -p shm -s localhost -S 4097 -D cuda                                                                                                   
libfabric:63422:1689361931::core:core:ofi_cudaMemcpy():160<warn> Either dst or src buffer of cudaMemcpy is not allocated or registered by cuda device. cudaDeviceSynchronize() will be performed to ensure data consistency. The performance may be impacted.

$ ./install/bin//fi_unexpected_msg -e rdm -p shm -s localhost -S 9000 -D cuda                                                                                                   
libfabric:63554:1689361948::core:core:ofi_cudaMemcpy():160<warn> Either dst or src buffer of cudaMemcpy is not allocated or registered by cuda device. cudaDeviceSynchronize() will be performed to ensure data consistency. The performance may be impacted.
```
This is on mainline 2c325372c01bfb56c66d2162979bafeffb30b31c

**Expected behavior**
Test shouldn't hang. SM2 provider with this PR passes this test https://github.com/ofiwg/libfabric/pull/9139

```
$ ./install/bin//fi_unexpected_msg -e rdm -p sm2 -s localhost -S 9000 -D cuda
libfabric:75313:1689362215::sm2:av:sm2_mmap_shrink_to_size():552<warn> Shrinking SHM file to be of size 20480
libfabric:75313:1689362215::sm2:ep_ctrl:sm2_create():71<warn> Claiming an entry for (fi_ns://localhost:9228)
libfabric:75313:1689362215::sm2:av:sm2_entry_allocate():472<warn> Using sm2 region at allocation entry[0] for fi_ns://localhost:9228
libfabric:75313:1689362216::core:core:ofi_cudaMemcpy():160<warn> Either dst or src buffer of cudaMemcpy is not allocated or registered by cuda device. cudaDeviceSynchronize() will be performed to ensure data consistency. The performance may be impacted.
libfabric:75313:1689362216::sm2:av:sm2_entry_allocate():472<warn> Using sm2 region at allocation entry[1] for fi_sm2://localhost:1000:0
PID 75313 GOOD iter 0/600 completed
PID 75313 GOOD iter 100/600 completed
PID 75313 GOOD iter 200/600 completed
PID 75313 GOOD iter 300/600 completed
PID 75313 GOOD iter 400/600 completed
PID 75313 GOOD iter 500/600 completed
PID 75313 GOOD all done
```

**Environment:**
Amazon Linux 2

### PR DESCRIPTION
**Pull request by aingerson**
Fixes #9143

### CODE REVIEW

**Comment by wenduwan** [comment]
AWS CI
```

server_command: ssh -n -o StrictHostKeyChecking=no -o ConnectTimeout=30 -o BatchMode=yes 172.31.4.49 'timeout 360 /bin/bash --login -c '"'"'/home/ec2-user/PortaFiducia/build/libraries/libfabric/pr9187-debug/install/fabtests/bin/fi_rma_bw -e rdm -o read -I 5 -U -v -p shm -s 172.31.4.49'"'"''

client_command: ssh -n -o StrictHostKeyChecking=no -o ConnectTimeout=30 -o BatchMode=yes 172.31.4.49 'timeout 360 /bin/bash --login -c '"'"'/home/ec2-user/PortaFiducia/build/libraries/libfabric/pr9187-debug/install/fabtests/bin/fi_rma_bw -e rdm -o read -I 5 -U -v -D cuda -p shm -s 172.31.4.49 172.31.4.49'"'"''
client_stdout:

client returncode: None
Client error: Client timed out
server_stdout:
bytes   iters   total       time     MB/sec    usec/xfer   Mxfers/sec
64      5       320         0.00s      6.27      10.20       0.10

server returncode: 124
```

**Comment by shijin-aws** [comment]
bot:aws:retest

**Comment by shijin-aws** [comment]
> AWS CI
> 
> ```
> 
> server_command: ssh -n -o StrictHostKeyChecking=no -o ConnectTimeout=30 -o BatchMode=yes 172.31.4.49 'timeout 360 /bin/bash --login -c '"'"'/home/ec2-user/PortaFiducia/build/libraries/libfabric/pr9187-debug/install/fabtests/bin/fi_rma_bw -e rdm -o read -I 5 -U -v -p shm -s 172.31.4.49'"'"''
> 
> client_command: ssh -n -o StrictHostKeyChecking=no -o ConnectTimeout=30 -o BatchMode=yes 172.31.4.49 'timeout 360 /bin/bash --login -c '"'"'/home/ec2-user/PortaFiducia/build/libraries/libfabric/pr9187-debug/install/fabtests/bin/fi_rma_bw -e rdm -o read -I 5 -U -v -D cuda -p shm -s 172.31.4.49 172.31.4.49'"'"''
> client_stdout:
> 
> client returncode: None
> Client error: Client timed out
> server_stdout:
> bytes   iters   total       time     MB/sec    usec/xfer   Mxfers/sec
> 64      5       320         0.00s      6.27      10.20       0.10
> 
> server returncode: 124
> ```

I couldn't tell if it is a real bug or not since the same tests passed for other OSes on cuda platforms.

File: prov/shm/src/smr_progress.c [hunk 1]
```diff
@@ -891,7 +894,20 @@ static int smr_alloc_cmd_ctx(struct smr_ep *ep,
...
+		if (!buf) {
+			FI_WARN(&smr_prov, FI_LOG_EP_CTRL,
+				"Error allocating buffer\n");
+			assert(0);
+		}
+		cmd_ctx->sar_entry = NULL;
+		slist_init(&cmd_ctx->buf_list);
+		slist_insert_tail(&buf->entry, &cmd_ctx->buf_list);
+		tx_buf = smr_get_ptr(ep->region, (size_t) cmd->msg.hdr.src_data);
+		memcpy(buf->buf, tx_buf->buf, cmd->msg.hdr.size);
```
Comment (shijin-aws) [inline prov/shm/src/smr_progress.c:908]: So we are using buffer of SAR_SIZE (32 K) for inject sized (4K) buffering? I think it may cause unnecessarily high memory usage when the number of unexp messages is high.

Comment (aingerson) [reply prov/shm/src/smr_progress.c:908]: Large (even 4k) unexpected message buffering if already going to case unnecessarily high memory usage. I did it this way to simplify the code. We could have two separate pools for 4k and 32k but that could also cause unnecessarily high memory usage since you can't mix and match (so if you've already allocated a bunch of 32k buffers but now you have a lot of 4k messages to buffer, you can't use that memory). The other solution would be to switch to 4k buffers all around and make the SAR messages take batch_size * 8 number of buffers but I think that would make the buffering code for SAR more complicated. Is there a method you would prefer?

Comment (shijin-aws) [reply prov/shm/src/smr_progress.c:908]: Let's go with the current simple approach.

**Comment by shijin-aws** [comment]
>Now that shm has unexpected SAR buffering (which requires a
pending entry to track the progress of the SAR copy), we could
theoretically exceed the rx size for in flight messages.

I actually have a question on this. I thought the sending will be blocked if the resp queue (tx/rx size) is full, so in theory we shouldn't have > rx size of in flight messages?

**Comment by aingerson** [comment]
@shijin-aws There are two ways the rx size can be exceeded with the pend_fs, neither of which are likely issues today, but they are valid issues and turning it into a bufpool also probably helps with memory consumption since we rarely have 1k pending entries to process at any given time. 
One is when using both the SAR protocol and ROCR async. They both use the pend_fs to track pending receives so you could use up all 1k pending entries for the IPC calls and then not have any left to process unexpected SARs
The second case is when rx_size < max peers (256). The rx size is actually modifiable by the user (either through info->rx_attr->size or overwritten through the FI_SHM_RX_SIZE environment variable) so if every peer sends a large SAR that requires a pending entry but our rx size is too small, we will run out.

The second case it actually an issue in upstream (but no application overrides the rx size or sets it so small) so it's not quite accurate to say that it is this PR that makes it necessary. But the first case is a new one where you could have more in flight pending receives than posted receives

**Comment by shijin-aws** [comment]
@aingerson ok, but neither of the case above should be hit by my earlier reproducer `fi_unexpected_msg -M 1024 -S 1048576`?

**Comment by aingerson** [comment]
@shijin-aws Yeah neither one should ha caused it so I don't know exactly where it came from but the version you were running when you hit it was very wrong and there were loads of other issues so I wouldn't be surprised if something else was the root cause there

File: prov/shm/src/smr_ep.c [hunk 2]
```diff
@@ -1466,6 +1470,15 @@ int smr_endpoint(struct fid_domain *domain, struct fi_info *info,
 			"Unable to create cmd ctx pool\n");
 		goto ep;
 	}
+
+	ret = ofi_bufpool_create(&ep->unexp_buf_pool, sizeof(struct smr_unexp_buf),
+				 16, 0, 4, OFI_BUFPOOL_NO_TRACK);
+	if (ret) {
+		FI_WARN(&smr_prov, FI_LOG_EP_CTRL,
+			"Unable to create cmd ctx pool\n");
```
Comment (shijin-aws) [inline prov/shm/src/smr_ep.c]: nit: the warning message should be "unable to create unexpected buf pool"

**Review by shijin-aws — APPROVED** [review]

File: prov/shm/src/smr_ep.c [hunk 3]
```diff
@@ -1418,6 +1422,43 @@ static void smr_init_sig_handlers(void)
...
+	if (ret)
+		goto err;
+
+	ret = ofi_bufpool_grow(ep->cmd_ctx_pool);
+	if (ret)
+		goto free2;
+
+	ret = ofi_bufpool_create(&ep->unexp_buf_pool,
+				 sizeof(struct smr_unexp_buf),
+				 16, 0, 4, OFI_BUFPOOL_NO_TRACK);
```
Comment (shijin-aws) [inline prov/shm/src/smr_ep.c:1441]: Could you add FI_WARN before goto free? same for the pend buf pool

**Comment by aingerson** [comment]
@shijin-aws I see you just reviewed but maybe on an outdated version? I don't think those are there anymore. Would you mind taking a second look on the new version and letting me know if that looks ok now?

**Comment by aingerson** [comment]
@shijin-aws Oh jk I see what happened. You reviewed by patch and I was looking at the full set. I will fix it in the patch itself.

File: prov/shm/src/smr_ep.c (hunk 3 above)
Comment (aingerson) [reply prov/shm/src/smr_ep.c:1441]: There's already a general warning message for all of the error cases. Would you prefer three different messages?

Comment (shijin-aws) [reply prov/shm/src/smr_ep.c:1441]: I am ok with having 1 FI_WARN at the bottom, but EP resources may be too general. How about "Unable to allocate buf pools for EP" to match this function's signature?

**Comment by a-szegel** [comment]
alinux2.test_suites.libfabric.test_fabtests.test_fabtests_functional[single_node-debug].test_rma_bw[delivery_complete-cuda_to_host-short-write] 
ubuntu2004-disable-cma.test_suites.libfabric.test_fabtests.test_fabtests_functional[single_node-debug].test_rma_bw[delivery_complete-host_to_host-short-writedata] 

Looks like Client/Server both timed out on both failures... might not be related to your PR... but it might be.

**Review by a-szegel — APPROVED** [review]

**Comment by a-szegel** [comment]
bot:aws:retest

**Comment by shijin-aws** [comment]
bot:aws:retest

**Comment by shijin-aws** [comment]
Still the cuda-to-host fabtests timeout

```
server_command: ssh -n -o StrictHostKeyChecking=no -o ConnectTimeout=30 -o BatchMode=yes 172.31.42.42 'timeout 360 /bin/bash --login -c '"'"'/home/ec2-user/PortaFiducia/build/libraries/libfabric/pr9187-debug/install/fabtests/bin/fi_rma_bw -e rdm -o write -I 5 -v -p shm -s 172.31.42.42'"'"''

client_command: ssh -n -o StrictHostKeyChecking=no -o ConnectTimeout=30 -o BatchMode=yes 172.31.42.42 'timeout 360 /bin/bash --login -c '"'"'/home/ec2-user/PortaFiducia/build/libraries/libfabric/pr9187-debug/install/fabtests/bin/fi_rma_bw -e rdm -o write -I 5 -v -D cuda -p shm -s 172.31.42.42 172.31.42.42'"'"''
client_stdout:

client returncode: None
Client error: Client timed out
server_stdout:

server returncode: 124
```

will try to reproduce

**Comment by a-szegel** [comment]
bot:aws:retest

**Comment by shijin-aws** [comment]
I can reproduce the hang locally. Will update when I get something

**Comment by shijin-aws** [comment]
The hang was caused by the following warning:

```
+ /home/ec2-user/PortaFiducia/build/libraries/libfabric/pr9187-debug/install/fabtests/bin/fi_rma_bw -e rdm -o read -I 5 -U -v -p shm -s localhost
+ FI_LOG_LEVEL=warn
+ /home/ec2-user/PortaFiducia/build/libraries/libfabric/pr9187-debug/install/fabtests/bin/fi_rma_bw -e rdm -o read -I 5 -U -v -p shm -s localhost -D cuda localhost
libfabric:21146:1691522761::core:core:ofi_cudaMemcpy():160<warn> Either dst or src buffer of cudaMemcpy is not allocated or registered by cuda device. cudaDeviceSynchronize() will be performed to ensure data consistency. The performance may be impacted.
libfabric:21122:1691522761::shm:mr:ofi_mr_map_verify():114<warn> unknown key: 0
libfabric:21122:1691522761::shm:ep_ctrl:smr_progress_cmd():1201<warn> error processing command
bytes   iters   total       time     MB/sec    usec/xfer   Mxfers/sec
64      5       320         0.00s      6.96       9.20       0.11
```

**Comment by shijin-aws** [comment]
The issue is due to a bug in `smr_buffer_sar`, commented in the PR

File: prov/shm/src/smr_progress.c [hunk 4]
```diff
@@ -1190,10 +1269,43 @@ static void smr_progress_ipc_list(struct smr_ep *ep)
...
+			&sar_entry->cmd_ctx->buf_list);
+
+		sar_buf = smr_freestack_get_entry_from_index(
+				smr_sar_pool(ep->region),
+				sar_entry->cmd.msg.data.sar[i]);
+		bytes = MIN(sar_entry->cmd.msg.hdr.size -
+				sar_entry->bytes_done,
+				SMR_SAR_SIZE);
+
+		memcpy(buf, sar_buf->buf, bytes);
```
Comment (shijin-aws) [inline prov/shm/src/smr_progress.c:1301]: I think it should be `memcpy(buf->buf, sar_buf->buf, bytes);` here

**Comment by shijin-aws** [comment]
Please also rebase on the latest main branch to resolve the conflicts

**Comment by shijin-aws** [comment]
@aingerson can you change that fabtests/pytest/efa commit to this fabtests/pytest/shm commit https://github.com/shijin-aws/libfabric/commit/08fa02e14313847cfaedacc0da44a63fce5e3c31? 

I want to work on that efa change in a separate PR

**Comment by aingerson** [comment]
@shijin-aws Sorry I think I grabbed the wrong commit! Updated

**Comment by shijin-aws** [comment]
Thanks! We can merge it as long as CI passes

**Comment by shijin-aws** [comment]
A new failure in AWS CI:

```
--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

server_command: ssh -n -o StrictHostKeyChecking=no -o ConnectTimeout=30 -o BatchMode=yes 172.31.37.104 'timeout 360 /bin/bash --login -c '"'"'FI_EFA_USE_DEVICE_RDMA=0 /home/ec2-user/PortaFiducia/build/libraries/libfabric/pr9187/install/fabtests/bin/fi_bw -e rdm -v -T 1 -U -p efa -E=9233'"'"''

client_command: ssh -n -o StrictHostKeyChecking=no -o ConnectTimeout=30 -o BatchMode=yes 172.31.37.104 'timeout 360 /bin/bash --login -c '"'"'FI_EFA_USE_DEVICE_RDMA=0 /home/ec2-user/PortaFiducia/build/libraries/libfabric/pr9187/install/fabtests/bin/fi_bw -e rdm -v -T 1 -U -p efa -E=9233 172.31.37.104'"'"''
client_stdout:

client returncode: None
Client error: Client timed out
server_stdout:
bytes   iters   total       time     MB/sec    usec/xfer   Mxfers/sec
64      64      4k          0.00s     33.85       1.89       0.53
256     64      16k         0.00s     77.28       3.31       0.30
1k      64      64k         0.00s    292.57       3.50       0.29
4k      64      256k        0.00s    422.81       9.69       0.10

server returncode: 124
```

Likely related to the PR. Will try to reproduce

**Comment by shijin-aws** [comment]
@aingerson I think you need this patch to handle 0 sized sar unexpected msg

```
@@ -1327,7 +1328,9 @@ static void smr_progress_sar_list(struct smr_ep *ep)
                                     sar_entry, entry, tmp) {
                peer_smr = smr_peer_region(ep->region, sar_entry->cmd.msg.hdr.id);
                resp = smr_get_ptr(peer_smr, sar_entry->cmd.msg.hdr.src_data);
-               if (sar_entry->cmd.msg.hdr.op == ofi_op_read_req) {
+               if (!sar_entry->cmd.msg.hdr.size) {
+                       resp->status = SMR_STATUS_SUCCESS;
+               } else if (sar_entry->cmd.msg.hdr.op == ofi_op_read_req) {
```

**Comment by aingerson** [comment]
@shijin-aws Thanks for the patch! I've added the fix in a different way (not adding it to the sar list in the first place). Let me know if you see issues.

**Comment by shijin-aws** [comment]
Thanks for the update, yeah I think your fix is better than mine. I verified it works for 0 byte unexpected msg test. I still need  to look into those hang for >4k msg

**Comment by shijin-aws** [comment]
All the AWS CI failures are the fi_rma_bw runs for shm provider

One of them is

```
--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

server_command: ssh -n -o StrictHostKeyChecking=no -o ConnectTimeout=30 -o BatchMode=yes 172.31.3.203 'timeout 360 /bin/bash --login -c '"'"'/home/ec2-user/PortaFiducia/build/libraries/libfabric/pr9187-debug/install/fabtests/bin/fi_rma_bw -e rdm -o write -I 5 -U -v -S r:4048,4,4148 -p shm -s 172.31.3.203'"'"''

client_command: ssh -n -o StrictHostKeyChecking=no -o ConnectTimeout=30 -o BatchMode=yes 172.31.3.203 'timeout 360 /bin/bash --login -c '"'"'/home/ec2-user/PortaFiducia/build/libraries/libfabric/pr9187-debug/install/fabtests/bin/fi_rma_bw -e rdm -o write -I 5 -U -v -S r:4048,4,4148 -D cuda -p shm -s 172.31.3.203 172.31.3.203'"'"''
client_stdout:

client returncode: 255
server_stdout:

server returncode: 124
```

**Comment by shijin-aws** [comment]
bot:aws:retest

**Comment by shijin-aws** [comment]
bot:aws:retest

**Comment by aingerson** [comment]
@shefty FYI I'm hoping to put this in 1.19 but we have a lingering failure we are trying to resolve (our CI going bonkers is not helping)

**Comment by shefty** [comment]
The CI going bonkers is buying you more time.  You have that going for you.

**Comment by shijin-aws** [comment]
I think this PR is ready for merge @aingerson
