### PR TITLE
prov/sockets: Refactored fi_getinfo to handle corner cases

### LINKED ISSUE #2146: sockets: provider doesn't check if specified source address belongs to local interface
Providing a source address during discovery with the `FI_SOURCE` flag always succeeds even if the address is not local or not usable. It seems this is because the address is [resolved using `getaddrinfo`](https://github.com/ofiwg/libfabric/blob/master/prov/sockets/src/sock_fabric.c#L421-L431), but never checked against the interfaces on the system. This becomes a problem later when the provider attempts to open a connection thread on the address. The provider logs an error about the failed connection thread but does not return an error code. I think the provider should probably return an error code in the event that the connection thread cannot be started [here](https://github.com/ofiwg/libfabric/blob/master/prov/sockets/src/sock_ep.c#L968-L972). Instead it seems to start up and wait for a timeout. 

```sh
bturrubi at blade11 :: FI_LOG_LEVEL=debug ./fi_dgram_pingpong -f sockets -s www.google.com
...
libfabric:sockets:ep_data:sock_pe_init_table():2803<debug> PE table init: OK
libfabric:sockets:ep_data:sock_pe_init():2854<debug> PE init: OK
libfabric:sockets:ep_data:sock_pe_progress_thread():2743<debug> Progress thread started
libfabric:sockets:ep_data:sock_pe_add_tx_ctx():2435<debug> TX ctx added to PE
libfabric:sockets:ep_data:sock_pe_add_rx_ctx():2453<debug> RX ctx added to PE
libfabric:sockets:ep_ctrl:sock_conn_listen():311<debug> Binding listener thread to port: 9228
libfabric:sockets:ep_ctrl:sock_conn_listen():327<warn> failed to listen to port: 9228
libfabric:sockets:ep_ctrl:sock_ep_enable():970<warn> cannot start connection thread
libfabric:sockets:ep_data:sock_rx_new_entry():83<debug> New rx_entry: 0x65c760, ctx: 0x645580
libfabric:sockets:ep_data:sock_ep_recvmsg():134<debug> New rx_entry: 0x65c760 (ctx: 0x645580)
5s timeout expired
ft_get_cq_comp(): ../common/shared.c:1313, ret=-61 (No data available)
libfabric:sockets:ep_data:sock_pe_progress_thread():2780<debug> Progress thread terminated
libfabric:sockets:ep_data:sock_pe_finalize():2910<debug> Progress engine finalize: OK
...
```

@shantonu @jithinjosepkl

### PR DESCRIPTION
**Pull request by shantonu**
- Added <code>slist_find_first_match()</code> to <code>fi_list.h</code>
- Added <code>sock_matches_interface()</code> that checks if the <code>node</code> or <code>hints->src_addr</code> matches local interfaces
- Minor refactoring of <code>sock_get_list_of_addr</code>
- Return localhost as the last entry in the returned list of interfaces

Fixes #2146 

@jithinjosepkl @shefty @a-ilango

### CODE REVIEW

File: prov/sockets/src/sock_fabric.c [hunk 1]
```diff
@@ -634,6 +624,55 @@ int sock_node_getinfo(const char *node, const char *service, uint64_t flags,
...
+	int ret;
+
+	if (src_len == sizeof(struct sockaddr_in)) {
+		addr = (struct sockaddr_in *)src_addr;
+	} else {
+		memset(&ai, 0, sizeof(ai));
+		ai.ai_family = AF_INET;
+		ai.ai_socktype = SOCK_STREAM;
+
+		ret = getaddrinfo(src_addr, 0, &ai, &rai);
```
Comment (shefty) [inline prov/sockets/src/sock_fabric.c]: This needs to be paired with freeaddrinfo()

Comment (shantonu) [inline prov/sockets/src/sock_fabric.c]: Missed that! Fix is pushed.

File: prov/sockets/src/sock_fabric.c [hunk 2]
```diff
@@ -634,6 +623,58 @@ int sock_node_getinfo(const char *node, const char *service, uint64_t flags,
...
+}
+
+static int sock_matches_interface(struct slist addr_list, const void *src_addr, size_t src_len)
+{
+	struct slist_entry *entry;
+	struct addrinfo ai, *rai = NULL;
+	struct sockaddr_in *addr;
+	int ret;
+
+	if (src_len == sizeof(struct sockaddr_in)) {
```
Comment (a-ilango) [inline prov/sockets/src/sock_fabric.c]: We might need to handle IPv6 addresses as well.

File: prov/sockets/src/sock_fabric.c [hunk 3]
```diff
@@ -658,35 +699,44 @@ static int sock_getinfo(uint32_t version, const char *node, const char *service,
...
-	if (!node  && (!hints || !hints->src_addr || (!(flags & FI_SOURCE) &&
-	     !hints->dest_addr))) {
-		addr_list = sock_get_list_of_addr();
+	/* Returns loopback address if no other interfaces are available */
+	sock_get_list_of_addr(&addr_list);
+	if (flags & FI_SOURCE) {
+		if (node)
+			ret = sock_matches_interface(addr_list, node, sizeof(node));
+	}
+	else if (hints && hints->src_addr) {
```
Comment (a-ilango) [inline prov/sockets/src/sock_fabric.c]: nit: "else if" should be in the same line as the closing brace for previous if

File: prov/sockets/src/sock_fabric.c (hunk 2 above)
Comment (shefty) [inline prov/sockets/src/sock_fabric.c]: I think the socket provider is limited to ipv4 and will require more changes to handle ipv6

File: prov/sockets/src/sock_fabric.c [hunk 4]
```diff
@@ -634,6 +623,58 @@ int sock_node_getinfo(const char *node, const char *service, uint64_t flags,
 	return ret;
 }
 
+static int sock_match_src_addr(struct slist_entry *entry, const void *src_addr)
+{
+	struct sock_host_list_entry *host_entry;
+	host_entry = container_of(entry, struct sock_host_list_entry, entry);
+
+        if (strcmp(host_entry->hostname, (char *)src_addr) == 0)
```
Comment (jithinjosepkl) [inline prov/sockets/src/sock_fabric.c]: nit: we could just return directly (strcmp() == 0)

File: prov/sockets/src/sock_fabric.c (hunk 2 above)
Comment (jithinjosepkl) [inline prov/sockets/src/sock_fabric.c]: yeah, it supports only ipv4 addresses.

File: prov/sockets/src/sock_fabric.c (hunk 3 above)
Comment (shantonu) [inline prov/sockets/src/sock_fabric.c]: :+1:

File: prov/sockets/src/sock_fabric.c (hunk 4 above)
Comment (shantonu) [inline prov/sockets/src/sock_fabric.c]: :+1:

**Comment by shantonu** [comment]
Updated the PR with suggested fixes.

File: prov/sockets/src/sock_fabric.c [hunk 5]
```diff
@@ -634,6 +622,57 @@ int sock_node_getinfo(const char *node, const char *service, uint64_t flags,
...
+		addr = (struct sockaddr_in *)src_addr;
+	} else {
+		memset(&ai, 0, sizeof(ai));
+		ai.ai_family = AF_INET;
+		ai.ai_socktype = SOCK_STREAM;
+
+		ret = getaddrinfo(src_addr, 0, &ai, &rai);
+		if (ret) {
+			SOCK_LOG_DBG("getaddrinfo failed!\n");
+			freeaddrinfo(rai);
```
Comment (shefty) [inline prov/sockets/src/sock_fabric.c]: You need to call freeaddrinfo() if getaddrinfo() succeeds, not fails.

File: prov/sockets/src/sock_fabric.c [hunk 6]
```diff
@@ -634,6 +622,57 @@ int sock_node_getinfo(const char *node, const char *service, uint64_t flags,
...
+static int sock_matches_interface(struct slist addr_list, const void *src_addr,
+				   size_t src_len)
+{
+	struct slist_entry *entry;
+	struct addrinfo ai, *rai = NULL;
+	struct sockaddr_in *addr;
+	int ret;
+
+	if (src_len == sizeof(struct sockaddr_in)) {
+		addr = (struct sockaddr_in *)src_addr;
```
Comment (shefty) [inline prov/sockets/src/sock_fabric.c]: We shouldn't need a cast here.  You may need to declare addr as const to avoid a warning, and propagate the const through to subcalls.

File: include/fi_list.h [hunk 7]
```diff
@@ -187,6 +187,18 @@ static inline struct slist_entry *slist_remove_head(struct slist *list)
 typedef int slist_func_t(struct slist_entry *item, const void *arg);
 
 static inline struct slist_entry *
+slist_find_first_match(struct slist *list, slist_func_t *match, const void *arg)
```
Comment (shefty) [inline include/fi_list.h]: Should probably define list as const

File: prov/sockets/src/sock_fabric.c [hunk 8]
```diff
@@ -634,6 +622,57 @@ int sock_node_getinfo(const char *node, const char *service, uint64_t flags,
...
+		if (ret) {
+			SOCK_LOG_DBG("getaddrinfo failed!\n");
+			freeaddrinfo(rai);
+			return -FI_EINVAL;
+		}
+		addr = (struct sockaddr_in *)rai->ai_addr;
+	}
+	entry = slist_find_first_match(&addr_list, sock_match_src_addr,
+					inet_ntoa(addr->sin_addr));
+	freeaddrinfo(rai);
```
Comment (shefty) [inline prov/sockets/src/sock_fabric.c]: This should only be called if we call getaddrinfo().  That's only done in the else clause above.

File: prov/sockets/src/sock_fabric.c [hunk 9]
```diff
@@ -658,35 +697,44 @@ static int sock_getinfo(uint32_t version, const char *node, const char *service,
...
 
 	slist_init(&addr_list);
-	if (!node  && (!hints || !hints->src_addr || (!(flags & FI_SOURCE) &&
-	     !hints->dest_addr))) {
-		addr_list = sock_get_list_of_addr();
+	/* Returns loopback address if no other interfaces are available */
+	sock_get_list_of_addr(&addr_list);
+	if (flags & FI_SOURCE) {
+		if (node)
+			ret = sock_matches_interface(addr_list, node, sizeof(node));
```
Comment (shefty) [inline prov/sockets/src/sock_fabric.c]: sizeof(node) will be the size of a pointer, not the length of the string.

Comment (shantonu) [inline prov/sockets/src/sock_fabric.c]: Actually I want pass sizeof(type specifier) which is sizeof(char). Will update.

File: prov/sockets/src/sock_fabric.c (hunk 8 above)
Comment (shantonu) [inline prov/sockets/src/sock_fabric.c]: Fixed it.

File: prov/sockets/src/sock_fabric.c (hunk 6 above)
Comment (shantonu) [inline prov/sockets/src/sock_fabric.c]: :+1:

File: prov/sockets/src/sock_fabric.c (hunk 5 above)
Comment (shantonu) [inline prov/sockets/src/sock_fabric.c]: :+1:

File: include/fi_list.h (hunk 7 above)
Comment (shantonu) [inline include/fi_list.h]: :+1:

**Comment by shantonu** [comment]
Pushed another round of fixes addressing all the comments.

**Comment by shantonu** [comment]
Noticed Mac failures on Travis-CI. Seems to me irrelevant to the PR. Also Travis-CI broadcasted that they have Mac build issues. Not sure if it was sue to system issue.

File: prov/sockets/src/sock_fabric.c [hunk 10]
```diff
@@ -658,35 +696,45 @@ static int sock_getinfo(uint32_t version, const char *node, const char *service,
...
 	slist_init(&addr_list);
-	if (!node  && (!hints || !hints->src_addr || (!(flags & FI_SOURCE) &&
-	     !hints->dest_addr))) {
-		addr_list = sock_get_list_of_addr();
+	/* Returns loopback address if no other interfaces are available */
+	sock_get_list_of_addr(&addr_list);
+
+	if (flags & FI_SOURCE) {
+		if (node)
+			ret = sock_matches_interface(addr_list, node, sizeof(char));
```
Comment (jithinjosepkl) [inline prov/sockets/src/sock_fabric.c]: It looks a little confusing to use sizeof(char) to determine the address type.

File: prov/sockets/src/sock_fabric.c [hunk 11]
```diff
@@ -634,6 +622,57 @@ int sock_node_getinfo(const char *node, const char *service, uint64_t flags,
...
+{
+	struct sock_host_list_entry *host_entry;
+	host_entry = container_of(entry, struct sock_host_list_entry, entry);
+
+        return ((strcmp(host_entry->hostname, (char *) src_addr) == 0) ||
+		(strcmp(host_entry->hostname, "0.0.0.0") == 0));
+}
+
+static int sock_matches_interface(struct slist addr_list, const void *src_addr,
+				   size_t src_type_len)
```
Comment (shefty) [inline prov/sockets/src/sock_fabric.c]: As Jithin mentioned below, using a len to indicate the address type is confusing.  Given the structure of the function and that it nearly splits into 2 based on src_type_len, I would just create 2 separate functions and call the correct one from the proper location.

Comment (shantonu) [inline prov/sockets/src/sock_fabric.c]: I agree, it's a bit confusing. I'll create two functions then.

**Comment by shantonu** [comment]
Updates to the PR:
- Fixed a bug in <code>sock_node_matches_interface() </code> which was causing issue in OS X run
- Created two separate methods for matching different address type
- Added logic to detect loopback address and return match without iterating over the local interfaces since it'll always be there.
- Added another commit to fix minor type casting

Travis looks happy as well. Can you please take another look? @jithinjosepkl @shefty

File: prov/sockets/src/sock_ep_msg.c [hunk 12]
```diff
@@ -1380,8 +1380,8 @@ int sock_msg_passive_ep(struct fid_fabric *fabric, struct fi_info *info,
 				SOCK_LOG_DBG("getaddrinfo failed!\n");
 				goto err;
 			}
-			memcpy(&_pep->src_addr, result->ai_addr,
-				result->ai_addrlen);
+			memcpy(&_pep->src_addr, (struct sockaddr_in *)result->ai_addr,
```
Comment (shefty) [inline prov/sockets/src/sock_ep_msg.c]: You don't need a cast for memcpy

File: prov/sockets/src/sock_fabric.c [hunk 13]
```diff
@@ -634,6 +622,62 @@ int sock_node_getinfo(const char *node, const char *service, uint64_t flags,
 	return ret;
 }
 
+static int sock_match_src_addr(struct slist_entry *entry, const void *src_addr)
```
Comment (shefty) [inline prov/sockets/src/sock_fabric.c]: Change src_addr from void * to char *.

Comment (shefty) [inline prov/sockets/src/sock_fabric.c]: Er... you may not be able to - I see that the function is passed as a parameter below

File: prov/sockets/src/sock_ep_msg.c (hunk 12 above)
Comment (shantonu) [inline prov/sockets/src/sock_ep_msg.c]: Oh, ok!

File: prov/sockets/src/sock_fabric.c (hunk 13 above)
Comment (shantonu) [inline prov/sockets/src/sock_fabric.c]: Yeah, it's passed in <code>sock_addr_matches_interface()</code> as a function pointer of type <code>slist_func_t(struct slist_entry *item, const void *arg)</code>

File: prov/sockets/src/sock_fabric.c [hunk 14]
```diff
@@ -658,35 +702,45 @@ static int sock_getinfo(uint32_t version, const char *node, const char *service,
...
+		flags |= FI_SOURCE;
+		ret = sock_node_getinfo(node, service, flags, hints, info, &tail);
 		free(host_entry);
+		if (ret) {
+			if (ret == -FI_ENODATA)
+				continue;
+			goto out;
+		}
 	}
+	return 0;
```
Comment (jithinjosepkl) [inline prov/sockets/src/sock_fabric.c]: Adding return here will result in memory leaks (list entries)

File: prov/sockets/src/sock_fabric.c [hunk 15]
```diff
@@ -634,6 +622,62 @@ int sock_node_getinfo(const char *node, const char *service, uint64_t flags,
...
 
+static int sock_match_src_addr(struct slist_entry *entry, const void *src_addr)
+{
+	struct sock_host_list_entry *host_entry;
+	host_entry = container_of(entry, struct sock_host_list_entry, entry);
+
+        return (strcmp(host_entry->hostname, (char *) src_addr) == 0);
+}
+
+static int sock_addr_matches_interface(struct slist addr_list, struct sockaddr_in *src_addr)
```
Comment (jithinjosepkl) [inline prov/sockets/src/sock_fabric.c]: Is there a need for keeping the argument as struct? Cant we use pointer to list here?

File: prov/sockets/src/sock_fabric.c [hunk 16]
```diff
@@ -634,6 +622,62 @@ int sock_node_getinfo(const char *node, const char *service, uint64_t flags,
...
+		return 1;
+
+	entry = slist_find_first_match(&addr_list, sock_match_src_addr,
+					inet_ntoa(src_addr->sin_addr));
+
+	return entry ? 1 : 0;
+}
+
+static int sock_node_matches_interface(struct slist addr_list, const char *node)
+{
```
Comment (jithinjosepkl) [inline prov/sockets/src/sock_fabric.c]: We are passing struct here also.

File: prov/sockets/src/sock_fabric.c [hunk 17]
```diff
@@ -658,35 +702,45 @@ static int sock_getinfo(uint32_t version, const char *node, const char *service,
...
-	return 0;
-out:
+
 	while (!slist_empty(&addr_list)) {
 		entry = slist_remove_head(&addr_list);
 		host_entry = container_of(entry, struct sock_host_list_entry, entry);
+		node = host_entry->hostname;
+		flags |= FI_SOURCE;
+		ret = sock_node_getinfo(node, service, flags, hints, info, &tail);
 		free(host_entry);
```
Comment (shantonu) [inline prov/sockets/src/sock_fabric.c]: We are freeing the list entry here @jithinjosepkl

File: prov/sockets/src/sock_fabric.c (hunk 14 above)
Comment (shantonu) [inline prov/sockets/src/sock_fabric.c]: It's freed in the while loop in success case and we have a free in error case.

File: prov/sockets/src/sock_fabric.c (hunk 15 above)
Comment (shantonu) [inline prov/sockets/src/sock_fabric.c]: Sure, will change that.

File: prov/sockets/src/sock_fabric.c (hunk 16 above)
Comment (shantonu) [inline prov/sockets/src/sock_fabric.c]: Changed it!

File: prov/sockets/src/sock_fabric.c (hunk 17 above)
Comment (jithinjosepkl) [inline prov/sockets/src/sock_fabric.c]: Ok, a cleaner way is to just free the entries before exiting the loop, and then do a break. That can avoid the goto out.

Comment (shantonu) [inline prov/sockets/src/sock_fabric.c]: Removed the goto and added the free call and return inside the while loop.

**Comment by shantonu** [comment]
Addressed all the comments. Is there any other concern?

**Comment by jithinjosepkl** [comment]
👍
