### PR TITLE
Pr/sockets: Add fabric/domain name based filtering in fi_getinfo

### LINKED ISSUE #2248: sockets: filtering on fabric name doesn't seem to work as expected
In trying to debug an unrelated issue, I noticed some unexpected behavior with the sockets provider. The code for this test can be found [here](https://github.com/bturrubiates/fi-resolve).

It's a very simple program to just try resolving an address. I'd expect that if I request fabric `127.0.0.0/8`, then I'll only get back structures from `fi_getinfo` that are on that fabric. 

The `-P` switch is the provider, the `-f` switch is the fabric, and the last parameter is the address that should be resolved. 

```sh
bturrubi at ivy11 :: ./src/fi_resolve -P sockets -f 127.0.0.0/8 10.30.0.191
[src/resolve.c]:setup_fabric():<91> provided provider name hint: sockets
[src/resolve.c]:setup_fabric():<92> provided fabric name hint: 127.0.0.0/8
[src/resolve.c]:setup_fabric():<111> opened fabric with provider: sockets
[src/resolve.c]:setup_fabric():<112> bound to: 10.0.0.0/16
Successfully resolved address to 10.30.0.191:1337
```

### PR DESCRIPTION
**Pull request by shantonu**
- After setting the fabric/domain name from the local interfaces, check if if matches with the hint provided by the user.
- Fix the return value of fi_getinfo when there is no fi_info to return.

Fixes #2248 and #2302. Verified with #2300 that adds fabric and domain parameter in ```fi_info```.

Could you please review @j-xiong @bturrubiates @a-ilango?

### CODE REVIEW

File: prov/sockets/src/sock_fabric.c [hunk 1]
```diff
@@ -718,7 +718,8 @@ static int sock_getinfo(uint32_t version, const char *node, const char *service,
 			return ret;
 		}
 	}
-	return 0;
+
+	return ret ? ret : 0;
```
Comment (j-xiong) [inline prov/sockets/src/sock_fabric.c]: that is equivalent to "return ret;"

Comment (shantonu) [inline prov/sockets/src/sock_fabric.c]: right! Will fix it.

**Comment by bturrubiates** [comment]
👍 Thanks!

**Comment by shantonu** [comment]
@j-xiong, could you please merge if there's no other comments?
