### PR TITLE
prov/util: Only allocate MR key when needed

### LINKED ISSUE #10882: prov/tcp: fi_mr_reg fails when requested_key is unchanged even when the buffer is not used for RMA operations
**Describe the bug**
According to Sean here https://github.com/ofiwg/libfabric/pull/8350#issuecomment-1349946033
> A key is only needed and used if the memory will be the target of an RMA operation.

So if an endpoint does not have FI_RMA and FI_ATOMIC capabilities or if the buffer access flags are only FI_SEND and FI_RECV, then the key is not relevant or useful. Yet today, an `fi_mr_reg` call to the TCP provider will fail unless the `attr->requested_key` is unique for each call

The failure happens here https://github.com/ofiwg/libfabric/blob/996a6c1911ca91a8cb9367da854c09086963303b/prov/util/src/util_mr_map.c#L82-L90

What should be the behavior of `fi_mr_reg` and the remote key when the buffer is not meant for RMA or atomic usage? If the key doesn't matter unless the buffer is used for RMA or atomic operations, shouldn't the TCP provider check that and not fail `fi_mr_reg` in such cases?

**To Reproduce**
Call `fi_mr_regattr` without changing `attr->requested_key`

**Expected behavior**
`fi_mr_regattr` succeeds

**Additional context**
Similar to https://github.com/ofiwg/libfabric/issues/10821

### PR DESCRIPTION
**Pull request by j-xiong**
MR key is only needed for remote access. If remote access rights are not asked
for, MR registration should succeed even if key allocation fails. To prevent
key confliction with a future registration that needs the key, don't even try
to allocation the key if it is not needed.

A special key, FI_KEY_NOTAVAIL, is assigned for such case.

Fixes #10882

### CODE REVIEW

File: prov/util/src/util_mr_map.c [hunk 1]
```diff
@@ -82,6 +83,8 @@ int ofi_mr_map_insert(struct ofi_mr_map *map, const struct fi_mr_attr *attr,
 	if (map->mode & FI_MR_PROV_KEY)
 		item->requested_key = map->key++;
 
+	key_is_optional = !(attr->access & (FI_REMOTE_READ | FI_REMOTE_WRITE));
```
Comment (sunkuamzn) [inline prov/util/src/util_mr_map.c:86]: Should `FI_READ` and `FI_WRITE` also be included?

File: prov/util/src/util_mr_map.c [hunk 2]
```diff
@@ -82,6 +83,8 @@ int ofi_mr_map_insert(struct ofi_mr_map *map, const struct fi_mr_attr *attr,
...
+
 	ret = ofi_rbmap_insert(map->rbtree, &item->requested_key, item, NULL);
```
Comment (sunkuamzn) [inline prov/util/src/util_mr_map.c:88]: The first insertion will succeed because the key is unique. Meaning `fi_mr_key` will return the `requested_key` from mr_attr for the first region and `FI_KEY_NOTAVAIL` for the others.

Also, if there is a future `fi_mr_reg` call for the same region with different access flags, they will overlap in the rb tree.

I think we should not insert into the rb tree if `key_is_optional` is true.

**Comment by sunkuamzn** [comment]
Our CI failure is unrelated. We are trying to fix.

File: prov/util/src/util_mr_map.c (hunk 1 above)
Comment (j-xiong) [reply prov/util/src/util_mr_map.c:86]: FI_READ and FI_WRITE are for local access only (the result buffer for fi_read, and the source buffer for fi_write).

File: prov/util/src/util_mr_map.c (hunk 2 above)
Comment (j-xiong) [reply prov/util/src/util_mr_map.c:91]: Updated.

**Review by sunkuamzn — APPROVED** [review]

**Comment by shefty** [comment]
What is the purpose of registering memory with the tcp provider if not for remote access?  Nothing will touch the region.  The tcp provider could either treat such calls as no-ops (return some static struct) or just fail with EWHATISTHEUSERDOING

**Comment by j-xiong** [comment]
If we add FI_HMEM support to the tcp provider, the local desc will still be useful.

This PR though, is not limited to the tcp provider. The utility code is also used by efa, rxm, and ucx, which can potentially encounter the same issue.

**Comment by j-xiong** [comment]
@shefty Note added to the man page.

**Comment by sunkuamzn** [comment]
bot:aws:retest

**Comment by sunkuamzn** [comment]
@j-xiong the EFA provider actually needs to insert all buffers into the MR map because (1) we implicitly use RDMA protocols for some send/receive operations and (2) we're working around the CUDA memory monitor issue in https://github.com/ofiwg/libfabric/issues/8081

Because these are specific to the EFA provider, we added a fix in EFA provider code in https://github.com/ofiwg/libfabric/pull/10892 Please rebase on that commit and our CI should pass

**Review by shefty — APPROVED** [review]

**Comment by j-xiong** [comment]
@shefty @sunkuamzn Update the PR to handle the key in `ofi_mr_regattr` instead of `ofi_mr_map_insert`. This should make #10892 unnecessary.

**Review by shefty — APPROVED** [review]
I like this approach better.

**Comment by sunkuamzn** [comment]
@j-xiong this fix is working for us, thanks!

Can we backport this to v2.1.x branch?

**Comment by j-xiong** [comment]
@sunkuamzn Sure.
