### PR TITLE
usnic: Fix handling of info parameter passed to fi_passive_ep.

### LINKED ISSUE #1801: usnic: PEP info given in CONNREQ event doesn't seem to be properly filled out
PR ofiwg/fabtests#470 seems to have exposed an issue in the way that the usNIC provider handles the `fi_info` struct passed to `fi_passive_ep`. At the moment only the addressing information is preserved. I believe the correct solution is to copy all modes/caps/properties à la `fi_dupinfo`

### PR DESCRIPTION
**Pull request by bturrubiates**
- Info parameter to fi_passive_ep can't be NULL.
- Connections opened using passive endpoints should inherit the
  properties of the fi_info struct used to open the passive endpoint.
  Store the info struct in the passive endpoint and grab the source
  address up front so it doesn't have to be retrieved each time.
- pep->pep_src_addr is set to the fabric address, even if 0 is passed as
  the src addrlen.

Closes #1801.

@goodell 

Signed-off-by: Ben Turrubiates <bturrubi@cisco.com>

### CODE REVIEW

File: prov/usnic/src/usdf.h [hunk 1]
```diff
@@ -173,6 +173,7 @@ struct usdf_pep {
 	struct sockaddr_in pep_src_addr;
 	enum usdf_pep_state pep_state;
 	struct usdf_poll_item pep_pollitem;
+	struct fi_info *info;
```
Comment (goodell) [inline prov/usnic/src/usdf.h]: `pep_info` would be better and match the rest of the struct's naming scheme

File: prov/usnic/src/usdf_pep.c [hunk 2]
```diff
@@ -667,6 +652,7 @@ usdf_pep_open(struct fid_fabric *fabric, struct fi_info *info,
 		if (pep->pep_sock != -1) {
 			close(pep->pep_sock);
 		}
+		free(pep->info);
```
Comment (goodell) [inline prov/usnic/src/usdf_pep.c]: should this be `fi_freeinfo` instead?

Comment (bturrubiates) [inline prov/usnic/src/usdf_pep.c]: > should this be fi_freeinfo instead?

oops, good catch.

File: prov/usnic/src/usdf.h (hunk 1 above)
Comment (bturrubiates) [inline prov/usnic/src/usdf.h]: > pep_info would be better and match the rest of the struct's naming scheme

true

**Comment by bturrubiates** [comment]
Updated

**Comment by goodell** [comment]
:+1:
