### PR TITLE
prov/usnic: fix klockwork issues

### LINKED ISSUE #3295: prov/usnic: klocworks reported issues
Sorry about the formatting...

usdf_fabric.c: 231
```c
230 	                                    sin = calloc(1, sizeof(*sin));
231 	                                    *sin = *dest;
```
calloc could return a NULL and fail. *sin = *dest would fail due to the NULL pointer.

-----

usdf_fabric.c: 265
```c
263	                                    address_string = strdup(src);
264	                                    fi->src_addr = address_string;
265	                                    fi->src_addrlen = strlen(address_string);
```
strdup(src) may fail resulting in address_string = NULL and having it used in fi->src_addrlen = strlen(address_string); which will fail.

-----

usdf_fabric.c: 250
```c
249	                                    sin = calloc(1, sizeof(*sin));
250	                                    sin->sin_family = AF_INET;
```
calloc could return a NULL and fail. sin->sin_family = AF_INET would fail due to the NULL pointer.
 
-----

usdf_domain.c: 299
```c
285 	                 case FI_ADDR_STR:
286 	                                    sin = usdf_format_to_sin(info, info->src_addr);
287 	                                    goto skip_size_check;
288 	                 default:
289 	                                    ret = -FI_EINVAL;
290 	                                    goto fail;
291                  }
292
293                  if (info->src_addrlen != addrlen) {...}
297
298 	skip_size_check:
299	                 if (sin->sin_family != AF_INET ||
```
It is possible that calloc in ofi_str_to_psmx is NULL. usdf_str_toaddr assumes the outaddr is not NULL and returns the value to usdf_format_to_sin which could segfault on line 299 in usdf_domain.c.

-----
 
usdf_av.c: 482
```c
470                                    if (addr_format_str) {
471	                                                       usdf_str_toaddr(addr_str[i], &cur_sin);
472	                                                       sin = cur_sin;
473                                    }
474
475	                                    dest = NULL;
476	                                    u_dest = NULL;
477	                                    ret = usdf_av_alloc_dest(&dest);
478                                    if (ret == 0) {
479	                                                       USDF_DBG_SYS(AV, "usd_create_dest(addr=0x%x, port=0x%x)\n",
480	                                                                          ntohl(sin->sin_addr.s_addr), ntohs(sin->sin_port));
481	                                                       ret = usd_create_dest(av->av_domain->dom_dev,
482	                                                                          sin->sin_addr.s_addr, sin->sin_port,
```
ofi_str_toaddr eventually calls calloc to allocate memory for the addr variable. If calloc fails, then the value for addr will be NULL. usdf_str_toaddr does not check that the value of outaddr is not NULL and thus allows a NULL value to be set and used which can segfault later in the program.

-----

usdf_av.c: 371
```c
364                                    if (addr_format_str) {
365	                                                       usdf_str_toaddr(addr_str[i], &cur_sin);
366	                                                       sin = cur_sin;
367                                    }
368
369	                                    /* find the address we actually need to look up */
370	                                    ret = usnic_nl_rt_lookup(dap->uda_ipaddr_be,
371	                                                                          sin->sin_addr.s_addr, dap->uda_ifindex,
```
ofi_str_toaddr eventually calls calloc to allocate memory for the addr variable. If calloc fails, then the value for addr will be NULL. usdf_str_toaddr does not check that the value is not NULL and thus allows a NULL value to be set and used which can segfault later in the program.

-----
 
usdf_ep_rdm.c: 876
```c
858	                                    case FI_ADDR_STR:
859	                                                       sin = usdf_format_to_sin(info, info->src_addr);
860	                                                       break;
861	                                    default:
862	                                                       return -FI_EINVAL;
863                                    }
864                 } else {...}
871
872	                 rx->r.rdm.rx_sock = socket(AF_INET, SOCK_DGRAM, 0);
873                 if (rx->r.rdm.rx_sock == -1) {...}
876	                 ret = bind(rx->r.rdm.rx_sock, (struct sockaddr *)sin, sizeof(*sin));
```
It is possible that calloc in ofi_str_to_psmx is NULL. usdf_str_toaddr assumes the outaddr is not NULL and returns the value to usdf_format_to_sin which could segfault later in the program once the value is used.

### PR DESCRIPTION
**Pull request by jsquyres**
Take care of a bunch of corner cases where allocations can fail.

Signed-off-by: Jeff Squyres <jsquyres@cisco.com>

Fixes #3295

### CODE REVIEW

File: prov/usnic/src/usdf_domain.c [hunk 1]
```diff
@@ -285,6 +285,11 @@ usdf_domain_open(struct fid_fabric *fabric, struct fi_info *info,
 		break;
 	case FI_ADDR_STR:
 		sin = usdf_format_to_sin(info, info->src_addr);
+		if (NULL == sin) {
+			free(udp);
```
Comment (bturrubiates) [inline prov/usnic/src/usdf_domain.c]: Potential double free situation: 

1. Free `udp` here
2. Jump to `fail`
3. After jumping to `fail` check `if (udp != NULL)` and try to free it again because it's not. 

I see two ways to fix this: 

1. Don't free `udp` here and let it get handled after jumping to the `fail` label.
2. Free it here anyway, but set `udp = NULL` afterwards.

File: prov/usnic/src/usdf_av.c [hunk 2]
```diff
@@ -469,6 +473,8 @@ usdf_am_insert_sync(struct fid_av *fav, const void *addr, size_t count,
 
 		if (addr_format_str) {
 			usdf_str_toaddr(addr_str[i], &cur_sin);
+			if (NULL == cur_sin)
+				return -FI_ENOMEM;
```
Comment (bturrubiates) [inline prov/usnic/src/usdf_av.c]: Looking at the man page, I don't think we're supposed to return negative return values for this call. Which of course, means the values returned above are problematic. 

> Insertion calls for an AV opened for synchronous operation will return the
number of addresses that were successfully inserted. In the case of failure,
the return value will be less than the number of addresses that was specified.

File: prov/usnic/src/usdf_av.c [hunk 3]
```diff
@@ -469,6 +473,8 @@ usdf_am_insert_sync(struct fid_av *fav, const void *addr, size_t count,
 
 		if (addr_format_str) {
 			usdf_str_toaddr(addr_str[i], &cur_sin);
+			if (NULL == cur_sin)
```
Comment (bturrubiates) [inline prov/usnic/src/usdf_av.c]: I think this should actually be:

```c
if (NULL == cur_sin) {
    if (flags & FI_SYNC_ERR)
        errors[i] = -ENOMEM;

    return ret_count;
}
