### PR TITLE
prov/shm: fix FI_INJECT flag support

### LINKED ISSUE #7478: prov/shm: smr_writemsg() ignored FI_INJECT flag
**Describe the bug**
Noticed this when reading smr source code. According to https://ofiwg.github.io/libfabric/master/man/fi_rma.3.html, fi_writemsg() should use inject when FI_INJECT flags is specified. 

According to code, fi_writmsg on shm provider is `smr_rma_writemsg` which call `smr_generic_rma`. It looks to me like a bug, because this means FI_INJECT was ignored by `smr_rma_writemsg`. IMO, `smr_rma_writemsg` should have called `smr_generic_rma_inject` when FI_INJECT is specified. 

Note, `smr_rma_inject_write` and `smr_rma_inject_writedata` calls `smr_generic_rma_inject` correctly.

### PR DESCRIPTION
**Pull request by aingerson**
Most sendmsg or writemsg calls with FI_INJECT should work
fine without issues, but an assert is added to make sure we don't
use the IOV protocol.

There is an issue when using FI_INJECT and FI_DELIVERY_COMPLETE
or with hmem IPC enabled since those protocols default to an asynchronous
data copy initiated by the remote side. In order to avoid this
incompatbility, add checks in the IPC and IOV paths to make sure that if
we do need FI_DELIVERY_COMPLETE support and immediately copy the data from
the user buffer, use the SAR protocol which supports both flags.

Signed-off-by: aingerson <alexia.ingerson@intel.com>

Fixes #7478

### CODE REVIEW

**Comment by aingerson** [comment]
@wzamazon Thanks for catching that issue. Most cases should work automatically (assuming the user abides by the inject size) since it would go through the bounce buffer protocols anyway. I added an assert to double check that. Note that we cannot call the specific inject calls directly since those deal with one buffer (as opposed to the msg call iovs).
The issue I did see is FI_INJECT being used with IPC or DELIVERY_COMPLETE (which defaults to CMA). I've added some checks to make sure that if we are using DELIVERY_COMPLET that we default to the SAR protocol which will immediately copy it into the bounce buffer.
Let me know what you think. Thanks!

File: prov/shm/src/smr_rma.c [hunk 1]
```diff
@@ -204,7 +207,7 @@ ssize_t smr_generic_rma(struct smr_ep *ep, const struct iovec *iov,
 							     pend, resp);
 				}
 			} else if (total_len <= smr_env.sar_threshold ||
-			    iface != FI_HMEM_SYSTEM) {
+			    iface != FI_HMEM_SYSTEM || op_flags & FI_INJECT) {
```
Comment (wzamazon) [inline prov/shm/src/smr_rma.c:210]: This seems to be using SAR protocol for inject. I wonder if that is correct? should not we always use `smr_format_inject` for inject? I also have a question regarding earlier code (around line 160).

```
if (total_len <= SMR_INJECT_SIZE &&
		   !(op_flags & FI_DELIVERY_COMPLETE) && !use_ipc)
```
It seems if FI_DELIVERY_COMPLETE is requested, we do not use  `smr_format_inject`. I wonder why is that?

Comment (aingerson) [reply prov/shm/src/smr_rma.c:210]: Delivery complete requires a completion when the message arrives - the smr_format_inject protocol assumes FI_INJECT_COMPLETE completion semantics so if the user requests a higher completion level, we can't use that protocol. The SAR protocol is basically using an inject bounce buffer (like the inject protocol) but also has an accompanying response entry to support the delivery complete semantics. As long as the message length is less than the inject size, then the SAR protocol will behave pretty much exactly the same as the inject protocol + response entry

Comment (wzamazon) [reply prov/shm/src/smr_rma.c:210]: I guess I do not understand FI_INJECT_COMPLETE.

From my understanding of the API, when FI_INJECT is specified, libfabric will not write a completion entry. Meanwhile, FI_DELIVERY_COMPLETE is about the timing of the completion entry libfabric wrote. So if libfabric does not write a completion entry (inject), it should not matter.

Comment (shefty) [reply prov/shm/src/smr_rma.c:210]: FI_INJECT and FI_INJECT_COMPLETE are different flags.  FI_INJECT indicates that the buffer must be re-usable upon return from the call.  It does NOT impact the completion of the operation.

Comment (aingerson) [reply prov/shm/src/smr_rma.c:210]: The inject API calls do not generate completions. If FI_INJECT is specified it just means that the application can reuse the buffer immediately after the send call returns. The completion levels refer to at what point a completion is generated. So you could still set FI_INJECT so that you can reuse the buffer immediately but also set FI_DELIVERY_COMPLETE so that you get the completion later. Or, if FI_INJECT and FI_INJECT_COMPLETE were set, then the buffer could be immediately reused and a completion entry would immediately be generated.
From the man pages which might be helpful:
`Conceptually, this means that the fi_inject function behaves as if the FI_INJECT transfer flag were set, selective completions are enabled, and the FI_COMPLETION flag is not specified.`

Comment (wzamazon) [reply prov/shm/src/smr_rma.c:210]: Ah. I see. Thanks for the clarification!

File: prov/shm/src/smr_msg.c [hunk 2]
```diff
@@ -193,14 +193,16 @@ static ssize_t smr_generic_sendmsg(struct smr_ep *ep, const struct iovec *iov,
 	iface = smr_get_mr_hmem_iface(ep->util_ep.domain, desc, &device);
 
 	total_len = ofi_total_iov_len(iov, iov_count);
+	assert(!(op_flags & FI_INJECT) || total_len <= SMR_INJECT_SIZE);
```
Comment (shefty) [inline prov/shm/src/smr_msg.c:196]: Would it be simpler to do:
```
if (op_flags & FI_INJECT) {
    assert(total_len <= SMR_INJECT_SIZE);
    goto sar;
}
```
with a sar label added below, so that we can skip checking op_flags & FI_INJECT repeatedly?

File: prov/shm/src/smr_rma.c [hunk 3]
```diff
@@ -147,11 +147,13 @@ ssize_t smr_generic_rma(struct smr_ep *ep, const struct iovec *iov,
 	iface = smr_get_mr_hmem_iface(ep->util_ep.domain, desc, &device);
 
 	total_len = ofi_total_iov_len(iov, iov_count);
+	assert(!(op_flags & FI_INJECT) || total_len <= SMR_INJECT_SIZE);
```
Comment (shefty) [inline prov/shm/src/smr_rma.c:150]: See comment above for this function as well.  Yeah, using a goto to jump down in the middle of the function isn't great, but does avoid repeated checks.

**Comment by aingerson** [comment]
@shefty All of the protocol switch checks are a mess. I'm working on a patch to clean all of it up to reduce all the double checks (which are happening left and right). Let me know if you want me to include it here or I can open a separate PR for it after this is merged.

**Comment by aingerson** [comment]
Jenkins failure is a node demand issue (passed shm checks, timed out on tcp for no available nodes). Appveyor looks like a server error. Both are unrelated.

**Comment by shefty** [comment]
A separate PR for the restructured checks is good.

**Comment by shefty** [comment]
Appveyor reported an internal server error.  None of this code is built on windows, correct, even with EFA?  @wzamazon @aingerson

**Comment by aingerson** [comment]
As far as I know yes. I think we can ignore.
