### PR TITLE
fabric: Fix utility functions for tag format conversion

### LINKED ISSUE #3751: fi_tag_bits() and fi_tag_format() work incorrectly?
These two functions may be working incorrectly:

```
uint64_t fi_tag_bits(uint64_t mem_tag_format)
{
        return UINT64_MAX >> (ffsll(htonll(mem_tag_format)) -1);
}
 
uint64_t fi_tag_format(uint64_t tag_bits)
{
        return FI_TAG_GENERIC >> (ffsll(htonll(tag_bits)) - 1);
}
```

My intuitive understanding of the intention of algorithm is that the `ffsll(htonll(x))` part tries to find the location of the most significant "1". However, the function `ffsll()` only finds the least significant "1". The call to `htonll()` swaps bytes on little endian machines, but that doesn't affect bits order within the byte, and it has no effect on big endian machines.

As an example, if I reserve 4 top most bits from a 64-bit tag to leave 60-bit effective tag, the resulting "tag_bits" should be `0x0FFFFFFFFFFFFFFFULL`, and the "tag_format" should be `0x0AAAAAAAAAAAAAAAULL`. However, these two functions don't convert as expected:

```
fi_tag_bits(0x0AAAAAAAAAAAAAAAULL) = 0x7FFFFFFFFFFFFFFFULL
fi_tag_format(0x0FFFFFFFFFFFFFFFULL) = 0xAAAAAAAAAAAAAAAAULL
```

### PR DESCRIPTION
**Pull request by j-xiong**
The functions fi_tag_bits() and fi_tag_format() didn't work as
expected.

Signed-off-by: Jianxin Xiong <jianxin.xiong@intel.com>

Fixes #3751 

@shefty

### CODE REVIEW

File: src/common.c [hunk 1]
```diff
@@ -78,14 +78,30 @@ int fi_poll_fd(int fd, int timeout)
...
+{
+	int pos = 0;
+
+	while (x) {
+		x >>= 1;
+		pos++;
+	}
+
+	return pos;
+}
```
Comment (shefty) [inline src/common.c]: There's an existing function, fi_size_bits(), that I think does the same thing.  Maybe we can rename fi_size_bits() to ofi_msb() as a common function.

File: src/common.c [hunk 2]
```diff
@@ -78,14 +78,30 @@ int fi_poll_fd(int fd, int timeout)
...
+
 uint64_t fi_tag_bits(uint64_t mem_tag_format)
 {
-	return UINT64_MAX >> (ffsll(htonll(mem_tag_format)) -1);
+	return UINT64_MAX >> (64 - msb(mem_tag_format));
 }
```
Comment (shefty) [inline src/common.c]: It's actually taken me more than just a couple seconds to figure out what these functions are trying to do.  I wonder if we can't come up with better names.  Something like ofi_max_tag() seems like a better option for this call.

File: src/common.c [hunk 3]
```diff
@@ -78,14 +78,30 @@ int fi_poll_fd(int fd, int timeout)
...
 
 uint64_t fi_tag_format(uint64_t tag_bits)
```
Comment (shefty) [inline src/common.c]: And this function is treating the input as a max_tag_value, rather than using it as some number of bits.  Maybe we can rename the parameter?

File: src/common.c (hunk 1 above)
Comment (j-xiong) [reply src/common.c]: Yes you are right, fi_size_bits() does the same thing although it's not obvious from the function name. Renaming the function sounds good. What is the guideline to use "ofi_" prefix vs "fi_" prefix for non-API functions?

File: src/common.c (hunk 2 above)
Comment (j-xiong) [reply src/common.c]: I agree ofi_max_tag() would be a better name.

File: src/common.c (hunk 3 above)
Comment (j-xiong) [reply src/common.c]: Yes we can rename the parameter as max_tag_value. In the psm2 provider, the parameter passed to the call is actually named that way.

While we are here, it may also make sense to change the function name to ofi_tag_format() for consistency.

File: src/common.c (hunk 1 above)
Comment (shefty) [reply src/common.c]: The ofi prefix is for all things internal.  The fi prefix should be reserved for public facing APIs and structures.  There's just a lot of fi prefix still in use that has never been converted to ofi.  I may try to work on that this week.  It's just a lot of potential changes.

File: src/common.c (hunk 3 above)
Comment (shefty) [reply src/common.c]: Thanks - that makes sense too.

File: src/common.c (hunk 1 above)
Comment (j-xiong) [reply src/common.c]: fi_size_bits() behaves slightly differently. When the input is 0, fi_size_bit() would return 1 which is incorrect. msb() returns 0 in this case.
