### PR TITLE
prov/shm: Fix unsigned comparison introduced in #6948

### LINKED ISSUE #6963: SHM provider compilation warning
Got the following warning from SHM provider. Looks like a bug to me:

```
  CC       prov/shm/src/src_libfabric_la-smr_rma.lo
prov/shm/src/smr_progress.c: In function 'smr_progress_resp_entry':
prov/shm/src/smr_progress.c:123:34: warning: comparison of unsigned expression < 0 is always false [-Wtype-limits]
      *err = (pending->bytes_done < 0)
                                  ^

prov/shm/src/smr_progress.c:151:32: warning: comparison of unsigned expression < 0 is always false [-Wtype-limits]
    *err = (pending->bytes_done < 0)
                                ^
prov/shm/src/smr_progress.c: In function 'smr_progress_inline':
prov/shm/src/smr_progress.c:226:22: warning: comparison of unsigned expression < 0 is always false [-Wtype-limits]
   return (*total_len < 0) ? ((int) *total_len) : -FI_ETRUNC;
                      ^
prov/shm/src/smr_progress.c: In function 'smr_progress_inject':
prov/shm/src/smr_progress.c:259:22: warning: comparison of unsigned expression < 0 is always false [-Wtype-limits]
   return (*total_len < 0) ? ((int) *total_len) : -FI_ETRUNC;
                      ^
prov/shm/src/smr_progress.c: In function 'smr_mmap_peer_copy':
prov/shm/src/smr_progress.c:334:22: warning: comparison of unsigned expression < 0 is always false [-Wtype-limits]
    ret = (*total_len < 0)
                      ^
prov/shm/src/smr_progress.c:345:22: warning: comparison of unsigned expression < 0 is always false [-Wtype-limits]
    ret = (*total_len < 0)
                      ^
prov/shm/src/smr_progress.c: In function 'smr_progress_ipc':
prov/shm/src/smr_progress.c:487:21: warning: comparison of unsigned expression < 0 is always false [-Wtype-limits]
   ret = (*total_len < 0) ? ((int) *total_len) : -FI_ETRUNC;
```

### PR DESCRIPTION
**Pull request by PeterGottesman**
Signed-off-by: Peter Gottesman <pgottes@amazon.com>

resolves #6963

### CODE REVIEW

File: prov/shm/src/smr_progress.c [hunk 1]
```diff
@@ -120,7 +120,7 @@ static int smr_progress_resp_entry(struct smr_ep *ep, struct smr_resp *resp,
 				if (pending->bytes_done != pending->cmd.msg.hdr.size) {
 					FI_WARN(&smr_prov, FI_LOG_EP_CTRL,
 						"Incomplete copy from mmapped file\n");
-					*err = (pending->bytes_done < 0)
+					*err = ((ssize_t) pending->bytes_done < 0)
```
Comment (wzamazon) [inline prov/shm/src/smr_progress.c:123]: I am not familiar with the full context. It seems `pending->bytes_done` is return of `ofi_copy_to_hmem_iov`?

So `ofi_copy_to_hmem_iov`  can return  a value "< 0" under certain  situation?

Comment (PeterGottesman) [reply prov/shm/src/smr_progress.c:123]: Yeah, `ofi_copy_to_hmem_iov` returns a negative value in error cases. While `ofi_copy_to_iov` returned a size_t, the hmem variant returns a ssize_t. Changing this to a draft because I think there may be other type conversion issues lurking here.

Comment (wzamazon) [reply prov/shm/src/smr_progress.c:123]: In that case, the return value of `ofi_hmem_copy_iov` should be stored to an variable `ret`, and only if `ret` is < 0, we set error. if `ret >=0`, we update bytes_done and proceed.

Comment (PeterGottesman) [reply prov/shm/src/smr_progress.c:123]: I should have been more specific, the other type conversion issue here is because of the conversion to an int if the conditional is true:
```
((ssize_t) *total_len < 0) ? ((int) *total_len) : -FI_ETRUNC;
```

Type conversion from an unsigned 64 bit to a signed 32 bit integer is undefined behavior in C.

Comment (PeterGottesman) [reply prov/shm/src/smr_progress.c]: Let me know how it looks now. I didn't conditionally set `*total_len` where that is used because it is unused when an error occurs, but I did conditionally set `pending->bytes_done` if no error occurred.

File: prov/shm/src/smr_progress.c [hunk 2]
```diff
@@ -110,19 +111,23 @@ static int smr_progress_resp_entry(struct smr_ep *ep, struct smr_resp *resp,
 			break;
 		if (pending->cmd.msg.hdr.op == ofi_op_read_req) {
 			if (!*err) {
-				pending->bytes_done =
+				hmem_copy_len =
```
Comment (wzamazon) [inline prov/shm/src/smr_progress.c:114]: I think the variable name should be `ret`, it is not always length.

File: prov/shm/src/smr_progress.c [hunk 3]
```diff
@@ -110,19 +111,23 @@ static int smr_progress_resp_entry(struct smr_ep *ep, struct smr_resp *resp,
...
 					ofi_copy_to_hmem_iov(pending->iface,
 							     pending->device,
 							     pending->iov,
 							     pending->iov_count,
 							     0, pending->map_ptr,
 							     pending->cmd.msg.hdr.size);
-				if (pending->bytes_done != pending->cmd.msg.hdr.size) {
+				if (hmem_copy_len < 0) {
+					FI_WARN(&smr_prov, FI_LOG_EP_CTRL,
+						"Copy from mmapped file failed\n");
```
Comment (wzamazon) [inline prov/shm/src/smr_progress.c:123]: also print err code here.

**Review by wzamazon — CHANGES_REQUESTED** [review]

File: prov/shm/src/smr_progress.c (hunk 2 above)
Comment (PeterGottesman) [reply prov/shm/src/smr_progress.c:114]: I didn't use ret because that already exists in some functions and I was trying to maintain uniformity. I didn't just use ret where it already existed because it is an int and we need an ssize_t. Would it make sense to rename `hmem_copy_len` to `hmem_copy_ret`?

Comment (wzamazon) [reply prov/shm/src/smr_progress.c:114]: `hmem_copy_ret` is OK to me.

File: prov/shm/src/smr_progress.c [hunk 4]
```diff
@@ -218,13 +230,22 @@ static int smr_progress_inline(struct smr_cmd *cmd, enum fi_hmem_iface iface,
 			       uint64_t device, struct iovec *iov,
 			       size_t iov_count, size_t *total_len)
 {
-	*total_len = ofi_copy_to_hmem_iov(iface, device, iov, iov_count, 0,
-					  cmd->msg.data.msg, cmd->msg.hdr.size);
-	if (*total_len != cmd->msg.hdr.size) {
+	ssize_t hmem_copy_ret;
```
Comment (wzamazon) [inline prov/shm/src/smr_progress.c:233]: empty line between declaration and implemenation.

**Review by wzamazon — APPROVED** [review]
There seems to be some refactor opportunity here because the same code segment appeared multiple times. but that can be in separate PR.
