### PR TITLE
prov/rxm,verbs: Negotiate credit based flow control support over CM

### LINKED ISSUE #6712: Envariable mismatch on client and server can crash servers
A mismatch between client and server  FI_OFI_RXM_USE_SRX setting can cause server side to crash when client sends an RPC.
For example starting server with FI_OFI_RXM_USE_SRX=1 while client sets its to 0 will lead to server-side crash when using verbs;ofi_rxm

OFI: v1.12.0
Provider: verbs;ofi_rxm

`(gdb) bt
#0  0x00007f66192cb30e in vrb_add_credits ()
   from /home/aaoganez/github/daos/install/lib/daos/TESTING/tests/../../../../prereq/release/mercury/lib/../../ofi/lib/libfabric.so.1
#1  0x00007f66192dfac9 in rxm_handle_comp ()
   from /home/aaoganez/github/daos/install/lib/daos/TESTING/tests/../../../../prereq/release/mercury/lib/../../ofi/lib/libfabric.so.1
#2  0x00007f66192e101b in rxm_ep_do_progress ()
   from /home/aaoganez/github/daos/install/lib/daos/TESTING/tests/../../../../prereq/release/mercury/lib/../../ofi/lib/libfabric.so.1
#3  0x00007f66192e1191 in rxm_ep_progress ()
   from /home/aaoganez/github/daos/install/lib/daos/TESTING/tests/../../../../prereq/release/mercury/lib/../../ofi/lib/libfabric.so.1
#4  0x00007f66192924cd in ofi_cq_progress ()
   from /home/aaoganez/github/daos/install/lib/daos/TESTING/tests/../../../../prereq/release/mercury/lib/../../ofi/lib/libfabric.so.1
#5  0x00007f6619291a0b in ofi_cq_readfrom ()
`

### PR DESCRIPTION
**Pull request by j-xiong**
Credit based flow control only works when both sides support it.
Exchange the information over the connetion manager and disable
flow control if support is missing from either side.

To help this, a new method 'available()' is added to flow_ctrl_ops and
the hook provider is updated to handle this new method.

Signed-off-by: Jianxin Xiong <jianxin.xiong@intel.com>

Fix #6712 
Replace #7480

### CODE REVIEW

**Review by shefty — APPROVED** [review]
Thanks - did you figure out the issue?  Was it related to the peer_flow_ctrl field being needed?

**Comment by j-xiong** [comment]
Yes. The issue was that the CONNECTED event from the accepting side was not properly handled. The addition of peer_flow_ctrl field made the logic simpler.

**Comment by j-xiong** [comment]
Added a default implementation of the available() method. Should fix the CI failures.

**Comment by j-xiong** [comment]
Jenkins CI repetitively had one test (10 rank spawn_rootargs) hanging for 6 hours and then got killed. This was with rxm+verbs. This seems to be a real issue related to the change.

**Comment by wzamazon** [comment]
typo in the title of commit message. "negociate" -> "negotiate"

**Comment by j-xiong** [comment]
@wzamazon Thanks! That's why the title felt strange to me :)

**Comment by j-xiong** [comment]
Pushed update that fixes the CI failure. When enabling flow control, preposted recvs should be properly counted for.

File: prov/verbs/src/verbs_domain.c [hunk 1]
```diff
@@ -56,12 +80,28 @@ static void vrb_set_credit_handler(struct fid_domain *domain_fid,
...
+
+	if (vrb_flow_ctrl_available(ep_fid)) {
+		ofi_genlock_lock(&cq->util_cq.cq_lock);
+		/*
+		 * peer_rq_credits is initialized to UINT64_MAX (same as -1).
+		 * It is possible credit updates arrived earlier. The new
+		 * credit should be (received credits + 1).
+		 */
+		ep->peer_rq_credits += 2;
+		ofi_genlock_unlock(&cq->util_cq.cq_lock);
```
Comment (shefty) [inline prov/verbs/src/verbs_domain.c:104]: I find this confusing.  The credit scheme overall isn't great, at it uses a counter based mechanism (+10 new messages can now be sent), rather than a sliding window sort of scheme (send up to message ID 400).  This results in weird initialization like rq_credits_avail = -1, and the non-intuitive setting of peer_rq_credits += 2 when enabling.

I think there's a good chance this would be simpler if we switched to a window credit scheme instead.  Then we could have something like:
```
if (peer_rq_credits == UINT64_MAX)
    peer_rq_credits = 1;
```
Even if we kept to a counter scheme, I would have expected the above flow to be:
```
if (peer_rq_credits == UINT64_MAX)
    peer_rq_credits = 1;
else
    peer_rq_credits++;  /* both sides assume 1 credit to start with */
```
I understand why the +2 is in the above code, but it's not intuitive at all and seems likely to confuse someone else down the line.

Bad news is that changing the credit scheme changes the protocol.

Comment (shefty) [reply prov/verbs/src/verbs_domain.c:104]: Actually, this changes the CM protocol anyway.  We should handle that.  Gah.

**Comment by shefty** [comment]
I'm analyzing the credit code to see if there's some reasonable way out of this, which keeps the credit counts in an intuitive state.

File: prov/rxm/src/rxm_conn.c [hunk 2]
```diff
@@ -491,6 +489,17 @@ void rxm_process_connect(struct rxm_eq_cm_entry *cm_entry)
...
+		conn->peer_flow_ctrl = cm_entry->data.accept.flow_ctrl;
+	}
+
+	if (conn->flow_ctrl & conn->peer_flow_ctrl) {
+		domain = container_of(conn->ep->util_ep.domain,
+				      struct rxm_domain, util_domain);
+		if (!domain->flow_ctrl_ops->enable(conn->msg_ep)) {
+			domain->flow_ctrl_ops->
+				set_threshold(conn->msg_ep,
+					      conn->ep->msg_info->rx_attr->size / 2);
```
Comment (shefty) [inline prov/rxm/src/rxm_conn.c:501]: Should enable and set_threshold be combined into a single call?

File: prov/verbs/src/verbs_domain.c (hunk 1 above)
Comment (j-xiong) [reply prov/verbs/src/verbs_domain.c:104]: One way is to use a different variable to track the received credit before flow control is enabled:
```
peer_rq_credits = saved_peer_credit + 1;  /* both sides assume 1 credit to start with */
```

File: prov/rxm/src/rxm.h [hunk 3]
```diff
@@ -78,7 +78,8 @@ union rxm_cm_data {
 		uint8_t ctrl_version;
 		uint8_t op_version;
 		uint16_t port;
-		uint8_t padding[2];
+		uint8_t flow_ctrl;
+		uint8_t padding;
```
[the remark this answers is not in the document]
Comment (j-xiong) [reply prov/rxm/src/rxm.h:82]: yep, that can be done.

File: prov/verbs/src/verbs_domain.c (hunk 1 above)
Comment (shefty) [reply prov/verbs/src/verbs_domain.c:104]: That sounds good.  I think we want to keep protocol compatibility.  That requires changing the value of flow_ctrl mentioned above.

File: prov/rxm/src/rxm_conn.c (hunk 2 above)
Comment (j-xiong) [reply prov/rxm/src/rxm_conn.c:501]: I think so, given that the available() method already serves the original purpose of status checking.

**Comment by j-xiong** [comment]
Updated to address all the review comments.

**Review by shefty — APPROVED** [review]
Thanks - this is easier to follow, even if it does add a branch into add_credits.

**Comment by j-xiong** [comment]
Some cosmetic changes.
