### PR TITLE
prov/rxm: Mode bits fixes

### LINKED ISSUE #3167: rxm providers disppeared
After updating to commit c57d7f6 (was 53e5534), rxm providers (e.g., sockets;ofi_rxm, verbs;ofi_rxm) do not show up from fi_getinfo.

To reproduce, just run fi_info.

### PR DESCRIPTION
**Pull request by a-ilango**
- Before calling fi_getinfo on core provider, disable modes that rxm can't
  support and add modes that rxm can support.
- Also update MR mode bit requirement in man page

Fixes #3167

### CODE REVIEW

File: prov/rxm/src/rxm_init.c [hunk 1]
```diff
@@ -49,16 +60,19 @@ int rxm_info_to_core(uint32_t version, struct fi_info *hints,
...
 			if (hints->domain_attr->mode)
 				core_info->domain_attr->mode = hints->domain_attr->mode;
 		}
+	} else {
+		/* Since hints is NULL fake support for FI_MR_BASIC to allow
+		 * discovery of core providers like verbs which require it */
+		if (FI_VERSION_GE(version, FI_VERSION(1, 5)))
+			core_info->domain_attr->mr_mode |= OFI_MR_BASIC_MAP;
+		else
+			core_info->domain_attr->mr_mode = FI_MR_BASIC;
```
Comment (shefty) [inline prov/rxm/src/rxm_init.c]: I think this can be UNSPEC, which is allowed to return either basic or scalable. Otherwise, you won't pick up scalable providers or use that feature if the provider does support it.

Comment (a-ilango) [inline prov/rxm/src/rxm_init.c]: Thanks. Updated it to FI_MR_UNSPEC.
