### PR TITLE
include/fi_peer, efa, shm, sm2: update peer srx API to allow for peer modification of the rx_entry

### LINKED ISSUE #9227: prov/efa: cq data not available with FI_PEEK
**Describe the bug**
In MPICH, we transmit the source rank of pt2pt messages using CQ data when available. In testing MPICH+efa, we found that an `MPI_Probe` operation does not return the correct source rank in the MPI_Status object. The cause seems to be that the CQ data is not available for FI_PEEK operations processed in `util_srx_peek`.

**To Reproduce**
1. configure and build MPICH 4.1.2 with libfabric main branch or v1.19.0rc1. EDIT: adding additional configure flags to speed up build time:
```
./configure --with-device=ch4:ofi --with-libfabric=</path/to/install> --with-datatype-engine=dataloop --disable-cxx --disable-fortran
```
2. Build and run this MPI reproducer using MPICH+efa. This can be done on a single node with the environment variable `MPIR_CVAR_NOLOCAL=1`.
```
mpicc foo.c
MPIR_CVAR_NOLOCAL=1 mpiexec -n 2 ./a.out
```

```c
#include <mpi.h>
#include <assert.h>
#include <stdlib.h>

int main(void) {
  MPI_Init(NULL, NULL);

  int rank;
  MPI_Comm_rank(MPI_COMM_WORLD, &rank);

  if (rank == 1) {
    MPI_Send(NULL, 0, MPI_DATATYPE_NULL, 0, 0, MPI_COMM_WORLD);
  }

  if (rank == 0) {
    MPI_Status status;
    MPI_Probe(MPI_ANY_SOURCE, 0, MPI_COMM_WORLD, &status);
    assert(status.MPI_SOURCE == 1);
    MPI_Recv(NULL, 0, MPI_DATATYPE_NULL, MPI_ANY_SOURCE, 0, MPI_COMM_WORLD, &status);
    assert(status.MPI_SOURCE == 1);
  }

  MPI_Finalize();
  return 0;
}
```

**Expected behavior**
The above reproducer should complete normally without triggering either assertion.

**Output**
With `FI_LOG_LEVEL=debug`, we see this output directly before the assert failure:
```
libfabric:52078:1692287803::efa:ep_data:efa_rdm_msg_generic_recv():926<debug> efa_rdm_msg_generic_recv: iov_len: 0 tag: 0 ignore: 60000000000000 op: 1 flags: 1080000
libfabric:52078:1692287803::core:ep_ctrl:util_srx_peek():620<debug> Message not found
libfabric:52079:1692287803::efa:ep_data:efa_rdm_msg_generic_recv():926<debug> efa_rdm_msg_generic_recv: iov_len: 0 tag: 0 ignore: 6000007fffffff op: 1 flags: 1080000
libfabric:52079:1692287803::core:ep_ctrl:util_srx_peek():620<debug> Message not found
libfabric:52078:1692287803::efa:ep_data:efa_rdm_msg_generic_recv():926<debug> efa_rdm_msg_generic_recv: iov_len: 0 tag: 0 ignore: 60000000000000 op: 1 flags: 1080000
libfabric:52078:1692287803::core:ep_ctrl:util_srx_peek():623<debug> Message found
a.out: foo.c:18: main: Assertion `status.MPI_SOURCE == 1' failed.
```

**Environment:**
provider: efa, endpoint type: rdm

**Additional context**
cc: @shijin-aws @aingerson

### PR DESCRIPTION
**Pull request by aingerson**
Fixes #9227

### CODE REVIEW

**Comment by aingerson** [comment]
@shijin-aws @shefty

**Comment by shijin-aws** [comment]
Did I miss anything? I didn't see you modify util_srx_peek to write cq data to cq.

**Comment by aingerson** [comment]
oh duh. no I didn't add that 🤦‍♀️

**Comment by shijin-aws** [comment]
@aingerson Thanks, I will test this PR with the reproducer in https://github.com/ofiwg/libfabric/issues/9227. I think we also need to make rdm_tagged_peek has an option to check cq data. I can work on that in a separate PR.

**Comment by shijin-aws** [comment]
I can confirm this PR fixes https://github.com/ofiwg/libfabric/issues/9227

File: prov/efa/src/rdm/efa_rdm_msg.c [hunk 1]
```diff
@@ -854,13 +854,25 @@ struct efa_rdm_ope *efa_rdm_msg_alloc_rxe_for_tagrtm(struct efa_rdm_ep *ep,
...
 	int pkt_type;
+	struct efa_rdm_base_hdr *base_hdr;
+	uint64_t cq_data, cq_flags;
 
 	peer_srx = util_get_peer_srx(ep->peer_srx_ep);
 	data_size = efa_rdm_pke_get_rtm_msg_length(*pkt_entry_ptr);
 
+	base_hdr = efa_rdm_pke_get_base_hdr(*pkt_entry_ptr);
+	if (base_hdr->flags & EFA_RDM_REQ_OPT_CQ_DATA_HDR) {
+		cq_flags = FI_REMOTE_CQ_DATA;
```
Comment (shijin-aws) [inline prov/efa/src/rdm/efa_rdm_msg.c:865]: Is `FI_REMOTE_CQ_DATA` enough here? Do we need to |= `ofi_rx_cq_flags(ofi_op_tagged)` ?

Comment (aingerson) [reply prov/efa/src/rdm/efa_rdm_msg.c:865]: So far, the peer srx AP flags are only defined for FI_REMOTE_CQ_DATA so I think for now, yes. The peer utility saves the FI_TAGGED | FI_RECV flags in since it knows it is a tagged receive. We should think about more concretely defining the ownership of the flags but that would require extending the flags to the get_msg API as well

Comment (shijin-aws) [reply prov/efa/src/rdm/efa_rdm_msg.c:865]: >The peer utility saves the FI_TAGGED | FI_RECV flags in since it knows it is a tagged receive.

Which peer utility saves those flags?

Comment (aingerson) [reply prov/efa/src/rdm/efa_rdm_msg.c:865]: sorry I meant the util srx here in these changes does that

Comment (shijin-aws) [reply prov/efa/src/rdm/efa_rdm_msg.c:865]: I missed this change 

```
util_entry = util_init_unexp(srx_ctx, addr, size, tag, cq_data,
				     FI_TAGGED | FI_RECV | flags);
```
Should be good, thanks!

**Review by shijin-aws — APPROVED** [review]

File: include/rdma/providers/fi_peer.h [hunk 2]
```diff
@@ -181,7 +182,8 @@ struct fi_ops_srx_owner {
 	int	(*get_msg)(struct fid_peer_srx *srx, fi_addr_t addr,
 			size_t size, struct fi_peer_rx_entry **entry);
 	int	(*get_tag)(struct fid_peer_srx *srx, fi_addr_t addr,
-			size_t size, uint64_t tag, struct fi_peer_rx_entry **entry);
+			size_t size, uint64_t tag, uint64_t cq_data,
+			uint64_t flags, struct fi_peer_rx_entry **entry);
```
Comment (shefty) [inline include/rdma/providers/fi_peer.h:186]: cq_data and flags are completion data.  It seems odd to pass that into a call that is trying to retrieve the buffer.

I wonder if util_init_unexp() is being called from the correct side.  There's a mismatch here setting some of the fi_peer_rx_entry fields based on whether we matched a buffer or not that seems confusing.  The size, cq_data, and flags fields are ignored unless we don't find a match?

Comment (aingerson) [reply include/rdma/providers/fi_peer.h:186]: yes I agree, it seems much. Right now the definition of the peer entry is that only the owner is allowed to touch the fields (hence this change). But the other alternative is to modify the definition so that the peer is allowed to initialize all the variables only in the unexpected case. I think I like that better. Thoughts?

Comment (shefty) [reply include/rdma/providers/fi_peer.h:186]: Because we have a separate queue call, it should be okay for the peer to modify the structure prior to queuing it.

**Comment by aingerson** [comment]
Alright, updated with a different modification of the peer API where we only pass in the necessary fields to match and then allow the peer to modify the fields with extra information

**Review by shefty — APPROVED** [review]
Thanks - need AWS to recheck the fix and EFA changes.

File: prov/efa/src/rdm/efa_rdm_msg.c [hunk 3]
```diff
@@ -812,6 +813,14 @@ struct efa_rdm_ope *efa_rdm_msg_alloc_rxe_for_msgrtm(struct efa_rdm_ep *ep,
 			return NULL;
 		}
 		(*pkt_entry_ptr)->ope = rxe;
+
+		peer_rxe->size = data_size;
```
Comment (shijin-aws) [inline prov/efa/src/rdm/efa_rdm_msg.c:817]: This is non-tagged msg path. You should implement the change in efa_rdm_msg_alloc_rxe_for_tagrtm

Comment (aingerson) [reply prov/efa/src/rdm/efa_rdm_msg.c]: @shijin-aws Sorry about that! Updated.

**Review by shijin-aws — APPROVED** [review]
This revision passed the test for the original issue as well.

**Comment by shijin-aws** [comment]
bot:aws:retest

**Comment by shijin-aws** [comment]
ok to merge

File: man/fi_peer.3.md [hunk 4]
```diff
@@ -482,32 +483,32 @@ the same lock, if needed.
 fi_peer_rx_entry defines a common receive entry for use between the owner and
 peer. The entry is allocated and set by the owner and passed between owner and
 peer to communicate details of the application-posted receive entry. All fields
-are only modifiable by the owner, except for the peer_context which is provided
-for the peer to use to save peer-specific information for unexpected message
-processing. Similarly, the owner_context can be used by the owner_context as
-needed for storing extra owner-specific information.
+are initialized by the owner, except in the unexpected message case where the
+peer can initialize any extra available data before queuing the message with
+the owner. The peer_context and owner_context fields are ony modifiable by the
```
Comment (raffenet) [inline man/fi_peer.3.md:488]:
```suggestion
the owner. The peer_context and owner_context fields are only modifiable by the
```

Comment (aingerson) [reply man/fi_peer.3.md]: Thanks! Updated
