### PR TITLE
prov/sockets: Fix compare buffer bug in fi_compare_atomic

### LINKED ISSUE #1959: prov/sockets: fi_compare_atomic doesn't honor FI_INJECT flag for compare data
When the FI_INJECT flag is set on a context, or provided to fi_compare_atomicmsg() as a flag, the compare data is not being copied to the provider maintained buffer when using the socket provider. The compare data should be copied to the inject buffer similar to what is being done with the buf data.

### PR DESCRIPTION
**Pull request by shantonu**
When <code>FI_INJECT</code> is set as a flag in <code>fi_compare_atomic</code>, the compare data was not being copied to the internal buffer. This should fix #1959.

@jithinjosepkl
Signed-off-by: Shantonu Hossain <shantonu.hossain@intel.com>

### CODE REVIEW

**Comment by jithinjosepkl** [comment]
@shantonu - Thanks for the patch. This patch writes the compare_buf to the TX ringbuffer. In addition to this, we need to read this data from the ringbuffer (rather than reading it directly from the compare-buffer) while sending out the atomic op control message.

**Comment by shantonu** [comment]
Thanks! I have updated <code>sock_pe_new_tx_entry</code> to read from the ring buffer in case <code>FI_INJECT</code> flag is set.

File: prov/sockets/src/sock_atomic.c [hunk 1]
```diff
@@ -161,24 +163,41 @@ ssize_t sock_ep_tx_atomic(struct fid_ep *ep,
...
 
-	src_len = 0;
+	src_len = dst_len = 0;
 	if (flags & FI_INJECT) {
 		for (i = 0; i < msg->iov_count; i++) {
 			sock_tx_ctx_write(tx_ctx, msg->msg_iov[i].addr,
 					  msg->msg_iov[i].count * datatype_sz);
 			src_len += (msg->msg_iov[i].count * datatype_sz);
 		}
+		for (i = 0; i < compare_count; i++) {
```
Comment (jithinjosepkl) [inline prov/sockets/src/sock_atomic.c]: While processing the ringbuffer, the compare iovecs/data are expected after result iovecs. Doing it here will result in data corruption.

File: prov/sockets/src/sock_atomic.c [hunk 2]
```diff
@@ -161,24 +163,41 @@ ssize_t sock_ep_tx_atomic(struct fid_ep *ep,
...
+			dst_len += comparev[i].count * datatype_sz;
+		}
 	} else {
 		for (i = 0; i < msg->iov_count; i++) {
 			tx_iov.ioc.addr = (uintptr_t) msg->msg_iov[i].addr;
 			tx_iov.ioc.count = msg->msg_iov[i].count;
 			sock_tx_ctx_write(tx_ctx, &tx_iov, sizeof(tx_iov));
 			src_len += (tx_iov.ioc.count * datatype_sz);
 		}
+		for (i = 0; i < compare_count; i++) {
```
Comment (jithinjosepkl) [inline prov/sockets/src/sock_atomic.c]: Same comment as above.

File: prov/sockets/src/sock_progress.c [hunk 3]
```diff
@@ -2323,6 +2327,12 @@ static int sock_pe_new_tx_entry(struct sock_pe *pe, struct sock_tx_ctx *tx_ctx)
 					msg_hdr->msg_len += datatype_sz *
 						pe_entry->pe.tx.tx_iov[i].src.ioc.count;
 			}
+			for (i = 0; i < pe_entry->pe.tx.tx_op.atomic.cmp_iov_len; i++) {
+				rbread(&tx_ctx->rb, &pe_entry->pe.tx.tx_iov[i].cmp,
+				 	sizeof(pe_entry->pe.tx.tx_iov[i].cmp));
+				msg_hdr->msg_len += datatype_sz *
+					pe_entry->pe.tx.tx_iov[i].cmp.ioc.count;
+			}
```
Comment (jithinjosepkl) [inline prov/sockets/src/sock_progress.c]: Ok, noticed that the ringbuffer processing is updated as well. Now, compare-buffer is expected after src_buffer. 👍

File: prov/sockets/src/sock_atomic.c (hunk 1 above)
Comment (shantonu) [inline prov/sockets/src/sock_atomic.c]: I have changed the processing part as well. I grouped the ringbuffer copy/read in the same place as otherwise another check is needed for compare data.

File: prov/sockets/src/sock_progress.c (hunk 3 above)
Comment (jithinjosepkl) [inline prov/sockets/src/sock_progress.c]: Note that while sending out the atomic op request, the compare data is read from the iovecs. This should be updated to read from the inject buffer (+ offset).

Comment (jithinjosepkl) [inline prov/sockets/src/sock_progress.c]: Also, the src_iov_len in case of inject indicates the total data length (not the iov length). We can follow similar semantics for compare data as well.

Comment (shantonu) [inline prov/sockets/src/sock_progress.c]: ok, will update the cmp_iov_len to the data length for inject case.

**Comment by shantonu** [comment]
Updated the PR with reading from ring buffer while sending out atomic op request in case FI_INJECT flag is set. Modified fabtests/rdm_atomic.c with FI_INJECT op_flags and verified the inject path.

File: prov/sockets/src/sock_progress.c [hunk 4]
```diff
@@ -1826,25 +1826,22 @@ static int sock_pe_progress_tx_atomic(struct sock_pe *pe,
...
 				       &pe_entry->pe.tx.inject[0],
 				       pe_entry->pe.tx.tx_op.src_iov_len, len))
 			return 0;
 		len += pe_entry->pe.tx.tx_op.src_iov_len;
+		/* cmp data */
+		if (sock_pe_send_field(pe_entry,
+					&pe_entry->pe.tx.inject[0] + pe_entry->pe.tx.tx_op.src_iov_len,
+					pe_entry->pe.tx.tx_op.atomic.cmp_iov_len, len))
+			return 0;
+		len += pe_entry->pe.tx.tx_op.atomic.cmp_iov_len;
```
Comment (jithinjosepkl) [inline prov/sockets/src/sock_progress.c]: This violates the wire protocol. Receiver expects the compare data before the src data. Please check sock_pe_process_rx_atomic().

Comment (shantonu) [inline prov/sockets/src/sock_progress.c]: Fixed the ordering.

File: prov/sockets/src/sock_progress.c [hunk 5]
```diff
@@ -1826,25 +1826,31 @@ static int sock_pe_progress_tx_atomic(struct sock_pe *pe,
...
 	datatype_sz = fi_datatype_size(pe_entry->pe.tx.tx_op.atomic.datatype);
-	for (i = 0; i < pe_entry->pe.tx.tx_op.atomic.cmp_iov_len; i++) {
+	if (pe_entry->flags & FI_INJECT) {
+		/* cmp data */
 		if (sock_pe_send_field(pe_entry,
-				       (void *) (uintptr_t) pe_entry->pe.tx.tx_iov[i].cmp.ioc.addr,
-				       pe_entry->pe.tx.tx_iov[i].cmp.ioc.count *
-				       datatype_sz, len))
+					&pe_entry->pe.tx.inject[0],
+					pe_entry->pe.tx.tx_op.atomic.cmp_iov_len, len))
```
Comment (jithinjosepkl) [inline prov/sockets/src/sock_progress.c]: @shantonu - For the inject case, you are writing cmp_data at tx.inject[0] + src_len. But, in here, it is read from tx.inject[0].

File: prov/sockets/src/sock_progress.c [hunk 6]
```diff
@@ -1826,25 +1826,31 @@ static int sock_pe_progress_tx_atomic(struct sock_pe *pe,
...
-		len += (pe_entry->pe.tx.tx_iov[i].cmp.ioc.count * datatype_sz);
-	}
-
-	/* data */
-	if (pe_entry->flags & FI_INJECT) {
+		len += pe_entry->pe.tx.tx_op.atomic.cmp_iov_len;
+		/* data */
 		if (sock_pe_send_field(pe_entry,
-				       &pe_entry->pe.tx.inject[0],
+				       &pe_entry->pe.tx.inject[0] + pe_entry->pe.tx.tx_op.atomic.cmp_iov_len,
```
Comment (jithinjosepkl) [inline prov/sockets/src/sock_progress.c]: Similar comment here, the src_data is written at tx.inject[0].

File: prov/sockets/src/sock_progress.c (hunk 5 above)
Comment (shantonu) [inline prov/sockets/src/sock_progress.c]: Oh, sorry! Updated the patch with correct offset.

**Comment by shantonu** [comment]
Modified fabtests/rdm_atomic.c and performed data verification on both inject and non-inject path for CSWAP.
